### ISSUE TITLE
[Bounty] Tronscan V2 - VOTES  REPRESENTATIVES  - votes are not reset to default

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#1]
Bug Report
-------------
step 1:  vote
![image](https://user-images.githubusercontent.com/39301026/40128471-fbfd4c5e-5931-11e8-88db-530a447406ab.png)

step 2: submit the vote
![image](https://user-images.githubusercontent.com/39301026/40128529-21df5a5c-5932-11e8-8eee-bf98fa6a455b.png)

step 3: start a new voting:
![image](https://user-images.githubusercontent.com/39301026/40128569-3a7a23b2-5932-11e8-9275-e36b040b29da.png)

the website has memorized the values:
![image](https://user-images.githubusercontent.com/39301026/40128590-49046852-5932-11e8-95d7-0d6139af963c.png)

-after voting the values should be set to default
-the values remain even if you change the website

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
16. may 2018 6pm (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

**Comment by Rovak** [comment]
This is intended behavior, if you decided to redistribute your votes differently then you can just modify your existing votes

**Comment by PMD3VSolution** [comment]
Ok thank you for the update!
