### ISSUE TITLE
I Cant recieve TRON or Send it!

### ISSUE THREAD

**Issue by CryptoInvesta** [tronscan/tronscan-frontend#1003]
Tron scan doesn't work!!! i need HELP! 

I'm losing out on voting!!!!! 

Email me please!

**Comment by CryptoInvesta** [comment]
So my Wallet Address just wont show :(

**Comment by hhanquez** [comment]
Same for me

Trying to check my wallet address, I got a bad gateway error when calling `https://wlcyapi.tronscan.org/api/system/status`

`(Access to XMLHttpRequest at 'https://wlcyapi.tronscan.org/api/system/status' from origin 'https://tronscan.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.)`
