### ISSUE TITLE
tokens can not sent

### ISSUE THREAD

**Issue by Dirkbelgie** [tronscan/tronscan-frontend#1005]
i always get this message in TronLink when i wanna sent my tokens to another account

**errorMessage">class org.tron.core.exception.ContractValidateException : No asset !**

and there are a lot tokens on my account in tronlink

Who can help me

**Comment by a49688448** [comment]
please use private key to login

**Comment by Dirkbelgie** [comment]
Dear

when i copy paste my private key ,it won t work in tronscan

and i m sure the key is correct

and i usue this link 

https://tronscan.github.io/tronscan-frontend/#/
 
Dirk Anthoni
 
 
-------Oorspronkelijk bericht-------
 
Van: Wendy Yi
Datum: 01/13/19 07:31:33
Aan: tronscan/tronscan-frontend
Cc: Dirkbelgie;  Author
Onderwerp: Re: [tronscan/tronscan-frontend] tokens can not sent (#1005)
 
please use private key to login

**Comment by a49688448** [comment]
dear 
please login here
https://tronscan.org/#/
