### ISSUE TITLE
Participate in TRON token doesn't accept tokens

### ISSUE THREAD

**Issue by gabi777** [tronscan/tronscan-frontend#1006]
Hi ,

I've tried to participate in many different tokens but they all come back with errors. Today the error is "Login to the wallet first" when the wallet is already logged in. I've been able to use wallet with other dapps just not Participate. Yesterday the error didn't mention wallet but just came up with ! Error. 

Please look into this bug so people can start contributing to tokens again. thanks

**Comment by a49688448** [comment]
participate with tronlink is in fixing.
please use private key to participate.
