### ISSUE TITLE
Please Whitelist My Token DEP On Tronscan [1001909]

### ISSUE THREAD

**Issue by NishantSinghOfficial** [tronscan/tronscan-frontend#1008]
[TronscanTokenInformationSubmissionTemplate.xlsx](https://github.com/tronscan/tronscan-frontend/files/2752844/TronscanTokenInformationSubmissionTemplate.xlsx)
[whitepaper.docx](https://github.com/tronscan/tronscan-frontend/files/2752845/whitepaper.docx)

**Comment by a49688448** [comment]
token is under review.contact
roy@tron.network

**Comment by NishantSinghOfficial** [comment]
i already send my all documents and information to roy@tron.network but
still no responce from that side. please push my message to him for
whitelistining my token DEP TRC10 Token ID- 1001909
