### ISSUE TITLE
cant see oreder at current order

### ISSUE THREAD

**Issue by cakrafals** [tronscan/tronscan-frontend#1009]
I intend to sell my ante first, I sell it on goc, but I cancel the order and I move the order to tronscan but from 1/11/2019  8:00 AM until now my order does not appear in the current order. What should I do?

**Comment by a49688448** [comment]
I highly recommend you join in telegram group.
tele:https://t.me/trxmarket2018

TRX.MARKET Please report your problem here :

https://docs.google.com/forms/d/e/1FAIpQLSeCQOYwdSMal-gvYD2zguy8PmZ9e-VjfxY6Adrlwb3p7ggSMA/viewform

TRON Foundation
