### ISSUE TITLE
tokens TRC10 can not sent

### ISSUE THREAD

**Issue by robertg1974** [tronscan/tronscan-frontend#1010]
I always get this message in TronScan when i wanna sent my tokens to another account.
What is wrong? 
![zavrnjena_transakcija](https://user-images.githubusercontent.com/27872021/51085706-71ba7600-173d-11e9-925e-5413d554e6d1.png)

**Comment by a49688448** [comment]
use private key not tronlink,please.
tronlink integrate with tronscan has some bugs, in repair.

**Comment by robertg1974** [comment]
I use Tronscan with keystore file, not use Tronlink

**Comment by mrencar** [comment]
I have the same problem and I'm using a Ledger Nano S on Tronscan

**Comment by Captainherb** [comment]
I am also experiencing this problem with my Ledger Nano S on Tronscan.  Cannot send my IGG for the swap.
