### ISSUE TITLE
Nano Ledger S Show TRX SEEDS Only Have 14 Using TronWatch Never Update

### ISSUE THREAD

**Issue by elvintay2000** [tronscan/tronscan-frontend#1011]
Hi, 
Please help me to check my Nano Ledger S show TRX SEEDS only have 14 coin if i using TronWatch to check but never update every day, i have vote 100% to Sesameseed

My Nano Ledger S TRX Account: TGmGJHfJdm7dEv3XdqxH4THpqFxPz7C2uH

![nanoledgers](https://user-images.githubusercontent.com/45877990/51087254-cd135500-178b-11e9-8e4f-7e37480ab761.JPG)

![nanoledgers-1](https://user-images.githubusercontent.com/45877990/51087278-3b581780-178c-11e9-9ac9-6d1e7ae4bbb2.JPG)

![nanoledgers-2](https://user-images.githubusercontent.com/45877990/51087321-c33e2180-178c-11e9-80b4-01f94f0cf6ca.JPG)

please advice how to correct my seeds current should be 21 to my nanoledger S

Thank you

**Comment by a49688448** [comment]
in repairing
