### ISSUE TITLE
TRXMarket taking funds but not creating order

### ISSUE THREAD

**Issue by 5u8v3r7** [tronscan/tronscan-frontend#1012]
Many people are having issues with orders not showing up.  I placed an order this morning for 130,000 TRX and it never showed up in the books and did not fill:
here is the txid:
f2622aa4de587831876515b5f9a06f8c9a0e7f57b12ab5aa4cded81512b7f4bb
![trx missing](https://user-images.githubusercontent.com/41802168/51088955-a4f40980-172b-11e9-8097-929679c2bb5e.PNG)
The screenshot shows I cancelled an order at 10:35, I tried to replace the order in the tx above at 10:42 and it simply never showed up and my TRX is gone.

**Comment by a49688448** [comment]
I highly recommend you join in telegram group.
tele:https://t.me/trxmarket2018

TRX.MARKET Please report your problem here :

https://docs.google.com/forms/d/e/1FAIpQLSeCQOYwdSMal-gvYD2zguy8PmZ9e-VjfxY6Adrlwb3p7ggSMA/viewform

TRON Foundation
