### ISSUE TITLE
Market taking TRX but i dint got PLAY

### ISSUE THREAD

**Issue by aleksandar343** [tronscan/tronscan-frontend#1014]
I was try to buy 250 000 PLAY on tronscan market but TRX is gone but i never got PLAY and no creating order too

**Comment by a49688448** [comment]
I highly recommend you join in telegram group.
tele:https://t.me/trxmarket2018

TRX.MARKET Please report your problem here :

https://docs.google.com/forms/d/e/1FAIpQLSeCQOYwdSMal-gvYD2zguy8PmZ9e-VjfxY6Adrlwb3p7ggSMA/viewform

TRON Foundation
