### ISSUE TITLE
Missing my rey tokens

### ISSUE THREAD

**Issue by skaminski90** [tronscan/tronscan-frontend#1015]
992fcc708d80ef4284c67eec2eef0bf076f9619f1d6691c2bf5d806b7fa59fb2

Thats my hash #. I never recieved my millions of $rey even tho tronscan.org took my 918 trx ... can anyone help here? Please

**Comment by a49688448** [comment]
I highly recommend you join in telegram group.
tele:https://t.me/trxmarket2018

TRX.MARKET Please report your problem here :

https://docs.google.com/forms/d/e/1FAIpQLSeCQOYwdSMal-gvYD2zguy8PmZ9e-VjfxY6Adrlwb3p7ggSMA/viewform

TRON Foundation
