### ISSUE TITLE
Ledger Nano unable to verify transactions

### ISSUE THREAD

**Issue by Captainherb** [tronscan/tronscan-frontend#1017]
Greetings,
I am consistently receiving error messages when I attempt to vote or send tokens.  I am using a Ledger Nano S.  After around a dozen failed attempts to verify a transaction, I am able to vote, even after the failure message comes up.  However, I am unable to send any tokens at all.  Please help.

Thank you, Herb Shoemaker
ffherb@sbcglobal.net

**Comment by a49688448** [comment]
ledger problem will be fixed in this Wednesday

**Comment by Captainherb** [comment]
OK, its now Thursday and I am still unable to send my IGG for the swap; same error message!

**Comment by Captainherb** [comment]
And now its Friday and still I cannot send my IGG.

**Comment by Captainherb** [comment]
Still not working, and its Sunday.  Ive been trying for over a week now!  Ive updated the firmware on my Ledger, reinstalled the Tronscan program, tried the Github frontend and the Tronscan app........nothing allows me to transfer my IGG for the swap.  Keeps saying, "Something went wrong while submitting this transaction."Please, can you really fix this????Can I also retrieve all the tokens I have sent from my GuildChat wallet that never arrived on Tronscan?Thank you,Herb

    On Monday, January 14, 2019, 8:08:42 PM PST, Wendy Yi <notifications@github.com> wrote:  
 
 
ledger problem will be fixed in this Wednesday

**Comment by Captainherb** [comment]
Hello,
My problem has now progressed to the point that I cannot even open my Tronscan PC Desktop Wallet.  The app connects to my wallet, but, when I try to open it, it says, "No Open Wallet to View."
This is becoming so frustrating and is costing me money.  

PLEASE ADVISE!!!!
Herb Shoemaker
