### ISSUE TITLE
Missing coins

### ISSUE THREAD

**Issue by nskendrovic** [tronscan/tronscan-frontend#1027]
Hey.

I placed an order for ANTE with TRX.
Order is not showing anywhere..i miss over 20.000 TRX coins . Its been hours.

Plese help

**Comment by mlomba04** [comment]
I also did the same. I placed an order for ANTE with TRX. Roughly 23,000 coins. My order has never gone through. Any ideas on whats going on?

**Comment by nskendrovic** [comment]
I dont know bud, but im pissed. I subbmited a feedback form.

Go on Telegram and ask in chat they will give you link for support.
