### ISSUE TITLE
i can't move my seed out of my tronscan desktop, please help !

### ISSUE THREAD

**Issue by Lorenzo-ipb** [tronscan/tronscan-frontend#1028]
i can't move my SEED out of my tronscan wallet on my desktop, i receved them regularly, can see the transaction but they're not showing up to move it & always show a 0
 :-( 
please help !!!

**Comment by Lorenzo-ipb** [comment]
nobody to answers? no one knows ??

**Comment by Rovak** [comment]
use tronscan.org, desktop version is deprecated
