### ISSUE TITLE
Can't Unfreeze Tron (Ledger Nano S)

### ISSUE THREAD

**Issue by ungrenandrew** [tronscan/tronscan-frontend#1034]
I am unable to unfreeze my TRX holdings. I have waited a week and haven't had any luck. Among many other issues, this is by far the most frustrating.

**Comment by cypheron** [comment]
Same here.

**Comment by MiguelPachecoEOS** [comment]
me too, still with the issue?

**Comment by cypheron** [comment]
Issue is fixed with latest ledger app. I compiled it from source, think it's not been released yet.
