### ISSUE TITLE
Cannot withdraw from tronscan

### ISSUE THREAD

**Issue by lehman888** [tronscan/tronscan-frontend#1038]
Hello,

I cannot withdrawal my coins from tronscan with my ledger nano s.

Mostly when logging in with the ledger get "no open wallet to view", and after trying multiple times sometimes i get logged in but after want to send coins it will get stuck there when i press send.

Could you give me some support so i can withdrawal my coins?

**Comment by dkyng2482** [comment]
im trying to log in myself and keep getting the No open wallet to view message as well ...its bloody annoying

**Comment by lehman888** [comment]
Can somebody help us???

**Comment by lehman888** [comment]
Tried tronscan-frontend and cannot even log in with the ledger, it stays “open the tron app on your ledger” while tron app is already open.

**Comment by BillioniresMind** [comment]
Use the actual TronScan website with your Ledger Nano S... https://tronscan.org
