### ISSUE TITLE
Cant Freeze TRX

### ISSUE THREAD

**Issue by Uruisg** [tronscan/tronscan-frontend#1046]
I cant freeze my Tron balance to get Energy, Bandwidth, or Power. Receive error message that says "Something went wrong while trying to freeze Tron"

**Comment by Bitelbola** [comment]
The same is happening to me. I tried the desktop tronscan app and also the web app version... same result.

**Comment by cypheron** [comment]
@Uruisg @bitelbola you guys using ledger?

**Comment by Bitelbola** [comment]
Yes I'm using ledger. Updated firmware and everything.

**Comment by cypheron** [comment]
I'm guessing there is an issue with Tron blockchain and the ledger app. I read something about an upcoming update for the app, hopefully it will fix these issues.
