### ISSUE TITLE
tronscan withdrawal not possible

### ISSUE THREAD

**Issue by lehman888** [tronscan/tronscan-frontend#1049]
When will the issue with the withdrawal will be possible on desktop tronscan with the ledger nano s????????????????????????????????????????????????????????????????????????????????????????????

**Comment by obhutara** [comment]
It still not working :(
I m stuck i hate tron

**Comment by caroldorrell** [comment]
I can't transfer any of my TRX to an exchange.  Is there anyone who can respond with an answer?

**Comment by obhutara** [comment]
Hey, I tried reducing the amount of Tron to send. i.e leave a few tron on
your wallet on Tron scan and it might work

**Comment by caroldorrell** [comment]
No luck.  Can't send my TRX anywhere, but I can see it on wallet.

**Comment by obhutara** [comment]
Oh. That's sad. Keep trying with a few lesser trx to send and maybe try
downloading a desktop client wallet which might work. I had similar
troubles for a day and thankfully it went through I'll avoid Tron now. It's
quite shady :(

**Comment by MiguelPachecoEOS** [comment]
You can go to the official site and do all you need from there: https://tronscan.org
