### ISSUE TITLE
I no longer have access to my TRX since my Ledger nano s

### ISSUE THREAD

**Issue by Skyloop236** [tronscan/tronscan-frontend#1051]
Hello, my dear,
When I log on to my Ledger nano’s wallet TRON tells me: "No open wallet to display trx" when 1 week ago I did have my TRX on. What happens?

**Comment by HansHeiri** [comment]
same problem. a few hours ago i had access via tronscan and right now i cant login (desktop and frontend)

**Comment by Skyloop236** [comment]
Yes, I did, and it all came back, thank God! A GREAT THANK YOU for your return, which has allowed me to rediscover the serenity I love .

Very good evening to you!
Edwin
