### ISSUE TITLE
My accounts show 0.

### ISSUE THREAD

**Issue by rayoca03** [tronscan/tronscan-frontend#1058]
I sent a small amount that shows up on the transaction page but shows 0 on account balance. Then I sent a large amount that showed up in the right place so I sent a little more.  Now I show a 0 balance.
![screenshot 7](https://user-images.githubusercontent.com/35036461/51755503-d1dde000-208c-11e9-90a3-2183271a9278.png)
![screenshot 6](https://user-images.githubusercontent.com/35036461/51755507-d6a29400-208c-11e9-96a5-1e7ec44875f9.png)

**Comment by Rovak** [comment]
Please contact the developer of the wallet
