### ISSUE TITLE
transferring TRX from Tronscan isn't working 

### ISSUE THREAD

**Issue by caroldorrell** [tronscan/tronscan-frontend#1064]
Hello, I am trying to transfer my TRX from the Tronscan wallet to an exchange.  When I hit send, it looks like something is processing on my screen but 1 and 1/2 hours later still nothing.  
Any ideas why this is happening?
Thanks,
Carol

**Comment by a49688448** [comment]
is there a picture? what error did you get?

**Comment by caroldorrell** [comment]
No error, just looks like its sending but nothing happens.  TRX logo just spins around.  I left it for a few hours yesterday and nothing happened.  
![tronscan send transaction](https://user-images.githubusercontent.com/47088215/51842626-51fb8400-22df-11e9-966c-c4326229f39e.jpeg)

**Comment by caroldorrell** [comment]
Are there any admins on this site??

**Comment by ibnzUK** [comment]
i have same problem when sending TRC20,
