### ISSUE TITLE
Ledger shows wrong wallet address

### ISSUE THREAD

**Issue by frostman7** [tronscan/tronscan-frontend#1065]
Since updating MCU and firmware on my ledger my trx wallet address has changed and now opens a different wallet with zero balance. I restored with original seed and still shows a different wallet. My ledger has only ever had one 24 word seed. How can I access my original wallet?

**Comment by frostman7** [comment]
Hey Rovak, Know anyone who could get into my ledger/tron account? I would be happy to offer payment to get access to my tokens.

 

Kind Regards

 

James Frost

Director | Foliage Landscapes Pty Ltd

p: 0402 158 312 

L. QBCC 1308284 



Proud Members of Landscape QLD

**Comment by Rovak** [comment]
Hi @frostman7, CryptoChain has an alternative Ledger Wallet which you should be able to use https://twitter.com/_CryptoChain_/status/1094659230932656129
