### ISSUE TITLE
Request TRX for Testing

### ISSUE THREAD

**Issue by steffensq** [tronscan/tronscan-frontend#107]
Hi,

I am unable to receive TRX when requesting for testing from the Account main page. I have tested with three separate accounts and each account has been unsuccessful.

(1) I receive the following error:
"Limit (1 requests) reached for address"

(2) Or when creating a new account to test "receive TRX" the following may be displayed:
"Already requested 1 times in the last hour"

I've seen mention of the account addresses being stored in a DB to prevent excessive repeat request. When the error message (1) is display, is my account now a lost cause and a new one will need to be generated to receive TRX? Any help would be much appreciated.

**Comment by Rovak** [comment]
The account which distributes TRX has ran out of coins, the account will be resupplied soon

**Comment by steffensq** [comment]
Okay, can you help clarify if my address is stored in a queue waiting for TRX to be distributed? Or do I have to follow TPwJS5eC5BPGyMGtYTHNhPTB89sUWjDSSu transaction ages to determine when the account is active and reapply for TRX? How often is the account resupplied? I'm now 5 days in with 5 separate accounts and can't seem to be issued TRX for the life of me. Please help provide a more detailed response.
