### ISSUE TITLE
Trx_market sell order tokens disappeared

### ISSUE THREAD

**Issue by Demy500** [tronscan/tronscan-frontend#1071]
I Put A sell order on tronscan.org,  1.300000,00 igg, the sell order is not visible on current order and also not visible on my tradings. My tokens are also no longer in my wallet!? 
Under transaction the hash is visible and confirmd. Who can tell me where the tokens are.

best regards

**Comment by SaintUtila** [comment]
I'm in the same exact boat as you are man. Sold my IGG, my transaction is confirmed, but no tron at all. Let me know if you get this resolved and how you did so. Gotta raise hell I guess.

**Comment by Demy500** [comment]
After waiting for more than 2 days, the sell order was in the current order.
Per transaction you need bandwidth and energy to trade on the trx network, if this is too low the transaction gets a lot of delay. 
Hope it is the same with you! 
Bad thing that the community (trx_market) never responded, I send a mail and a tweet. I had to figure out everything by myself

**Comment by SaintUtila** [comment]
It's been more than 3 days and I still haven't gotten it yet sigh.........................the weird thing is that it says that I still have all of my IGG when I click the IGG tab in the exchange and the TRC-20 token tab on my account page says it's still there. But it's not in my Tronlink wallet.

**Comment by SaintUtila** [comment]
I figured it out. I just needed energy in my account by freezing some Tron and the sell order went fine. I appreciate the help.
