### ISSUE TITLE
BTT/TRX

### ISSUE THREAD

**Issue by mgt825** [tronscan/tronscan-frontend#1076]
have tried to buy BTT everyday since it has been listed... steady going up and i am missing out because of issues on tronscan side..it wont let me purchase any still.......come on I've owned tron for over a year.  where is the customer service....

**Comment by Lstork121** [comment]
i think if your trx is on tronscan you should be getting free btt.  Not 100 % sure but just maybe.

**Comment by mgt825** [comment]
Nice! I wish it would let me buy in!

**Comment by ronsimmonds** [comment]
The BTT air drop was yesterday and I've yet to see any BTT in my wallet.  Anyone actually receive any BTT yet from yesterday's air drop?
