### ISSUE TITLE
Trx, Freeze and vote problem

### ISSUE THREAD

**Issue by 1N3mo** [tronscan/tronscan-frontend#1078]
HI, 
i have tried to "Freeze" a certain amount of my TRX many many times over, and i keep on getting a notification that there is an "error". I also tried to vote for a super representative and even though the votes go trough the "error" message keeps coming out. 1 out of 10 times is when my request to do something actually goes trough so its getting kinda anoying , this used to be a great wallet to keep my TRX and get the tokens , but not it seems kinda forgoten. 
Is there anyting i can do to change this? 

Thanks in Advance.

**Comment by BillioniresMind** [comment]
Same thing going on with my voting. This needs sorting out if Tronscan want us to continue using it.

![vote error](https://user-images.githubusercontent.com/39076539/52516290-2a31e780-2c20-11e9-9dd8-b06f1a62b024.png)
