### ISSUE TITLE
No open Wallet ??

### ISSUE THREAD

**Issue by tronnoob** [tronscan/tronscan-frontend#1080]
I connected my ledger, opened tronscan selected open wallet. selected ledger  it found my ledger wallet address, I clicked open and all I get is a message saying "no open wallet to view"

how can I fix this, what is the issue ?

**Comment by tronnoob** [comment]
ok just read on reddit that you were working on a fix for this issue 2 months ago, when is it likely to be fixed ?

**Comment by TonyMcC** [comment]
Great!!!!.....just when you need to get into your wallet!
also having issues with freeze and token delivery
