### ISSUE TITLE
Tron "No open wallet to view"

### ISSUE THREAD

**Issue by MambaTime** [tronscan/tronscan-frontend#1083]
Hi, I am trying to get into my TRON wallet through my Ledger Nano S but I keep getting the error "No open wallet to view". Can you please assist me on this issue? I need to locate my TRON tokens.

Regards,
Dennis

**Comment by lendellkirk** [comment]
I get the same message. I froze a large amount of tokens and was looking forward to unfreezing but now have no open wallet to view

**Comment by lendellkirk** [comment]
I also used ledger nano s

**Comment by 1N3mo** [comment]
Same here
