### ISSUE TITLE
No Open wallet

### ISSUE THREAD

**Issue by atmhobby** [tronscan/tronscan-frontend#1084]
Ledger blue will not open when I click on open wallet on tron-scan.

**Comment by 1N3mo** [comment]
Same here

**Comment by atmhobby** [comment]
I used the link below and it worked!  
https://tronscan.org/#/

**Comment by Terrygil** [comment]
atmhobby, what steps did you take? I clicked on "Sign in" then chose "Ledger" and nothing happens.

**Comment by atmhobby** [comment]
I plug my ledger into the laptop, log into my ledger and then click on ledger on the desktop in the upper right drop down.  A window appears waiting for me to open tron on my ledger then i click ok on desktop.

**Comment by Terrygil** [comment]
That's what I'm doing and in the window that appears can't seem to see my ledger although I'm logged into it and Tron app is open on the ledger.

**Comment by Terrygil** [comment]
Thanks for the response.

**Comment by atmhobby** [comment]
Can you send a screen shot of what you see on your screen?

**Comment by Terrygil** [comment]
I was able to get in to the Tronscan desktop app once but tried it again and got the message again "No open wallet to view" but the screen shot is from the url you posted.

![image](https://user-images.githubusercontent.com/45721409/52585063-6a988d80-2df9-11e9-85a2-681d51c9248e.png)

**Comment by atmhobby** [comment]
https://tronscan.org/#/account
 Try this.

**Comment by Terrygil** [comment]
Same thing, I can put my wallet address in the search bar and see everything but it I have to login for any actions.

![image](https://user-images.githubusercontent.com/45721409/52586368-f7911600-2dfc-11e9-808a-c8aa035fac51.png)

**Comment by atmhobby** [comment]
I have one last idea.  Are you using the USB cable that your ledger came with?

**Comment by Terrygil** [comment]
I tried a different browser and it worked. I was using firefox and then tried it on the brave browser. I am using the ledger cable. It's got to be something about the browser. Thanks for your time and help.

**Comment by atmhobby** [comment]
So glad it worked for you.  It is an awful feeling not to be able to access!
Good Luck
