### ISSUE TITLE
Desktop Tronscan Not Working

### ISSUE THREAD

**Issue by guardtorah** [tronscan/tronscan-frontend#1085]
Tronscan for the Desktop is not longer working and has not worked for a while.

**Comment by 1N3mo** [comment]
Same here

**Comment by Lstork121** [comment]
same here, is it because of the btt coin airdrop?

**Comment by fati1601** [comment]
same here

**Comment by enrico22** [comment]
same here

**Comment by Rovak** [comment]
Tronscan desktop is no longer maintained, Ledger is now supported by the web version at https://tronscan.org
