### ISSUE TITLE
Using Ledger Nano S.  Worked fine 2 days ago, now, doesn't

### ISSUE THREAD

**Issue by plentius** [tronscan/tronscan-frontend#1088]
It says the Nano is connected; but when I try to open the wallet, it says there's no wallet open to view.

Two days ago it worked fine and I was able to send some TRX to Binance.  But now it doesn't work at all. 

![nano connected popup](https://user-images.githubusercontent.com/35902941/52543063-2f478180-2d5b-11e9-80db-36a42e79a5f2.jpg)

![no open wallet to view](https://user-images.githubusercontent.com/35902941/52543076-44bcab80-2d5b-11e9-84eb-4e5693ca4634.jpg)

**Comment by str87xr** [comment]
why are you closing this, please i have this same problem...

**Comment by plentius** [comment]
I am not closing this -- I don't know why it's being closed either.  I did
find a way to get around it though:  I went to *https://tronscan.org/#/account
<https://tronscan.org/#/account>* instead and that worked fine.

Hope this helps.

* <http://www.jonAdamson.com>* <http://www.JonAdamson.com>

**Comment by str87xr** [comment]
Thank you, it worked:)

**Comment by plentius** [comment]
You're very welcome.  Glad it worked for you too.  :-)

* <http://www.jonAdamson.com>* <http://www.JonAdamson.com>
