### ISSUE TITLE
[Bounty] Tronscan V2 -  Merge pull request #106 from DevObs1/master - duplicate keys

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#109]
Bugfix
-------

![image](https://user-images.githubusercontent.com/39301026/40892021-e23c97ee-6790-11e8-83e5-0bb5e03e66d9.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
02. June 2018 5:00 am (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

Bounty Program
--
https://twitter.com/justinsuntron/status/1002072890349531137

**Comment by DevObs1** [comment]
Already fixed in https://github.com/tronscan/tronscan-frontend/pull/111

**Comment by PMD3VSolution** [comment]
fixed
