### ISSUE TITLE
Why doesn't my Tron wallet on Tronscan load?  It has been stuck "Loading Wallet" for 1 week now....

### ISSUE THREAD

**Issue by tcash2** [tronscan/tronscan-frontend#1090]
Why doesn't my Tron wallet on Tronscan load?  It has been stuck "Loading Wallet" for 1 week now....

**Comment by shirt62** [comment]
What was the resolution on this?  I am having the exact same issue.

**Comment by Rovak** [comment]
use https://tronscan.org
