### ISSUE TITLE
I cannot access my ledger wallet on tronscan

### ISSUE THREAD

**Issue by mikeyg4** [tronscan/tronscan-frontend#1092]
Just says no wallet to view..any answers? thanks

**Comment by ronsimmonds** [comment]
This has been happening to me as well for quite some time now.  Unfortunately Tronscan doesn't appear to be a very reliable or robust application.  I usually need to close Tronscan and reopen my Ledger wallet about 9 or 10 times before it finally shows the actual Tron contents.  VERY annoying.
