### ISSUE TITLE
where is my BTT?

### ISSUE THREAD

**Issue by ronsimmonds** [tronscan/tronscan-frontend#1094]
I've had frozen Tron for several weeks now in Tronscan.  As of writing this the evening of February 12th I have yet to receive any BTT.   Anyone else in the same boat?  If I had received some shouldn't I be able to see them in my account view on Tronscan???

**Comment by Rovak** [comment]
Airdrops are unrelated to the tronscan project

**Comment by ronsimmonds** [comment]
But the fact that 9 times out of 10 my Ledger Tron wallet opens up complete empty is very relevant to the Tronscan project but you deleted that post anyway.
Sounds like a power trip to me.
    On Tuesday, February 12, 2019, 11:13:38 p.m. MST, Roy van Kaathoven <notifications@github.com> wrote:  
 
 
Airdrops are unrelated to the tronscan project

**Comment by Rovak** [comment]
the desktop client is no longer maintained, please use https://tronscan.org

**Comment by ronsimmonds** [comment]
Would have been nice to have been notified.either through email or in the app itself.
    On Friday, February 15, 2019, 7:32:55 p.m. MST, Roy van Kaathoven <notifications@github.com> wrote:  
 
 
the desktop client is no longer maintained, please use https://tronscan.org
