### ISSUE TITLE
Ledger Wallet - Wallet not open

### ISSUE THREAD

**Issue by TopCapCrypto** [tronscan/tronscan-frontend#1095]
I have been trying for two days, tronscan finds ledger and wallet address, authorized and opened on ledger - but nothing happens.

Is there anyway of opening my wallet?

**Comment by TopCapCrypto** [comment]
Why was the tread closed? I didn't get an answer?

**Comment by Rovak** [comment]
There have been multiple issues posted with the same question, please check if anyone asked the question before posting a new one

**Comment by TopCapCrypto** [comment]
Hi Roy, I have checked several treads and seen some suggestions which I tried and did not work.

 

Is there an official response to the issue?

 

Niall
