### ISSUE TITLE
no open wallet to view

### ISSUE THREAD

**Issue by dvr28** [tronscan/tronscan-frontend#1098]
For the past 24 hours my Tronscan account has said "no open wallet to view"
Has anyone had this issue resolved and how long did it take?

**Comment by 240516** [comment]
Hi there I exactly have the same problem but don't know what to do? And i wanna add one thing how we can get/withdraw Btt tokens through tronscan. Your help would be much appreciated.

**Comment by dvr28** [comment]
I was actually trying to log in to tronscan to look at the btt. I don’t know how to transfer from there as it is telling me I have “no wallet”. 
Sorry.

**Comment by LargeRaj** [comment]
i also have this "no open wallet to view" my nano s appears to be working fine and am able to open the wallet after seeing ledger connected. just no damn coins there ? wth

**Comment by dvr28** [comment]
Mine is the same.  Nono S is working and I can open the account. Just no wallet to view ( no tokens)

**Comment by 240516** [comment]
Good news for everyone whose tronscan is not working and they see "no open wallet". Just do these simple steps.
1. Uninstall your desktop Tronscan folder.
2. Simply go on "Tronscan.org" 
3. Signin through your Nano Ledger S and there you can see your Tron balance and your BTT tokens.

It worked for me and I transfered my BTT token to Binance which is successful as well. 
Happy days all tension is gone.

So follow these steps and be happy my friends😎

**Comment by dvr28** [comment]
Thanks for the advice.

I have uninstalled the desktop Tronscan.
I have loaded Tronscan.org.
I have signed in using my nano S and opened the TRON app but the wallet won’t show.

This did not work.

**Comment by dvr28** [comment]
Ah I just loaded TronLink as the extension to Chrome and now it works 

Thank you
