### ISSUE TITLE
My ledger is not opening the wallet - Ive never had this happen before

### ISSUE THREAD

**Issue by str87xr** [tronscan/tronscan-frontend#1099]
My ledger is not opening the wallet - Ive never had this happen before.  Please advise.  I have 4000 TRX and have been with you since nov 2016.  This makes me nervous.

**Comment by ronsimmonds** [comment]
I had created a similar error ticket yesterday and it was deleted by Admin.  It appears there is next to no support for the Tronscan application.  Can anyone suggest a better Tron wallet app?

**Comment by TonyMcC** [comment]
Have same issue... Then again I am having an issue with my Ledger install after update
May be a Ledger issue...

**Comment by str87xr** [comment]
Yes, there is a closed thread close to this one with 13 or 14 replies. In the messages youll find a new link that works. I would send it to you but I’m not with my computer right now.

**Comment by str87xr** [comment]
Found it: https://tronscan.org/#/account

**Comment by ronsimmonds** [comment]
That actually worked!  Thank you.  Don't bother with the Tronscan app, open your Tronscan wallet in the browser with the above link.

**Comment by str87xr** [comment]
:)

Raul
7869420419
