### ISSUE TITLE
TRX wallet on Tronscan disappeared 

### ISSUE THREAD

**Issue by dvr28** [tronscan/tronscan-frontend#1101]
Tronscan is telling me I have "no open wallet to view".  

It has been like this for a few days now.  No help from anyone.

I use a Nano S to open my wallet so I don't understand how it can go missing.

Starting to think TRON has scammed us. 

I had over 70,000 trx and now nothing. 

Dont trust TRONSCAN or TRON.

**Comment by Fahy1** [comment]
Im really disappointed in tron for this as I am having the same problem, What can we do as there is no support available

**Comment by dvr28** [comment]
Hi. 

Step 1. Delete Tronscan from your desk top.
Step 2. Using Google chrome open  https://tronscan.org <https://tronscan.org/> 
Step 3. Connect TronLink. (It is the first option in the drop down.
Step 4. Use your ledger nano S to open your account. 

I hope this helps.

**Comment by Fahy1** [comment]
SuccessThank you SO much dvr28 for your help, much appreciated     On Friday, 15 February 2019, 22:23:53 GMT, dvr28 <notifications@github.com> wrote:  
 
 Hi. 

Step 1. Delete Tronscan from your desk top.
Step 2. Using Google chrome open https://tronscan.org <https://tronscan.org/> 
Step 3. Connect TronLink. (It is the first option in the drop down.
Step 4. Use your ledger nano S to open your account. 

I hope this helps.

**Comment by dvr28** [comment]
Cool. Glad it worked for you too.

**Comment by AKEK114** [comment]
I have issue of missing TRX (Approx 25k) from my Windows Tron Wallet. This I came to know once I tried to check in few weeks time yesterday. My wallet receive address is TDSRex4NF5egmpZdCUhMXjBvt77BGpAvbV

Can anyone help why TRX are not shown or how to recover? I tried few times with TRX customer service and feedback but ALAS they are really not in mood to help apparently .. at least as of now.

**Comment by dvr28** [comment]
Hi. 

Step 1. Delete Tronscan from your desk top.
Step 2. Using Google chrome open  https://tronscan.org 
Step 3. Connect TronLink. (It is the first option in the drop down.
Step 4. Use your ledger nano S to open your account. 

I hope this helps.

**Comment by AKEK114** [comment]
Hi

Thx for guidance. However I dont have -   Step 4. Use your ledger nano S to
open your account. ?
So can I do with out hardware wallet to try recovering.

Thx

**Comment by AKEK114** [comment]
Thx a lot, I found my TRX  following your guideline :)

**Comment by dvr28** [comment]
Cool
