### ISSUE TITLE
Amount value in /api/transfer endpoint

### ISSUE THREAD

**Issue by jkincali** [tronscan/tronscan-frontend#1104]
Not really an issue, but more of a request for confirmation....
The amounts that are listed in the response to the /api/transfer endpoint in the "amount" field are not strings but numbers.  If the token queried is TRX ( _ ), it safe to multiply that amount by (10 ^ -6) to get the actual amount in every case?

**Comment by Mashud22** [comment]
ok

**Comment by Mashud22** [comment]
ok
