### ISSUE TITLE
Don't see my 22000 coins on tronscan when I open my wallet with ledger

### ISSUE THREAD

**Issue by TonyBallon** [tronscan/tronscan-frontend#1105]
Hello,
I wanted to check my wallet to see if I had received the BTT.
However, when I opend my tronscan wallet with Ledger, my wallet looks completely empty.

What happend?

**Comment by TonyBallon** [comment]
Probably have to do with the nodes, which I don't see at all. Nodes count = 0

**Comment by robballonoff** [comment]
Did you find out what happened? Same thing happened to me and I am pretty clueless what to do here at this point...

**Comment by TonyBallon** [comment]
If you go to the website tronscan.org and login with your ledger from there you will see your TRX amount again. 

The Tron Windows APP for Windows still doesn't work on my computer.

**Comment by robballonoff** [comment]
Thanks for the response. I actually did figure it out. For some reason I was using a GitHub address for my Tron access. And when I went directly like you're suggesting, everything was fine. I'm not sure how I ended up with that first address to begin with. But it always worked in the past until yesterday. Thanks again!Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by Rovak** [comment]
tronscan desktop is no longer maintained

**Comment by robballonoff** [comment]
Actually, it is through the following link (at least it is for those who use Ledger Live):TRON BlockChain Explorer 
  
|  
|   
|   
|   |    |

   |

  |
|  
|   |  
TRON BlockChain Explorer
 Tronscan allows you to explore and search the TRON blockchain for transactions,accounts,tokens,nodes,votes and m...  |   |

  |

  |

 
Rob B
