### ISSUE TITLE
Tronscan.org can't login

### ISSUE THREAD

**Issue by lostdutchman2** [tronscan/tronscan-frontend#1107]
Trying to login to tronscan.org with my private key and the login button is not highlighted for me to click it?

**Comment by lostdutchman2** [comment]
I am using the same exact private key I have used for almost a year someone please help.

**Comment by lostdutchman2** [comment]
I have checked my address all my balances are there its just that tronscan wont let me login.

**Comment by Rovak** [comment]
closing, discussed issue through twitter messenger
