### ISSUE TITLE
Tronscan web unable to withdraw (Send) tokens (TRC-10) when using Ledger Nano S

### ISSUE THREAD

**Issue by PabloTheViking** [tronscan/tronscan-frontend#1115]
I have frequently been withdrawing (Sending) tokens from my wallet and using Ledger Nano S to confirm the transactions. Until recently this is no longer working. When I use the Send-feature I am asked to confirm the transaction on the Ledger Nano S (Confirm the transaction on your ledger). When I do so, the whole process just hangs and I am eventually being thrown back to the original withdrawal (Send) window. This problem is regarding any type of TRC-10 tokens, eg. TRX, BTT, TronEuropeRewardCoin (TERC) etc. I am using Windows 10 and Google Chrome (Version 72.0.3626.119 - 64bit). Please look into this issue ASAP. This seems to be a general issue which is affecting all Ledger users who are using Tronscan.org.

**Comment by Rovak** [comment]
I just tried to send TRX myself and it worked flawlessly, i'm using ubuntu. There is a known issue with the latest Google Chrome which might be the cause https://support.ledger.com/hc/en-us/articles/360018810413-U2F-timeout-in-Chrome-browser

**Comment by PabloTheViking** [comment]
I installed the Opera browser and it worked :-). So the problem is related to the Google Chrome/Ledger support issue you sent the link to. Thank you!
