### ISSUE TITLE
Unable to freeze coins with Ledger Nano S

### ISSUE THREAD

**Issue by blassaut** [tronscan/tronscan-frontend#1116]
Hello,

I'm unable to freeze coins with Ledger Nano S using tronscan, could you advise ?

I can't see any FREEZEBALANCECONTRACT type in my transactions as well while performing such action.

**Comment by Rovak** [comment]
This is an issue with the latest version of Chrome https://support.ledger.com/hc/en-us/articles/360018810413-U2F-timeout-in-Chrome-browser

Please use Opera until chrome publishes a fix
