### ISSUE TITLE
Tron Wallet

### ISSUE THREAD

**Issue by nguyenev** [tronscan/tronscan-frontend#1117]
All the TRX in my wallet is suddenly gone. Can someone help me?

**Comment by Rovak** [comment]
what is your wallet address?

**Comment by nguyenev** [comment]
Trim switched over to a new block and I didn’t know. Is that why all my Tron is lost? Can I recover it?

**Comment by Rovak** [comment]
could you please provide your wallet address so i can take a look?

**Comment by nguyenev** [comment]
I am in my wallet on my ledger nano s and this is what is says. Where can I find my wallet address?

**Comment by Rovak** [comment]
are you using https://tronscan.org to login with your ledger? tronscan desktop client has been deprecated

**Comment by elvintay2000** [comment]
Try using this below link to check detail what step have moss out, you need to ensure install tron apps in your nanoledger.

https://support.ledger.com/hc/en-us/articles/360006904193-TRON-TRX-

**Comment by nguyenev** [comment]
I didn't know the desktop client was depreciated. The link worked. Thank
you so very much for your help. You are amazing!
