### ISSUE TITLE
cannot unfreeze TRON on tronscan

### ISSUE THREAD

**Issue by britestar7** [tronscan/tronscan-frontend#1119]
cannot unfreeze TRON on tronscan; help would be appreciated!!

**Comment by ATS-ONE** [comment]
Me, too. Can't unfreeze TRX on tronscan.org ... any workaround? The 3 freezing days are over for weeks now ...

**Comment by britestar7** [comment]
Hi,

Was wondering if this happened to anyone else. Sad that there appears to be
no one out there willing to help with this.
Not sure where to go with this but will keep trying to ask around and see
if I can find someone who can help.

Amazed it has not occurred more often.

Seems like it should be possible to find someone involved in creating the
tronscan wallet. If you find anyone, please let me know.

Will do the same for you.

Richard

**Comment by Rovak** [comment]
A recent Chrome update broke U2F, use opera browser until they fix it

**Comment by britestar7** [comment]
WORKED!!! Thank you, Rovak!!

**Comment by britestar7** [comment]
> Me, too. Can't unfreeze TRX on tronscan.org ... any workaround? The 3 freezing days are over for weeks now ...
> 
> Getting a console error in the browser (Chrome and Chromium): "TransportError" - "Failed to sign with Ledger device: U2F TIMEOUT".
> 
> ...but I have confirmed it on Ledger Nano S.

this worked for me:
A recent Chrome update broke U2F, use opera browser until they fix it
