### ISSUE TITLE
BUG TRON TEST NET

### ISSUE THREAD

**Issue by Holyfarmer** [tronscan/tronscan-frontend#112]
Hello, 

I'm a french user of your Tron Test net and if I understand I can claim 10K TRX per account , 
Today with my account I could claim 10K two times with the Tron test net 
![trx](https://user-images.githubusercontent.com/39909388/40917162-87e0a8e0-6802-11e8-8334-f1cbbe488523.jpeg) 

The two claim are the first one and the last one the second one is mine

**Comment by Rovak** [comment]
There are 2 databases that store the addresses who request TRX, it is possible to request 2 times if the load balancer decides to choose a different server. It doesn't really matter if this happens because it is only testing purposes
