### ISSUE TITLE
My tron ​​tokens have disappeared

### ISSUE THREAD

**Issue by Helga110159** [tronscan/tronscan-frontend#1120]
Hello everyone, I had about 10000 Tron tokens on the Tronscanwallet. The access is via the Ledger Nano S. Now I get the message after the login "no wallet available". Where is the mistake. I installed the app live via Ledger, and unlocked the wallet above the charger. Connect with TPNyRAaGLCr5XDbZs3P64QS2bjZYFCfDtL ....
Where is the mistake? About 2 months ago, the tokens were still there!
Where are my tokens?
Please help me!
Helga Tolksdorf

**Comment by Rovak** [comment]
tronscan desktop is no longer being maintained, please use your ledger on tronscan.org
