### ISSUE TITLE
Can not unfreeze energy given to another address

### ISSUE THREAD

**Issue by cryptoguyinza** [tronscan/tronscan-frontend#1127]
If you freeze energy for another address the front end does not allow unfreeze. Stays with "freeze" inactive. Even after the three days.

If you use wallet-cli you can unfreeze. This is Tronscan UI problem.

![image](https://user-images.githubusercontent.com/37824699/53946521-a9ee8d00-40cc-11e9-836d-4c29351d9b31.png)

Here is before, where you can not unfreeze and should be able to.
![image](https://user-images.githubusercontent.com/37824699/53946726-03ef5280-40cd-11e9-846c-2d7ff2bbc949.png)

Then uses wallet-cli to unfreeze
![image](https://user-images.githubusercontent.com/37824699/53946803-2b461f80-40cd-11e9-868d-e03413dfb60f.png)

then it is fine
![image](https://user-images.githubusercontent.com/37824699/53948519-a8bf5f00-40d0-11e9-98d9-d9523528d09e.png)

**Comment by Gitmiyorum** [comment]
Can I use wallet-cli to unfreeze using a Ledger and how would I do that? Any instructions?

**Comment by Gitmiyorum** [comment]
Ok as expected need the private key for that. WIll just wait for a fix. Thanks all!

**Comment by Charlie-Crypto** [comment]
yes, ill wait for a fix also. I hope its fixed soon, 12 days and counting

**Comment by cryptoguyinza** [comment]
lol, might be a while

**Comment by Charlie-Crypto** [comment]
Sheesh, the great cryptoguyinza  =D (thanks for reply)

Im going to try the fix you suggested, how hard is it for someone who is not great using terminal?

**Comment by cryptoguyinza** [comment]
you need basic linux skills.

If you good with that you should be good to go.

wallet-cli is available here, have a look at readme for different commands.
https://github.com/tronprotocol/wallet-cli

Thanks.

**Comment by Charlie-Crypto** [comment]
ill give it a go, thanks again for the fast responses and the workaround!!

Ive held your coin for some time but i will defiantly get a multiple of what i have. I appreciate the help( even if i dont get it)

**Comment by Gitmiyorum** [comment]
Unfreeze seems to work now in Tronscan. ;-)
