### ISSUE TITLE
tronscan wallet balance has been moved/transferred 

### ISSUE THREAD

**Issue by PaoraBoo** [tronscan/tronscan-frontend#1130]
Why has a transfer been moved from my wallet without being notified? Have I been hacked? Happened 23hours ago

![image](https://user-images.githubusercontent.com/33546727/54101891-f4d80f80-4400-11e9-9e37-b01b3545d8fc.png)

**Comment by PaoraBoo** [comment]
This transaction was not completed by me

![image](https://user-images.githubusercontent.com/33546727/54101990-7039c100-4401-11e9-8873-34fa15222827.png)

**Comment by Rovak** [comment]
transactions are unrelated to the tronscan frontend project, most likely your private key got leaked and these transactions cannot be reversed

**Comment by PaoraBoo** [comment]
So how can I get these coins back? So tronscan is not safe?

On 11 Mar. 2019 1:45 pm, Roy van Kaathoven <notifications@github.com> wrote:

transactions are unrelated to the tronscan frontend project, most likely your private key got leaked and these transactions cannot be reversed

**Comment by Rovak** [comment]
There are a lot of scam tronscan versions being advertised using google adwords, you might have input your private key in the wrong website

**Comment by PaoraBoo** [comment]
I haven't opened tronscan for few month's. I check the balance via tron network because tron scan app is so slow.

On 11 Mar. 2019 2:42 pm, Roy van Kaathoven <notifications@github.com> wrote:

There are a lot of scam tronscan versions being advertised using google adwords, you might have input your private key in the wrong website

**Comment by PaoraBoo** [comment]
So why does the account no longer exists? I cannot get into the acc at all. How was my private key to be non-existent. The acc should still be able to open. Therefore the scam closed my acc too?

On 11 Mar. 2019 2:56 pm, Kura Smiler <ksmiler@live.com.au> wrote:
I haven't opened tronscan for few month's. I check the balance via tron network because tron scan app is so slow.

On 11 Mar. 2019 2:42 pm, Roy van Kaathoven <notifications@github.com> wrote:

There are a lot of scam tronscan versions being advertised using google adwords, you might have input your private key in the wrong website
