### ISSUE TITLE
How can I access my tron coins?

### ISSUE THREAD

**Issue by Sausalitoj** [tronscan/tronscan-frontend#1133]
I can't open my Transcan wallet. How can I access my coins and transfer my TRON coins from my 
Transcan wallet to the new web TRON Wallet?

**Comment by Rovak** [comment]
You can use your private key, keystore or ledger on tronscan.org

**Comment by Sausalitoj** [comment]
Thank you 😊 

Sent from my iPhone

On Mar 13, 2019, at 7:23 AM, Roy van Kaathoven <notifications@github.com> wrote:

You can use your private key, keystore or ledger on tronscan.org
