### ISSUE TITLE
Unfreeze for rented trx

### ISSUE THREAD

**Issue by dave2702** [tronscan/tronscan-frontend#1135]
having frozen TRX for another wallet using the bandwidth share feature, when it comes to unfreezing there is no option to unfreeze the rented TRX, the TP shows the correct amount and if you freeze more TRX for you own wallet the TP increases but only shows your own frozen TRX

**Comment by Gitmiyorum** [comment]
Same problem here. Using a play account and a freeze account for remote freezing using a Ledger. Locally frozen assets unfreeze perfectly. Remote frozen assets just can't be unfrozen.

![image](https://user-images.githubusercontent.com/48581887/54416080-9b245d80-46fe-11e9-92b4-6446629291c9.png)

**Comment by Rovak** [comment]
can be unfrozen using wallet-cli, a fix for tronscan will follow later

**Comment by Gitmiyorum** [comment]
Is there any instruction how to do this easily? Will this also work for Ledger?

**Comment by Charlie-Crypto** [comment]
I dont hear to many people talking about this major bug. I hope there is a fix for the non tech person soon.

**Comment by afmsavage** [comment]
Any help on how to do this with the wallet-cli @Rovak ?

**Comment by gdoneit** [comment]
I have exactly the same problem. What is the ETA to fix this as essentially my TRX are held hostage to this bug. Thanks

**Comment by tomkay1985** [comment]
Nobody cares about the problems here... project seems dead or what?!

**Comment by myfocus** [comment]
Unfreeze for rented TRX has been updated
