### ISSUE TITLE
Cannot Freeze TRX

### ISSUE THREAD

**Issue by sspyue** [tronscan/tronscan-frontend#1138]
I am using Tronlink Chrome extension and cannot freeze TRX even though Tronscan saids it was successfully frozen.  There is no transaction record of TRX being frozen.  Reading similar issues in this Github points to a problem with the Google browser and suggestion was to use Opera.  Do you mean downloading the Chrome extension in Opera?  I tried that and I still can't freeze TRX.  I also tried the online tronscan wallet and cannot freeze TRX there either?  What is happening?

**Comment by UnBuenCamino** [comment]
Win10Pro, Tronscan.org, Ledger Nano S. I can't freeze or vote.  Very frustrating, been this way for months. I freeze, get success message, but nothing is frozen.  Same with vote, I vote, here, I generally get an error, and can never vote.  I have no confidence whatsoever in Tron.

**Comment by Makazar** [comment]
Using Tronscan.org I cannot Freeze or Unfreeze TRX. I too get the message "success" but nothing gets frozen. Looks like this has been going on for some time. Can anyone assist?

**Comment by ry4n5** [comment]
Same issue on OSX using Chrome with TronLink extension.

**Comment by sspyue** [comment]
> > I am using Tronlink Chrome extension and cannot freeze TRX even though Tronscan saids it was successfully frozen. There is no transaction record of TRX being frozen. Reading similar issues in this Github points to a problem with the Google browser and suggestion was to use Opera. Do you mean downloading the Chrome extension in Opera? I tried that and I still can't freeze TRX. I also tried the online tronscan wallet and cannot freeze TRX there either? What is happening?
> 
> Please use the Chrome browser

Ummmm....Google browser is Chrome browser....didn't work.  Resorted to other browsers and didn't work either.

**Comment by sspyue** [comment]
OK.  I finally got it to work by using another computer and Opera browser with Tronlink Chrome extension.  When you freeze, make sure you leave the address field blank, then I clicked max to freeze all my TRX.  Voted with no further issues.

**Comment by iamhydrogen** [comment]
So I am also using Ledger Nano S, Google Chrome, and the tronscan.org web site.  I was having same issue for days and tried to reinstall Tron app on Ledger.  Now I am getting message that the freeze was successful, but being asked to confirm transaction on ledger (seeing tx hash scroll back and forth and then x on left and check on right).  When I try to press the right bar to select confirm, ledger does nothing (i.e. it doesn't freeze but also doesn't confirm the tx).

Instead of giving away Teslas perhaps Tron should spend more time making sure the tech works?

**Comment by Makazar** [comment]
Tronscan is shamefully unreliable and I will not use it again. I have downloaded and installed Tron Ledger and it works a treat! 
Here if you wanna try it: https://www.youtube.com/watch?v=tOqkpotBu7g&feature=youtu.be
