### ISSUE TITLE
Проблемы с кошельком

### ISSUE THREAD

**Issue by Vova201** [tronscan/tronscan-frontend#1139]
Появились проблемы с тронсканоргом, не могут вывести монеты, контакты техподдержки недействительны, никаких адресов для связи более нет. Кто это такие и почему прячутся?

**Comment by myfocus** [comment]
You can join the troncan Telegram or Discard at the bottom of tronscan.org

**Comment by Vova201** [comment]
Developers via Discard answered that they can not do anything.What will have to wait some time.How much time will have to wait, who will pay me interest for waiting?This platform and coin is unreliable.
