### ISSUE TITLE
Is there a way to delete you wallet, if you created an extra by mistake?

### ISSUE THREAD

**Issue by CITYUPTAKE** [tronscan/tronscan-frontend#114]
I have two wallets and would like to delete one. The incorrect one has a name inputed that I would like assigned to the other. Hopefully that made some sense. Thank you for your time

**Comment by Rovak** [comment]
It isn't possible to remove a wallet, but don't worry, the network will be reset in around 2 weeks and then you can create a new wallet and assign the name

**Comment by CITYUPTAKE** [comment]
thank you for response
