### ISSUE TITLE
Ledger Wallet showing no balance

### ISSUE THREAD

**Issue by rishabhkapoor8711** [tronscan/tronscan-frontend#1141]
<img width="1440" alt="Screenshot 2019-04-07 at 11 01 47 PM" src="https://user-images.githubusercontent.com/26839040/55687327-3bca0e00-5989-11e9-8045-13c78e30ffd5.png">
This is my ledger wallet screen shot, It is able to see; that there is a ledger wallet. However, on seeing the balance; there is nothing to see. I had a good amount of Tron. Don't remember the exact amount! Kindly, let me know the problem. Also, how to see my airdrops?

**Comment by rishabhkapoor8711** [comment]
kindly, email me at rishabhkapoor8711@gmail.com for the feedback.

**Comment by Rovak** [comment]
Tronscan desktop is no longer maintained, use https://tronscan.org instead
