### ISSUE TITLE
Tron SR Github Link for Community Info Not Working

### ISSUE THREAD

**Issue by cryptoguyinza** [tronscan/tronscan-frontend#1145]
**Info** 
Tron Super Representative (SR) can link their Tron SR registered address to a github template that has information about their SR and team.
![image](https://user-images.githubusercontent.com/37824699/56468929-48437180-6433-11e9-82dc-13039046f19a.png)

**Error - Bug**
Newly elected Tron SR have expressed that adding this community info is not working for them. 

Existing Tron SR accounts also do not show that the link exists. I suspect it is in the db, but link between website and db not working.

Please correct this so all Tron SR can add detail and inform the community if they would like to.

![image](https://user-images.githubusercontent.com/37824699/56468872-6d83b000-6432-11e9-962b-9f4d434d16df.png)

**Comment by myfocus** [comment]
SR didn't fill in the team information, it is already good now.
