### ISSUE TITLE
tron login with nano

### ISSUE THREAD

**Issue by lombo72wal** [tronscan/tronscan-frontend#1147]
hi i just returned to my tron wallet after some time and my 9k is missing ive signed on to the tronscan and it verified my nano but my account is blank
i dont understand ive never had an issue before
i had this for sometime and put it here as it was to be a safe haven

very upset and confused

Brad can you help

**Comment by Peet911** [comment]
are they back? i have the same problem...

**Comment by lombo72wal** [comment]
peet no there not

**Comment by lombo72wal** [comment]
btw why would you close this  what give you the right
