### ISSUE TITLE
Countdown to next cycle is wrong

### ISSUE THREAD

**Issue by cryptoguyinza** [tronscan/tronscan-frontend#1148]
**Below is details of Bug**

The countdown on the website is incorrect. It is 17:28 CAT, this says in 32 minutes it will be new cycle. That means the website expects the change over to be at 18:00 CAT.

However the change over happens at 20:00 CAT! 

![image](https://user-images.githubusercontent.com/37824699/56851694-273abf00-6912-11e9-807f-5595ccc5e14c.png)

Then on mobile devices the countdown shows incorrectly as seen below.

![image](https://user-images.githubusercontent.com/37824699/56851724-b34ce680-6912-11e9-8f80-671e494a7188.png)

**Comment by myfocus** [comment]
The vote countdown has been fixed, thank you
