### ISSUE TITLE
Question about config.conf

### ISSUE THREAD

**Issue by CITYUPTAKE** [tronscan/tronscan-frontend#115]
I copied pasted some info below. Is it still necessary to enter this info in to get produced blocks under your candidate name. I'm confused about some saying don't touch it, only touch if your in 27, and finally enter it if your trying to get votes
......................................................................................................................................................................................................... 

the important part is the witnesses block where you enter your own information. This ought to make you visible under the blockchain explorer's #/Accounts tab. If you configure this without also configuring the "LocalWitness" block it will throw an error, so they pretty much go hand in hand. Your URL can be a website or a twitter account, etc.

witnesses = [
{
address: theaddressthatyougotfromtronscan
url = "http://EXAMPLE.COM",
voteCount = 104
},
...
]

Above all, the one thing you need to do is enter your private key in the localwitness block

localwitness = [
ABCDEF1234567890ABCDEF1234567890ABCDEF1234567890ABCDEF1234567890
]

**Comment by Rovak** [comment]
This can be reported in the https://github.com/tronprotocol/java-tron project
