### ISSUE TITLE
Navigate to TRC20 token from search is not working

### ISSUE THREAD

**Issue by ibnzUK** [tronscan/tronscan-frontend#1150]
I am looking at trc20 token and trying to navigate to a different trc20 token from search. 

When Clicked I get new link with different endpoint, but still the same information 

![image](https://user-images.githubusercontent.com/38762355/57679517-6dd32d80-7623-11e9-8345-24f42f7aaeac.png)

**Comment by myfocus** [comment]
We fixed this issue and will be flashing in the next version.
