### ISSUE TITLE
récupération my Tron 

### ISSUE THREAD

**Issue by louismartinze** [tronscan/tronscan-frontend#1154]
Hello,

I wanted to connect but nothing appears on the wallet.
Can you help me please?

**Comment by Rovak** [comment]
Which wallet are you using?

**Comment by louismartinze** [comment]
hello,

I use this one "Tronscan desktop version v2.0.2"

Sincerly,

Louis-Martin Zé-Talmétier

[image: Capture d’écran 2019-05-14 à 20.58.03.png]

Le jeu. 16 mai 2019 à 05:35, Roy van Kaathoven <notifications@github.com> a
écrit :

**Comment by Rovak** [comment]
Tronscan desktop is no longer maintained, please use your private key or ledger on https://tronscan.org

**Comment by louismartinze** [comment]
when i connect on tronscan
i have nothing to appear like this.



[image: Capture d’écran 2019-05-16 à 12.00.14.png]
[image: Capture d’écran 2019-05-16 à 12.00.53.png]

Le jeu. 16 mai 2019 à 11:04, Roy van Kaathoven <notifications@github.com> a
écrit :

**Comment by louismartinze** [comment]
How I can recup my tronix  from tronscan desktop ?

Le jeu. 16 mai 2019 à 11:04, Roy van Kaathoven <notifications@github.com> a
écrit :
