### ISSUE TITLE
Can't open my wallet

### ISSUE THREAD

**Issue by LiamWeber** [tronscan/tronscan-frontend#1155]
I just tried to open my wallet today, but when i type my private key, i can't click on connect. I don't understand because, I've already openend my wallet multiple times and i've never had this issue.
Thank you for helping me.

**Comment by Rovak** [comment]
Which wallet are you using?

**Comment by LiamWeber** [comment]
@Rovak I created my own wallet on tronscan

**Comment by Rovak** [comment]
Could you verify that the private key is 64 characters long and only contains the characters A to F and numbers 1 to 9

**Comment by LiamWeber** [comment]
@Rovak My private key is 65 characters long, but I am pretty sure I have already logged with this key. And my key is in hexadecimal but contains "0".

**Comment by bbsyaya** [comment]
ok, private key length error ,now close the issue
