### ISSUE TITLE
Sorting of TRC20 token holders is not sorting as expected

### ISSUE THREAD

**Issue by ibnzUK** [tronscan/tronscan-frontend#1158]
Sorting of addresses by balance is not working on trc20 token holders page. 

Below I attached an image of an example of how sorting goes from greater balance and another way round. 

![image](https://user-images.githubusercontent.com/38762355/58244884-71fdfa00-7d4b-11e9-98b4-0b09e5a9ed50.png)

**Comment by myfocus** [comment]
This sorting has been fixed, thank you for your question.
