### ISSUE TITLE
关于tronpay troanlink钱包能提供几个生命周期函数吗?

### ISSUE THREAD

**Issue by Ron233** [tronscan/tronscan-frontend#1168]
能提供几个生命周期钩子吗?顺便写点文档，用户登出 切换账号 修改网络可以有吗？切换账号、修改网络我在源码里找到了，tronlink钱包用户登出，我找不到在哪里，能友好一点吗？让第三方开发者稍微少费点心吗？都是开发者，何苦为难开发者

**Comment by Ron233** [comment]
你们知不知道微软移动系统怎么死的

**Comment by Ron233** [comment]
为什么tronpay登出可以会修改文档注入对象，tronlink不修改注入对象？

**Comment by bbsyaya** [comment]
tronsan不提供注入的函数，tronsan是提供数据查询
tronlink插件有注入函数使用，可以去https://github.com/TronLink/TronLink 关注下
