### ISSUE TITLE
Difficulties opening my wallet using ledger nano s

### ISSUE THREAD

**Issue by Toermalijn** [tronscan/tronscan-frontend#1173]
I'm trying to open my wallet using the ledger nano s. My screen reads 'Geen open portemonnee om te tonen', which translates to 'No open wallet to show'.

I this because I was away from the market for a little while and forgot to swap my ERC20 tokens? If so, is there a fix? If not, what else could be the problem?

**Comment by Rovak** [comment]
Hi, make sure you updated your ledger and your tron app to the latest version

**Comment by Toermalijn** [comment]
Hi Rovak, I've done as you suggested (Ledger nano S firmware 1.5.5 and Tron app version on Ledger nano S 0.1.1) to no avail. What is other steps can I take to regain access to my funds?

**Comment by bbsyaya** [comment]
hi，Tron app on Ledger  had updated， can you try it ？

**Comment by Toermalijn** [comment]
It works! :)

Op ma 14 okt. 2019 om 08:56 schreef mingyg <notifications@github.com>:
