### ISSUE TITLE
When Transfers > More  > Selected and calendar showing , there is no way to hide calendar 

### ISSUE THREAD

**Issue by ibnzUK** [tronscan/tronscan-frontend#1192]
I was looking at transactions by week, month  and more. But when more selected there is no way to hide it or go back apart from refreshing page. 

solution: User expects to click outside of the calendar to hide it or little Exit button would help too. 

![image](https://user-images.githubusercontent.com/48181667/65383948-e6ee3a00-dd13-11e9-8fd5-012390ae069b.png)

**Comment by bbsyaya** [comment]
had fixed it

**Comment by zhaohong** [comment]
@ibnzUK  thanks!
