### ISSUE TITLE
when running 'yarn install' come up with errors

### ISSUE THREAD

**Issue by zk19862018** [tronscan/tronscan-frontend#122]
HI @Rovak 

when running 'yarn install' I come up with errors, do u know how to fix this?
![image](https://user-images.githubusercontent.com/39797046/40972012-ee29675a-68f1-11e8-84c7-1bbf9e9d1f7e.png)

**Comment by Rovak** [comment]
Hi @zk19862018, the `canvas` module requires some additional dependencies, the canvas documentation shows how to install these https://github.com/Automattic/node-canvas#compiling
