### ISSUE TITLE
(Bug) Traduccion en español UPDATE

### ISSUE THREAD

**Issue by NeuroticLeek** [tronscan/tronscan-frontend#126]
He notado que en algunas partes de la pagina cuando es traduccida al español viene con errores como: oraciones separados con un "_" (guion bajo) y en otras partes no se traduce del todo

**Comment by PMD3VSolution** [comment]
it is fixed in #123

**Comment by NeuroticLeek** [comment]
Espero lo resuelvan pronto! Todavia quedan algunos detalles por alli
