### ISSUE TITLE
Send to accountname

### ISSUE THREAD

**Issue by Rovak** [tronscan/tronscan-frontend#127]
Besides sending to an address also allow to send to an account name. If the input is not a valid address then lookup the name in the database and find the corresponding address.

Possible issues:

* What if someone changes his account name to an address?

**Comment by Adsize** [comment]
Address for name is to long

![00009](https://user-images.githubusercontent.com/39515013/41030445-0911e494-6987-11e8-8042-084b9ce37e05.jpg)

**Comment by Rovak** [comment]
@Adsize good one! i didn't considered the length

**Comment by Adsize** [comment]
Filters for address names in general work oddly. That can be like these addresses do not.
TKBEfwZVTTUgZcU3umzxPvz8LaD7WE93qW
TW2SPuhrmKb2v74CGHx1vayCGKMSMZ6fKH

**Comment by Adsize** [comment]
By the way, I have long thought about why the user is constantly shown this information about the zero balance

![000088](https://user-images.githubusercontent.com/39515013/41031717-18325ce4-698a-11e8-83dd-c792b24890bf.jpg)

And if these zero coins will be +100500?

**Comment by Adsize** [comment]
By the way, the above addresses have one Link to Github.
"Input your Github username"
Theoretically an intruder can introduce a stranger Link to Github posing as someone else.
This is reflected in the voting list.
Potentially dangerous.
