### ISSUE TITLE
trx wallet

### ISSUE THREAD

**Issue by Leigh420** [tronscan/tronscan-frontend#129]
Having issues with wallet.
TRX wallet address   TLVjuMwsMWMB4vqwBekTLHv97vfXRsUAe6
Lost all trx
Lost all bandwidth
Lost all Tron power

Have reloaded and made new wallet just now. 
Download 1x TRX test coins 10000 and they are not showing up in my wallet?
Been having this issue for last few weeks.

Never posted prior to this and sorry not more technically minded than showing issue using Firefox.

Not sure if this all helps? Let me know. Thanks.

Other issue when inputting password on new wallet. It shows in green txt STRONGER after I had put in 42 lastpass password phase. Very secure. 
But txt in green saying stronger......That’s how I ended up with 42 password length.
It should be worded STRONG.....

**Comment by Leigh420** [comment]
Plus when i press   { request TRX for testing }  is says 
Error
Limit (1 requests) reached for address TLVjuMwsMWMB4vqwBekTLHv97vfXRsUAe6
But there is no TRX in my account.

Walletr was working fine untill i downloaded beta desktop version and then i have unistalled that and gone back on to website but still no trx in my wallet or power or frozen TRX ???

**Comment by Leigh420** [comment]
Request more TRX for testing one hour later and still showing this.
Error
Already requested 1 times in the last hour

Well past the hour. since last request.

**Comment by Rovak** [comment]
The account which distributes TRX is empty and will be refilled at a later time.
