### ISSUE TITLE
Defualt Operate list for Multi-signature is wrong

### ISSUE THREAD

**Issue by andelf** [tronscan/tronscan-frontend#1302]
UI Path: Account page / Multi-signature / Active access / Operate

The default Operate list has a "Representatives Brokerage Update", which is labeled as id=49.
The current mainnet doesn't support this.

Should uncheck "Representatives Brokerage Update" by default. Or remove from the current mainnet tronscan-frontend.

**Comment by andelf** [comment]
i.e. The default configuration results an AccountPermissionUpdateContract error.

**Comment by renchenchang** [comment]
The current main net has supported UpdateBrokerageContract.

The default configuration of active permission should not contain AccountPermissionUpdateContract

**Comment by andelf** [comment]
I was assuming shasta testnet has the same configuration of mainnet.
If not, will it be fixed on shasta testnet?

**Comment by andelf** [comment]
> POST https://api.shasta.trongrid.io/wallet/accountpermissionupdate

```json
{
  "owner_address": "41......[omitted]",
  "owner": {
    "keys": [
      {
        "address": "41.....[omitted]",
        "weight": 1
      }
    ],
    "threshold": 1,
    "permission_name": "owner",
    "type": 0
  },
  "actives": {
    "operations": "77ff07c0023e0300000000000000000000000000000000000000000000000000",
    "keys": [
      {
        "address": "41....[omitted]",
        "weight": 1
      },
      {
        "address": "41....[omitted]",
        "weight": 1
      }
    ],
    "threshold": 2,
    "id": 2,
    "type": 2,
    "permission_name": "active"
  }
}
```

REPLY:

```json
{"Error":"class org.tron.core.exception.ContractValidateException : 49 isn't a validate ContractType"}
```

**Comment by bbsyaya** [comment]
this api is for test
