### ISSUE TITLE
这个api有测试链调试吗

### ISSUE THREAD

**Issue by yangjianyao** [tronscan/tronscan-frontend#1307]
最近在学习波场离线签名交易，发现要用到这个api里面的广播交易，想问下，有没有测试链可以广播的

**Comment by bbsyaya** [comment]
您说的是冷钱包的离线签名么，您能具体描述下是哪个api的接口么，这样才好定位测试网是否有测试接口？

**Comment by yangjianyao** [comment]
看到一个离线的案例，使用了https://apilist.tronscan.org/api/block/latest 获取最新的block，还有一个https://apilist.tronscan.org/api/broadcast，广播离线签名的数据，这些好像都是主网的，有没有测试链的

**Comment by bbsyaya** [comment]
您好，可以使用nile测试网  https://nile.tronscan.org 或者 shasta 测试网 http://shasta.tronscan.org/ 都可以测试的

**Comment by yangjianyao** [comment]
http://shasta.tronscan.org/ shasta测试 没有我上面说的两个接口吧？改成这样http://shasta.tronscan.org/api/broadcast，测试了不行

**Comment by myfocus** [comment]
shasta测试网：使用 https://api.shasta.tronscan.org/api/block/latest  和 https://api.shasta.tronscan.org/api/broadcast  接口
nile测试网:使用 https://nileapi.tronscan.org/api/block/latest  和 https://nileapi.tronscan.org/api/broadcast  接口

**Comment by yangjianyao** [comment]
谢谢，shasta测试网已经成功了

**Comment by myfocus** [comment]
好的，欢迎加入tron开发者群里，获得更多技术支持
