### ISSUE TITLE
Cant Unfreeze TRX 

### ISSUE THREAD

**Issue by eventkitchens** [tronscan/tronscan-frontend#1320]
I Froze my TRX with an expiration date of Dec 3rd 2019. I went to retrieve them tonight, and I keep getting this message: 

"Unable to unfreeze TRX. This could be caused because the minimal freeze period hasn't been reached yet."

Unless Tronscan has deposited more TRX into my account; therefore, prolonging the expiration date, I'm confused why I can't unfreeze them. I am signing in with Ledger Nano S. 

![Screen Shot 2020-01-08 at 8 26 58 PM](https://user-images.githubusercontent.com/59673639/72029879-56e9e700-3255-11ea-8f22-9cfc64974492.png)

**Comment by bbsyaya** [comment]
can you send your acount address to check it?
