### ISSUE TITLE
Can't get usdt transfers - transactions data  

### ISSUE THREAD

**Issue by Gennttii** [tronscan/tronscan-frontend#1345]
I want to get USDT transactions only but this link doesn't give me anything, how to write the token name for USDT, tried with capital and lowercase letters, gives nothing..:

http://apilist.tronscan.org/api/transfer?sort=-timestamp&token=usdt&address=TEmcaT3xRarqhju1XrbskcV3w3UKz2iBqi

**Comment by myfocus** [comment]
Do you want to get all USDT transfers at the current address?
