### ISSUE TITLE
Set name regex issues

### ISSUE THREAD

**Issue by kookiekrak** [tronscan/tronscan-frontend#135]
Reported by email.

The regex is failing to match leading symbols which shouldn't be allowed.

![screenshot_1](https://user-images.githubusercontent.com/585120/41069647-be84bccc-69a3-11e8-80ef-6acc9211750f.png)
![screenshot_2](https://user-images.githubusercontent.com/585120/41069649-bfa5d686-69a3-11e8-8d29-5742618b4fe4.png)

**Comment by PMD3VSolution** [comment]
already reported #31

**Comment by kookiekrak** [comment]
@PMD3VSolution ah okay, sorry i didnt realize the emails you sent in were already opened as issues!
