### ISSUE TITLE
[Bounty] Displaying "Error 404" or idea on a million (mini presentation)

### ISSUE THREAD

**Issue by Adsize** [tronscan/tronscan-frontend#138]
Today, on a fine summer day, I discovered grand https://tronscan.org/#/ 
and replaced in the browser string characters "#/" by "0"
Refusing to understand and recalling the far 80th years said:
"I do not believe it!" 

![0001112](https://user-images.githubusercontent.com/39515013/41109434-b0b59b0c-6a7f-11e8-854b-6e4f3c60b68a.jpg)

This is the home page of a kitten or second-class son, 
or maybe in the 21st century they do not know:
.htaccess
ErrorDocument 404 /tron-logo.html

Conclusion:

1. On this page the logo
(not original)
2. Logo with musical accompaniment
(more interesting and fresh)
3. Classic and traditional Easter egg
(the continuation of the tradition of "error 404", "viral advertising")
3.1 Minigame
3.2 Coinfaucet
3.3 Coinfaucet in the form of a mini-game!

**Comment by Adsize** [comment]
Or a puzzle?
https://motherboard.vice.com/en_us/article/kzpqzz/heres-the-solution-to-the-3-year-old-dollar50000-bitcoin-puzzle

**Comment by kookiekrak** [comment]
I personally like a We're hiring! page :)
