### ISSUE TITLE
Terminal Output Disabled

### ISSUE THREAD

**Issue by steffensq** [tronscan/tronscan-frontend#141]
Hello,

when running:

./gradlew run -Pwitness

There is minimal output to terminal, I receive only the following:

Starting a Gradle Daemon (subsequent builds will be faster)

> Task :generateProto UP-TO-DATE
Using TaskInputs.file() with something that doesn't resolve to a File object has been deprecated and is scheduled to be removed in Gradle 5.0. Use TaskInputs.files() instead.
<===========--> 85% EXECUTING [38s]
> :run

The node appears to be running correctly as I can probe it successfully through the node tester on Tronscan and also see transactions through the log files in java-tron/logs/tron.log

Is there a way to enable output to the terminal as is seen in most of the setup examples provided in the documentation? Thanks!

**Comment by Rovak** [comment]
Hi @steffensq, recently the logging has changed. Logs are now written to a file which is located at `logs/tron.log`
