### ISSUE TITLE
Populating All Transaction Fields With User's Custom Tags

### ISSUE THREAD

**Issue by prometx** [tronscan/tronscan-frontend#1484]
Would it be possible to insert users' custom tag data in more transaction fields? Currently this can only be seen in the external addresses "Account" screen. It would be great though if these tags could appear in the main "Transaction" screen, The little bell notification dropdown, etc.

In "zealot-mode", I'm just going to say that it should appear *everywhere* an wallet address or transaction field appears, lol. Pretty please...

**Comment by bbsyaya** [comment]
yes can think add this
