### ISSUE TITLE
need some serious help.

### ISSUE THREAD

**Issue by LOUPENN** [tronscan/tronscan-frontend#1486]
hi there, after 2 years i decided to check on all my cryptos.
 Tron which i have a key and seed words, but no wallet to put them in.
i correctly had them on Binance to convert to the new system, but cannot locate them now.
can someone pls suggest a way how to track or locate them.
thanks regards Lou

**Comment by myfocus** [comment]
You can join the telegram group for some help https://t.me/tronscan_org

**Comment by Vanina095** [comment]
От браузъра Влизам с телефонния си номер аз мобилният портфейл съм се регистрирала с имейла и сега не иска да ми ги свърже и двата какво да правя
