### ISSUE TITLE
TOKEN INFORMATION UPDATE TO ADD INFORMATION YOUTUBE,TWITCH AND DLIVE CHANEL LOOK PICTURE

### ISSUE THREAD

**Issue by TRON-FAN** [tronscan/tronscan-frontend#1490]
WE NEED THIS IN TOKEN INFORMATION, THANK YOU

![image](https://user-images.githubusercontent.com/42068552/91579251-a2b7e080-e94b-11ea-8fae-70130d03d754.png)

**Comment by bbsyaya** [comment]
Please fill in the corresponding link
