### ISSUE TITLE
Adding support for TRC10 search by ID

### ISSUE THREAD

**Issue by wojak-frog** [tronscan/tronscan-frontend#1493]
AS  i noticed, TRC10 token search by ID only works for BTT because it's a verified token. Otherwise, if i try to search a TRC10 token by it's ID, tronscan will return a block ID. I would like to suggest to add a new feature which will let the users to search TRC10 tokens by its ID, and if there is BLOCK-TRC10 ID match, maybe a specification for search can be done like T + token id (e.g T1003000)

**Comment by mahdilou99** [comment]
> 
> 
> AS i noticed, TRC10 token search by ID only works for BTT because it's a verified token. Otherwise, if i try to search a TRC10 token by it's ID, tronscan will return a block ID. I would like to suggest to add a new feature which will let the users to search TRC10 tokens by its ID, and if there is BLOCK-TRC10 ID match, maybe a specification for search can be done like T + token id (e.g T1003000)

I have this problem too 
do you find answer for this? 
i can't update token to i have error : Token name contains sensitive words

**Comment by bbsyaya** [comment]
if the token of the keywords with security risks cannot be updated ，you in https://tronscan.org/#/tools/contactUs to feedback
