### ISSUE TITLE
i can't update token information

### ISSUE THREAD

**Issue by mahdilou99** [tronscan/tronscan-frontend#1494]
i wanna add logo to token information page but after fill fields and push Next i have this Error : Token name contains sensitive words

i can't change information , what is problem ?

**Comment by myfocus** [comment]
Maybe the token name hits some special sensitive words, you can change the name or join the Tron community for help

**Comment by tofudefi** [comment]
We have the same issue with TRC10 TOFU10 token: https://tronscan.org/#/token/1003475
We wanted to add new social media links, updated couple of times via tronscan token update interface, but it didn't work.

**Comment by WataMalon** [comment]
same as me.. I tried to update project website many times.. thing doesn't work out!
