### ISSUE TITLE
[Bounty] Tronscan V2 - Tokenbilance - No infodialog

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#15]
bug report
------------

if the balance is empty no note window appears:
![image](https://user-images.githubusercontent.com/39301026/40099107-e6eeaf04-58de-11e8-97c4-051548412820.png)

it should be the same as with the menu item vote:
![image](https://user-images.githubusercontent.com/39301026/40099129-00c05752-58df-11e8-98fa-c37c28a53799.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
18. may 2018 1:30pm (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

**Comment by Rovak** [comment]
Fixed
