### ISSUE TITLE
Tronscan showing "Cannot read property 'message' of undefined" error

### ISSUE THREAD

**Issue by rajacebong** [tronscan/tronscan-frontend#1500]
It works fine for other tokens but when i try to send VidyX token using Ledger Nano, it pops "Cannot read property 'message' of undefined" error.

![Screenshot from 2020-12-27 20-28-37](https://user-images.githubusercontent.com/76032346/103171913-568d9600-4882-11eb-8176-bd69b544a5fb.png)

**Comment by rajacebong** [comment]
additional info: contract signing and unverified contract is enabled in the ledger device

**Comment by myfocus** [comment]
Is VidyX a TRC10 Token？ id = 1003518

**Comment by rajacebong** [comment]
> Is VidyX a TRC10 Token？ id = 1003518

Yes it is! only this particular token gets error, other trc10 works fine

**Comment by bbsyaya** [comment]
had fixed
