### ISSUE TITLE
Cant connect wallet with keystore file anymore?

### ISSUE THREAD

**Issue by kondekaz** [tronscan/tronscan-frontend#1502]
Hi, havent visited tronscan few weeks now. Used to link wallet with keystore file but i cant find this option anymore?
How can I access my TRX now?

Thank you

**Comment by poppytroxell** [comment]
I'm having same problem, I usually go to Import Wallet and put in key. But that option seems to have been removed on last update in Dec. I also had never setup Tronlink to I really have no physical access to my wallet any more. We need help 
I'm sure there are plenty more people out there that will soon find out the same.

**Comment by poppytroxell** [comment]
I'm using the web based tronscan.org. on my PC. Is there another way to get access the wallet.? Is there a tronscan.org app that has access to our wallet that can be downloaded on Android. Same problem happens on Android chrome, brave, firefox.
Do we need to find another wallet and you can send our crypto there? Please Tell me what to do!!!!!!!!!!!!

**Comment by cryofix** [comment]
I just found out today I cannot login via wallet import. Tronlink is not working for me to login, I can not import my keystore into tronlink.

Does anyone know what format was used to create the keystore? is it an encoded keystore? 

I have 0 access to my account right now and it is VERY concerning.

**Comment by kondekaz** [comment]
Install tronlink.org Tronlink  addon to your browser and open it.
It will ask you to create a new password and choose name for your account
After that, you have an option to restore existing wallet (there's also an option for keystore file)
Upload your file, enter your file password and you should get in successfully.
After that, go to tronscan.org , click on Connect Wallet and choose Tronlink- it will log you in automatically and everything should look as it did before.

**Comment by poppytroxell** [comment]
WHOHOOOOO! Just DID IT!!!!!!
WORKS GREAT. EVERYTHING IS THERE>
See i knew we would figure it out, was just a matter of time.
Just make sure you LOG OUT good!!!!!

Also
LOOKED around a bit.
to find the private key in tronlink, go to the 3 lines on right hand side.
Go down to export Account, type in password.
there will be options for QRS, Private Key  and Key restore.

Of course i just found to Youtub videos i was just going over.

https://www.youtube.com/watch?v=_2_oEpg7Slw
[https://www.bing.com/th?id=OVP.0LVumAtxAhlI5H3S7zeQrwHgFo&pid=Api]<https://www.youtube.com/watch?v=_2_oEpg7Slw>
How To Import Any Tron (TRX) Wallet to TronLink Extension<https://www.youtube.com/watch?v=_2_oEpg7Slw>
How To Import Any Tron (TRX) Wallet to TronLink Extension TronLink Wallet: https://www.tronlink.org (Link TRON Ecosystem) Part 1: How to install and setup TronLink Wallet Extension Previous video: https://youtu.be/8sH233-2U7Q In this tutorial video I teach how you can import any Tron (TRX) wallet into your TronLink extension on desktop. Please ...
www.youtube.com

https://www.youtube.com/watch?v=b-zK8CHhvRc
[https://www.bing.com/th?id=OVP.j0sVWuDHyyhwFGdsH6QxGAHgFo&pid=Api]<https://www.youtube.com/watch?v=b-zK8CHhvRc>
Tron Link Wallet - Chrome Extension How To<https://www.youtube.com/watch?v=b-zK8CHhvRc>
www.tronlink.org
www.youtube.com



im just going to leave ticket open for now in case anybody needs it

Take It Easy

Paul




Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by poppytroxell** [comment]
I'm just replying to everybody that has emailed me. If we already communicated please disregard.  Thanks!!!!WHOHOOOOO! Just DID IT!!!!!!Downloaded and installed TronLink. Created new account.Had option where I was able to imported/restored wallet using my private key.WORKS GREAT. EVERYTHING IS THERE> TronAlso connect automatically to Tronscan.org, with almost same vintage view.When using PC.AlsoLOOKED around a bit.to find the private key in tronlink, go to the 3 lines on right hand side.Go down to export Account, type in password.there will be options for QRS, Private Key and Key restore.Of course i just found two Youtub videos i was just going over.https://www.youtube.com/watch?v=_2_oEpg7SlwThanks for the no help tronscan and GITHub helpOn Jan 31, 2021 12:09 AM, cryofix <notifications@github.com> wrote:
I just found out today I cannot login via wallet import. Tronlink is not working for me to login, I can not import my keystore into tronlink.
Does anyone know what format was used to create the keystore? is it an encoded keystore?
I have 0 access to my account right now and it is VERY concerning.

**Comment by bbsyaya** [comment]
Please use tronlink to import the private key
