### ISSUE TITLE
Tronscan Web Wallet

### ISSUE THREAD

**Issue by poppytroxell** [tronscan/tronscan-frontend#1504]
Is anyone else having issues with tronscan.org web wallet?  How do you get in now without the Import Wallet Link? Does anyone know if it is coming back? I have no access to my Crypto. Help!!!!??

**Comment by poppytroxell** [comment]
Can someone please guide me to the group that deal with the tronscan web wallet?

**Comment by poppytroxell** [comment]
Who runs tronscan web wallet?

**Comment by poppytroxell** [comment]
Come on guys, at least acknowledge that my ticket is even here. It's been seven days.i know your busy but at least say your looking into!!!!!

**Comment by kondekaz** [comment]
tronscan support isnt replying either (submitted a ticekt couple of weeks ago now) so something phishy is going on here

**Comment by poppytroxell** [comment]
Thanks for the update? Your right! Something is fishy. I did hear a high ranking official not sure if CEO, CIO,CFO but somebody high from GITHub was arrested. Not sure if related to china corruption.We will figure out. I'm sure we are not the only ones. But somebody out there has to know. As long as we have our security key we at least know when given chance we can get back in. I did some research on tronscan going back on there help site, there was an announcement and it did state they were updating front end Dec 31 and removing\ replacing. But don't understand why they would remove that particular function. Because it even states when you highlight Tronlink, you need to accss web wallet front end to do anything with reps. Plus There was no mass email that went to users, I certainly did not know and I was in on Christmas day. If I find out anything I will let you know.But  will keep updating tickets just out of principal now.On Jan 27, 2021 5:42 AM, kondekaz <notifications@github.com> wrote:
tronscan support isnt replying either (submitted a ticekt couple of weeks ago now) so something phishy is going on here

**Comment by poppytroxell** [comment]
Below is contact info for a major TRON cheerleader, including many other alt coins.
He goes by Crypto Tone, and I've talked to him a year ago about Crypto credit cards and Tron wallets.
I did email him a day ago and waiting for a response. He is busy but will eventually get back to you.
 but if you have a Twitter account you may catch him there or someone else in the chat room
Again see below!!!!


🔥🔥What’s up Telegram! Your boy CryptoTone, comin’ at ya.... with a new telegram room! 

❗️First & foremost, I’d like to thank all of you for the tremendous support 💯! You guys are the reason I keep pushing to put out solid content❗️

🚀 I’m going to be posting links here daily! Feel free to do the same! Just please don’t post scam links! 

🤬 For all the scammers in the YouTube comments..... go fuck yaself! 😎

🙏 Keep it clean & semi-professional! Don’t make me have to get vinny 🇮🇹 up in here! Ha! 🚀🚀

🔥🔥Holla at you boy 🔥🔥 ✌️

🗣 P.S. If you don’t already follow me on social media, here are my links! 

📺 YouTube - http://youtube.com/c/CryptoTone

📣 Twitter - https://twitter.com/Crypto_Tone1

🔈 Direct Telegram - https://t.me/Crypto_Tone1

📧Email -caponeT1212@gmail.com

👁 Looking for merch? You know your boy got you! Here’s my TRX address! THWabhmJ7zjRFzk3Tax1wKXDCeMdM3ZWbY 

🤠 Hit me up on your choice of platform & I’ll talk to u!

**Comment by poppytroxell** [comment]
Got some info off of Telegram,  Tronscan.org has an official site there with Tron link. I have not tried this yet, since it is getting late. But this seems to the cure wether on PC or mobile phone or tablet. Post back if it works for you.

Jonas Kahnwald:
Hai  there is no import wallet option in troncan.org, which i used to login with my private key.how can i login now?

$TRXMan:
You have to import yout Tron wallet to TronLink, therefore you can connect to tronscan via TronLink
Hello! Yes this login feature have been removed. So you have to import your wallet to TronLink, then connect to tronscan using tronlink

**Comment by poppytroxell** [comment]
Make sure you download TRONLINK  extension from TRONLINK.ORG
All others are scams

**Comment by kondekaz** [comment]
Good to know, did you manage to access your trx?

**Comment by poppytroxell** [comment]
Not yet, I'm still trying to figure out. I created a new Tronlink account, since I never linked it directly when I had access to tronscan.org web wallet. Created login with new password for it. Confirmed and copied 12 word restore security key for Tronlink itself. Up to this point there was no place to put in our security key, or original restore key. So there has to be a place , section once logged in to be able to restore import key. I just have to find it.Just wanted to note that on Telegram, tronscan.org group people are seemingly having issues with Tronlink sending , receiving and actually being hacked from and loosing crypto because supposedly it doesn't log out all the time or there is no lockdown on it since the update and removal of import Wallet function? Or using the fake tronlink install? Plus there are some free tokens that are actually scams or hacks to steel tokens. So as long as you dont try to sell, swap, or even send into oblivion and just left alone in wallet the will not affect you. That I just found so not sure if can be deleted out of wallet. Suppose to fix at some point? Working on it? I'm in two thoughts of triggering it now untill  I can find another wallet or until they fix it. I will at least let you know when I find the restore secton.Hang in there?On Feb 4, 2021 3:19 PM, kondekaz <notifications@github.com> wrote:
Good to know, did you manage to access your trx?

**Comment by kondekaz** [comment]
Ok, managed to get access to mine and transfer all TRX to another place.
If you install Tronlink addon, it will ask you to choose new password for your new wallet. When thats done, you get an option to restore existing wallet and behold, there is also the  keystore file option. Upload your file, enter the password and it should log you in fine. If you enter tronscan website after that and click Connect Wallet and choose TronLink, it will automatically log you in and everything looks as it did before :)
Since I dont trust this site anymore, I transfered all my TRX.
Thanks and good luck!

**Comment by poppytroxell** [comment]
WHOHOOOOO! Just DID IT!!!!!!
Added TronLink Extension to chrome, created account, then restored/ imported old wallet using private key.
WORKS GREAT. EVERYTHING IS THERE> all my Tron
See i knew we would figure it out, was just a matter of time.
Just make sure you LOG OUT good!!!!!

Also
LOOKED around a bit.
to find the private key in tronlink, go to the 3 lines on right hand side.
Go down to export Account, type in password.
there will be options for QRS, Private Key  and Key restore.

Of course i just found to Youtub videos i was just going over.

https://www.youtube.com/watch?v=_2_oEpg7Slw

**Comment by bbsyaya** [comment]
Please use tronlink to import the private key
