### ISSUE TITLE
Awful user experience for TRX freeze in Russian  language

### ISSUE THREAD

**Issue by travek** [tronscan/tronscan-frontend#1507]
Hello team!

I just pass made few steps to freeze some TRX to vote further for SR. I can say that it takes me around 5-7 minutes to understand what I need to submin. I use tronscan interface for this. 

I'm reaching Tronscan resource from RU zone, it seems that resource understand that I'm comming from Ru zone and translate everything into Russian.The translation is absolutely bad and not transparent.

Well, to freeze some TRX I need to submin a button "Получать" on the tab "Ресурсы". The button "Получать" is not visible and is located on the right side, far from "Ресурсы" word. Guys, this is very, very bad!!! And not understandable! You need to rework inteface and make it simple and easy to use with proper wording. For instance, if I want to freeze some TRX than you need to have a big button "Freeze TRX" and it is better not to translate this at all - on all resources it is written that if I want to vote than I need to FREEZE TRX at first. If you really want to translate, than make it in a good way. The proper wording should be - "Заморозить TRX"!!

Guys,
you are making a resource for managing one of the biggest cryptos! Try to make interface wor working with TRX correct and easy to use. Currect UX is awful!

If you want I can consult what correct wording to use for Russian interface and I can make it for u for free. 
I really want to have Tronscan interface to manage TRX simple and clean!

**Comment by bbsyaya** [comment]
Thank you for your suggestion, we will consider modifying it.
