### ISSUE TITLE
Multi Signature

### ISSUE THREAD

**Issue by CyKloneZ** [tronscan/tronscan-frontend#1513]
I have another wallet on my TRON account but-it's a long story-I can't recreate it so my primary account is unable to transact as it needs the other signature.Can I modify permissions (Tron) and remove the other account? t's been driving me NUTS-LOL There must be a way -I'm the primary account holder. All help would be VERY gratefully received.

**Comment by bbsyaya** [comment]
you can try use tronlink app to change the account Access

**Comment by CyKloneZ** [comment]
Thanks:)

**Comment by CyKloneZ** [comment]
I have tried to amend permissions and delete the second wallet but the sytatus quo remains the same. Whatever I do it seems I can't transact on my wallet without the signature of the now non-existent second wallet. This is driving me nuts-literally. There MUST be a way for the wallet owner to amemd co- signatories effectively?

**Comment by CyKloneZ** [comment]
I REALLY would appreciate and I'm happy to pay to get this resolved- I need an experienced Tron developer. There has to be a way- I PRAY there is

**Comment by freeinnotech** [comment]
How do you want it developed.?

**Comment by CyKloneZ** [comment]
We’d need to discuss- how can I reach you?

😊

**Comment by freeinnotech** [comment]
What's your number?

***@***.***

**Comment by CyKloneZ** [comment]
I’m in the UK- +44 754098 3938

**Comment by freeinnotech** [comment]
I am in NIGERIA Here is my Mobile / Whatsapp +2348167013743
