### ISSUE TITLE
Cannot record token to Poloni DEX via Tronscan

### ISSUE THREAD

**Issue by puftoken** [tronscan/tronscan-frontend#1518]
Hello,

I am trying to record my newly created token to Poloni DEX via Tronscan address at: https://tronscan.io/#/wallet/tokensCreate

I am filling in my data and after I sign the transaction I receive the following errors: 

`Access to XMLHttpRequest at 'https://platform.tron.network/api/token/addBasicInfo' from origin 'https://tronscan.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

and also

`POST https://platform.tron.network/api/token/addBasicInfo net::ERR_FAILED`

`Uncaught (in promise) TypeError: Cannot read property 'msg' of undefined
    at TokensCreate.cb035657.chunk.js:1
    at l (92.3c26764b.chunk.js:1)
    at Generator.n._invoke (92.3c26764b.chunk.js:1)
    at Generator.next (92.3c26764b.chunk.js:1)
    at r (92.3c26764b.chunk.js:1)
    at s (92.3c26764b.chunk.js:1)`

How can I overcome this issue and how to move past this point ?

I am using Google Chrome v90.0.4430.212 (Official Build) (64-bit) (cohort: Stable)

Thank you,
Cristian Badea

**Comment by bbsyaya** [comment]
this https://platform.tron.network/api/token/addBasicInfo has ok

**Comment by puftoken** [comment]
> this https://platform.tron.network/api/token/addBasicInfo had ok now

I get a 404 Not Found when trying to access it. Weird.

**Comment by puftoken** [comment]
I managed to do it after trying several times, seems like the issue is intermittent.
