### ISSUE TITLE
Witness team information unable to update using tronscan.org

### ISSUE THREAD

**Issue by chainchopper** [tronscan/tronscan-frontend#1521]
When adding the team information url for github to the super representative, we get 404 errors. It appears that the url including protocol is added to the github link creating the following: https://raw.githubusercontent.com/https:/github.com/chainchopper/tronsr-template/master/SERVER_CONFIGURATION.md

Instead of: https://github.com/chainchopper/tronsr-template/blob/master/SERVER_CONFIGURATION.md

I noticed that this isnt happening with some SR accounts but for some reason it is impossible to update this unless i am inputting the url incorrectly. 

![image](https://user-images.githubusercontent.com/36168576/123141697-a8286f00-d426-11eb-9df9-f024ecaa7114.png)

**Comment by InferoCrypto** [comment]
i have the same problem. i did notice that it's not allowed to use capitals. maybe give that a try?

**Comment by chainchopper** [comment]
Well of course I only enter the base link as required. Tronscan generates the individual links from that as this is the format of their tronsr_template and the files do indeed have capital letters. However, check out the screenshot. That's not the problem :) the problem is the extra https:// protocol that is added. It appears tron tries to (correctly so) regenerate the urls using raw.githubusercontent.com  however it should not be appending the extra protocol as required to be entered before submission to tronscan. You cant have both :P Either do not require the protocol to be entered (http:// or https:// must be entered along with your github team information link for submission to even work) as a temporary work around, or remove the protocol and domain completely after it is submitted since it will be rewritten to raw.githubusercontent.com anyways. Not sure if tronscan is doing any bounties or anything for these types of bugs, but as a new SR, its very disappointing to have your project held back in this very competitive space due to not being able to add legitimately your team information. Not to mentioned it costs 9999 tron to become SR. So this has been in our way for weeks without any real solution :(

**Comment by bbsyaya** [comment]
maybe your update github error
