### ISSUE TITLE
TRX transaction stuck pending. Also it is not in the list of transactions in the block

### ISSUE THREAD

**Issue by IgorAbramov** [tronscan/tronscan-frontend#1523]
Hello! 
Can you please explain why this transaction got stuck?: https://tronscan.org/#/transaction/82bce5916e329fe6ade58507bbee0f93823561bc7287ba6edfc27f5473656b9b

It is shown that this transaction belongs to block: https://tronscan.org/#/block/31569972
But it is not it the block's transactions list. 

We are sending a lot of transactions each day and this is something very unusual.

**Comment by bbsyaya** [comment]
this transaction  had ROLLED BACK
