### ISSUE TITLE
Multi Signatory Dilemma

### ISSUE THREAD

**Issue by CyKloneZ** [tronscan/tronscan-frontend#1525]
I've asked this in a previous thread but I thought I'd try again. It's a royal stuffup!! 
I can't recreate the wallet for the second signatory and I'm completely stuck with a healthy account that can't transact.

Is there ANYBODY out there that can assist- naturally this would attract a handsome fee!!

**Comment by freeinnotech** [comment]
Yes I can , reply back here.!

**Comment by freeinnotech** [comment]
Anytime!

**Comment by CyKloneZ** [comment]
Where are you based?

**Comment by CyKloneZ** [comment]
Are you available now?

**Comment by freeinnotech** [comment]
I am Based in Nigera

**Comment by CyKloneZ** [comment]
Missed you today- can we hook up tomorrow?

**Comment by freeinnotech** [comment]
I am not available today.

**Comment by bbsyaya** [comment]
Multi-signature account permissions are managed jointly, no need to trust others to operate your account
