### ISSUE TITLE
Surely there has to be a way...?

### ISSUE THREAD

**Issue by CyKloneZ** [tronscan/tronscan-frontend#1527]
I've posed two threads on this but not getting anywhere. 

I've lost the cosignaory on a multi-sig account.- Long story. 

Is there anyway AT ALL I can have this account removed from my wallet?

If it involves coding then I'm sure we have some TRONGURUS out there that could assist!

A very handsome fee awaits the person who can resolve this for me:-)

**Comment by freeinnotech** [comment]
👍

**Comment by bbsyaya** [comment]
Multi-signature account permissions are managed jointly, no need to trust others to operate your account
