### ISSUE TITLE
Activation failed

### ISSUE THREAD

**Issue by WoonchanCho** [tronscan/tronscan-frontend#1534]
When I sign up after filling in form (email and passwords), activation email is sent to the email I filled in the form.
When I click the link in the email to activate the account, I get error message saying that "Activation link has expired, please re-register"

**Comment by bbsyaya** [comment]
Can you send me your email address?

**Comment by fahispm22** [comment]
fahispm22@gmail.com my mail is not active tron

**Comment by pashcal** [comment]
Hi! I have the similar issue after registration and can't write you in the Contact Us form, because it needs Log In. Email: pashcal09@gmail.com

**Comment by jacostax** [comment]
I have sme issue. My e-mail is tuncay.yildirim@gmail.com
