### ISSUE TITLE
[Bounty] Tron Scan 2 Microsoft David

### ISSUE THREAD

**Issue by troolbox** [tronscan/tronscan-frontend#154]
ISSUE: At the end, the balance is read as Zero Million Dollars instead of Zero Dollars or Zero Tron.

![microsoft david](https://user-images.githubusercontent.com/36255140/41187846-f6b78870-6b67-11e8-87fc-e9425977a46b.png)

**Comment by Rovak** [comment]
could you make a screenshot of the "zero million dollars"?
