### ISSUE TITLE
TRONLINK TRONSCAN Multiple signature problems

### ISSUE THREAD

**Issue by hoitmiki** [tronscan/tronscan-frontend#1553]
Tron Link Tron Scan The address of one of the two addresses is not signed, so I can't do anything. 

Is there anyone who can help me?

I'll pay the commission
<img width="841" alt="스크린샷 2022-03-31 오후 8 12 27" src="https://user-images.githubusercontent.com/103718725/163518039-af09c10c-11fc-4c97-b934-362e7af261bb.png">
.

**Comment by bbsyaya** [comment]
only other address to sign the transaction，Don't trust others to sign for you
