### ISSUE TITLE
Transactions list without note

### ISSUE THREAD

**Issue by apetrichkovich** [tronscan/tronscan-frontend#1554]
Hello.
**Steps to reproduce:**
Execute `curl "https://apilist.tronscan.org/api/transaction?sort=-timestamp&count=true&limit=20&start=0&address=TWA1ZjV7LhXdh2w2SsnYVpoLq92jLsFP25"`
**Expexted result:** `"data":"n5"`, `"data":"c4"` and `"data":"i3"` for 3 transactions.
**Actual result:** `"data":""` for all transactions.

**Comment by bbsyaya** [comment]
Thank you for your suggestion, we will take it into consideration.
