### ISSUE TITLE
Proxy Contract Not Showing Options

### ISSUE THREAD

**Issue by taaha827** [tronscan/tronscan-frontend#1556]
Hello Guys, I was implementing Transparent Proxy Pattern in a smart contract,  i developed ,tested and compiled the code and deployed to shasta test network, but when I verified the contract, The tronscan website is not showing me Write as proxy and read as proxy option. Is there a way to do so or if any of you guys can help me identify the issue.

**Comment by bbsyaya** [comment]
Can you send me the address of your proxy contract?

**Comment by taaha827** [comment]
You can go ahead on close this issue, I was able to see those options, there was a mistake in my smart contract where it was not implementing the right Interface that would have allowed tronscan to identify the contract as a proxy contract. 
I was able to fix the issue.
