### ISSUE TITLE
Need my usdt withdrawal from tronscan

### ISSUE THREAD

**Issue by StcurrencyG** [tronscan/tronscan-frontend#1559]
Please I need help
,I want to withdraw my usdt out from tronscan back to facuet pay wallet. Please

**Comment by Sokrat3480** [comment]
TALW6ugFU851t43aY2ksCvUxpxYmdn7m7t

**Comment by Varshans2** [comment]
swap in [**one inch** wallet] or sushiswap

**Comment by StcurrencyG** [comment]
Now is not showing up in the balance in tronscan. Please I am so worried. The transaction is. Not easy for me to access

**Comment by bbsyaya** [comment]
what mistake ? if you send usdt to one address, will not pay back
