### ISSUE TITLE
Testnet

### ISSUE THREAD

**Issue by ironbeeper** [tronscan/tronscan-frontend#156]
You have some bugs here when I request 10000 TRX...
![a](https://user-images.githubusercontent.com/17235949/41188701-e14d3d18-6bc1-11e8-93c9-8eda5926064e.PNG)
![b](https://user-images.githubusercontent.com/17235949/41188702-e16a21a8-6bc1-11e8-8016-6b863d62d193.PNG)

**Comment by Rovak** [comment]
Fixed
