### ISSUE TITLE
How do i make an automatic transfer from my transparent account to shielded account

### ISSUE THREAD

**Issue by Oses0123** [tronscan/tronscan-frontend#1563]

**Comment by 01SMD** [comment]
Try zkwrapper.io

**Comment by Oses0123** [comment]
Should that be a website

**Comment by 01SMD** [comment]
It is. I found it thru tronlink wallet,a dapp. Only thing I've found so far
and honestly I haven't tried it myself yet.

**Comment by 01SMD** [comment]
Go thru your browser to get there

**Comment by Oses0123** [comment]
Okay,do you use facebook.we could share more knowledge
