### ISSUE TITLE
The page hovers

### ISSUE THREAD

**Issue by papamich** [tronscan/tronscan-frontend#160]
When buying tokens, bought TronCash, after confirming the transaction, the page stops on the spot, and is not updated or goes to the purse. It helps to update.Screenshot of the page attached This error found.
![test_tron](https://user-images.githubusercontent.com/36569153/41191677-a9fac030-6bfb-11e8-82f6-94c3afe699f9.PNG)

**Comment by Rovak** [comment]
This could be cache problem, could you try to refresh the page and try again?

**Comment by papamich** [comment]
Tokens are credited, everything is in order.
After updating the cache everything is fine. I did not bother yet. The third time the error was repeated.
And bought gold, also hangs up as in the picture.

**Comment by papamich** [comment]
If there is still a mistake, I'll write to you.

**Comment by papamich** [comment]
Good afternoon.
The tokens that were given out for testing the wallet, they will remain on the account, after the transition?

**Comment by papamich** [comment]
Here's another similar problem when creating a token.
When I started to enter the name of the token, I dropped this screen, I apply the screen. Cache was cleaning.
![create](https://user-images.githubusercontent.com/36569153/41214552-a70e58c8-6d54-11e8-8155-1cadf12b25ab.PNG)

**Comment by Rovak** [comment]
Fixed
