### ISSUE TITLE
tronscan.org - wallet -transaction-incorrect digit

### ISSUE THREAD

**Issue by Leigh420** [tronscan/tronscan-frontend#163]
address TLVjuMwsMWMB4vqwBekTLHv97vfXRsUAe6

click _ wallet
click _  transactions
incorrect amount showing in wallet tab

![trx wallet transaction](https://user-images.githubusercontent.com/35752054/41192671-4ff0afe8-6bf9-11e8-81e7-be92c0f40a6b.JPG)

**Comment by zk19862018** [comment]
repeated issue
