### ISSUE TITLE
(BUG) Negative bandwidth

### ISSUE THREAD

**Issue by markfrez** [tronscan/tronscan-frontend#167]
By unfreezing the tron ​​power in my account and sending the TRX coins to Flyred.Tron the bandwidth has remained in negative (see capture) when it should stay at 0
![screenshot_2018-06-10-00-40-01](https://user-images.githubusercontent.com/39841827/41196701-ab426d16-6c47-11e8-8659-71c0cb052f86.png)

**Comment by Yntelligence** [comment]
I had my trx frozen for 2 months or so, I unfreezed them 2 days ago and wanted to withdraw them but my bandwidth is negative. Yesterday it raised slowly to +2 bandwidth, I went to sleep and today it's again -291. I didn't do any transactions to this time, I just don't get it, I lost the faith in this wallet...

**Comment by Yntelligence** [comment]
And it just stays at -291
