### ISSUE TITLE
Include TRX in the hardware wallet

### ISSUE THREAD

**Issue by markfrez** [tronscan/tronscan-frontend#168]
Include the new TRX currency in the software of the main hardware wallets. IT IS NECESSARY FOR USERS. It will also give good reputation.
![hardware-wallet](https://user-images.githubusercontent.com/39841827/41196862-5e3d7de0-6c4b-11e8-9a86-d67d8b513035.jpg)
![ledger-ethereum_large](https://user-images.githubusercontent.com/39841827/41196864-63ce4c44-6c4b-11e8-8418-cf12d9cab273.jpg)

**Comment by markfrez** [comment]
Top seller of Hardware wallet is Ledger Nano

**Comment by Rovak** [comment]
TRX for ledger is in active development. 

![img_20180606_182902](https://user-images.githubusercontent.com/376155/41196971-7a3e822a-6c4e-11e8-9a0d-1598f83543a6.jpg)

**Comment by markfrez** [comment]
But it is the TOKEN, are you going to include the new currency?

**Comment by Rovak** [comment]
This is the new currency that is being added to ledger
