### ISSUE TITLE
(Bug) Button PREVIOUS / NEXT PAGE

### ISSUE THREAD

**Issue by markfrez** [tronscan/tronscan-frontend#169]
![screenshot-2018-6-9 2tronscan](https://user-images.githubusercontent.com/39841827/41196933-71d7433e-6c4d-11e8-8c21-ce6fc7d842de.png)
![screenshot-2018-6-9 tronscan](https://user-images.githubusercontent.com/39841827/41196934-71f1a2e2-6c4d-11e8-9e21-889183b4539d.png)

**Comment by Adsize** [comment]
This is a bug duplicate number 2
The first description:
https://github.com/tronscan/tronscan-frontend/issues/128#issuecomment-395961830
Second Description:
https://github.com/tronscan/tronscan-frontend/issues/161#issue-330888909

**Comment by markfrez** [comment]
#128 (comment) 
Your ticket is closed because it is solved and the bug keeps appearing now. It is not binding
