### ISSUE TITLE
[FRQ][Bounty] Tronscan V2 - the use of multi-server certificates is questionable from a security point of view -> pornographic content - ethical problem

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#17]
Feature Request / Bug Report
----------

for TLS verification of the tronscan website a multiserver certificate is used (multiple SAN entries) 
![grafik](https://user-images.githubusercontent.com/39301026/40276373-bfae8dce-5c08-11e8-9d73-17bc744d2d23.png)

That wouldn't be the problem if it were all female sides of the tron community.
additionally,the certificate authority does not make a trustworthy entry

please solve the problem with a professional ca and a shorter runtime of the certificate

the other SAN entries are wildcard entries and partly point to websites with pornographic content:
Example:
DNS-Name=boostertube.com
DNS-Name=boyscasting.org
DNS-Name=booktripeasy.com

This indirectly links the tron network to something it doesn't want to be. ethical problem

list of SAN entries 
-----
DNS-Name=sni64554.cloudflaressl.com
DNS-Name=*.4ji62books.cf
DNS-Name=*.67x8abooks.gq
DNS-Name=*.ajrouses.gq
DNS-Name=*.as-altamoda.com.ar
DNS-Name=*.booktripeasy.com
DNS-Name=*.boostertube.com
DNS-Name=*.boyscasting.org
DNS-Name=*.coin.top
DNS-Name=*.cyclopsci.com
DNS-Name=*.flokia.review
DNS-Name=*.guestblogging.com
DNS-Name=*.gunnisonconstructionandseptic.com
DNS-Name=*.hillfarmfinest.com
DNS-Name=*.hugeast.com
DNS-Name=*.individualeconomics.com
DNS-Name=*.lskz.org
DNS-Name=*.mannanewsonline.com
DNS-Name=*.marroclooks.tk
DNS-Name=*.mayomelz.com
DNS-Name=*.n6fohbooks.ga
DNS-Name=*.onmlm.ru
DNS-Name=*.pollyvendetti20ctqcz.ml
DNS-Name=*.roeckitts.gq
DNS-Name=*.sell-pilbha.ml
DNS-Name=*.sell-szduqh.ga
DNS-Name=*.seriousbloggersonly.com
DNS-Name=*.spbfaberlic.ru
DNS-Name=*.stateoftrondapps.com
DNS-Name=*.sunciztyltds.ga
DNS-Name=*.telemaccos.cf
DNS-Name=*.thisendout.com
DNS-Name=*.tron.network
DNS-Name=*.tronscan.io
DNS-Name=*.tronscan.org
DNS-Name=*.tronstatic.com
DNS-Name=*.zabumba.net
DNS-Name=4ji62books.cf
DNS-Name=67x8abooks.gq
DNS-Name=ajrouses.gq
DNS-Name=as-altamoda.com.ar
DNS-Name=booktripeasy.com
DNS-Name=boostertube.com
DNS-Name=boyscasting.org
DNS-Name=coin.top
DNS-Name=cyclopsci.com
DNS-Name=flokia.review
DNS-Name=guestblogging.com
DNS-Name=gunnisonconstructionandseptic.com
DNS-Name=hillfarmfinest.com
DNS-Name=hugeast.com
DNS-Name=individualeconomics.com
DNS-Name=lskz.org
DNS-Name=mannanewsonline.com
DNS-Name=marroclooks.tk
DNS-Name=mayomelz.com
DNS-Name=n6fohbooks.ga
DNS-Name=onmlm.ru
DNS-Name=pollyvendetti20ctqcz.ml
DNS-Name=roeckitts.gq
DNS-Name=sell-pilbha.ml
DNS-Name=sell-szduqh.ga
DNS-Name=seriousbloggersonly.com
DNS-Name=spbfaberlic.ru
DNS-Name=stateoftrondapps.com
DNS-Name=sunciztyltds.ga
DNS-Name=telemaccos.cf
DNS-Name=thisendout.com
DNS-Name=tron.network
DNS-Name=tronscan.io
DNS-Name=tronscan.org
DNS-Name=tronstatic.com
DNS-Name=zabumba.net

Reward Information
---------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

**Comment by Rovak** [comment]
This is related to cloudflare.

https://support.cloudflare.com/hc/en-us/articles/204144518-SSL-FAQ

Are Cloudflare SSL certificates shared?

Universal SSL certificates are shared across multiple domains that may not be in your account. These are multi-domain SSL certificates. If you want only your domain on a certificate, we recommend the Cloudflare Dedicated SSL service.
