### ISSUE TITLE
I found the bug

### ISSUE THREAD

**Issue by hani2018** [tronscan/tronscan-frontend#171]
Please read the text carefully for a few minutes
To Mr. Justin Sun
I'm Hani Akbari, a software engineer. I found 2 problems at your site and network right now. I wrote it for you. If I find something in the future, I'll send you again. I do not want a $ 10 million prize. Only if these things I say will help you, I'm asking for a little help from you.

More details are available in the pdf file.

[Bug.pdf](https://github.com/tronscan/tronscan-frontend/files/2087443/Bug.pdf)

**Comment by Rovak** [comment]
Hi @hani2018, thanks for the detailed bug report. Unfortunately are bugs found in `tron.network` out of scope from the bug bounty competition (see [Documentation](https://github.com/tronprotocol/Documentation/blob/508b7cb46db93591dd5fb13d3aa320e1a7e93c55/English_Documentation/TRON_BUG-BOUNTY_Program/TRON_BUG-BOUNTY_Program.md#out-of-scope))

After reading your PDF i understand you are interested in funding for your project. The Tron Accelerator (https://tron.network/loan?lng=en) program may provide a loan if you have a working prototype/product that you can present.
