### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by markfrez** [tronscan/tronscan-frontend#172]
Hi, How can I link my node 81.46.218.254 to my wallet or tron ​​account?

**Comment by Rovak** [comment]
See http://wiki.tron.network/en/latest/The_TRON_Network.html#running-a-local-node-and-connecting-to-the-public-testnet for instructions on how to connect your node to your wallet. You will need to provide a keystore or private key when starting your node.

I will be closing this issue as this is unrelated to the tronscan frontend. If you still have trouble connecting your wallet then submit an issue at https://github.com/tronprotocol/java-tron
