### ISSUE TITLE
(Bug) in voting

### ISSUE THREAD

**Issue by markfrez** [tronscan/tronscan-frontend#178]
It is possible to vote more times even though we have a limit of votes
![screenshot-2018-6-10 tronscan 1](https://user-images.githubusercontent.com/39841827/41204370-121c9542-6ce4-11e8-8828-aa5f30add182.png)
![screenshot-2018-6-10 tronscan ki1](https://user-images.githubusercontent.com/39841827/41204371-12345bbe-6ce4-11e8-86a3-454ff6ba8195.png)

**Comment by Rovak** [comment]
working as intended
