### ISSUE TITLE
[Bounty] Tronscan V2 - Blockchain Statistics - negative scale

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#18]
bug report
------------

![grafik](https://user-images.githubusercontent.com/39301026/40276467-410eec2c-5c0b-11e8-8f27-b0e6453b5128.png)

the scale represents a negative value (average block size). a block cannot be smaller than Value 0.

Same problem with the TRX transferrate
![grafik](https://user-images.githubusercontent.com/39301026/40276481-a4e9d93c-5c0b-11e8-868f-37133b1947a4.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
20. may 2018 8:00am (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

**Comment by Rovak** [comment]
Fixed
