### ISSUE TITLE
[Bounty] Tronscan V2 - markets Ranking Huobi Link pointed to an ko-Kr page

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#19]
bug report
------------

if you use the link of the huobi exchange you will be redirected to the chinese website of Huobi. due to the international idea it would be better to refer to the US page

![grafik](https://user-images.githubusercontent.com/39301026/40276520-b16a4308-5c0c-11e8-941a-1788f4b033c8.png)

![grafik](https://user-images.githubusercontent.com/39301026/40276523-cc032720-5c0c-11e8-9ab5-7a6cf61b6822.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
20. may 2018 8:00am (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

**Comment by Rovak** [comment]
The links are provided by coinmarketcap, this is not something tronscan provides.
