### ISSUE TITLE
(Improvement) Support for cold wallet and submission of signed transactions

### ISSUE THREAD

**Issue by FireFly2001** [tronscan/tronscan-frontend#190]
Under ERC20, a number of wallets support cold storage of TRX and provide support for submitting transactions that have been signed on an offline device.

For example, MyEtherWallet can be downloaded as an offline web page, so it can be run on an offline computer. Further, it supports a signed transaction (signed on an offline device) to be submitted on a connected device, thereby never exposing private keys.

All the serious coins including BTC, LTC, XRP and ETH support cold storage and provide wallets with the ability to submit signed transactions.

As we transition to MainNet, I can see a serious shortcoming here. Tronscan does not appear to support this concept at all, and it is a major step backwards for holders of TRX who use cold storage via existing ERC20 wallets.

I don't think the community will take TRX seriously under MainNet until there is support for cold wallets and submission of signed transactions.

Can someone advise if this is on the roadmap?

**Comment by Rovak** [comment]
There is a desktop version of Tronscan which can be downloaded at https://github.com/tronscan/tronscan-desktop/releases, also work on ledger support is being done in the ledger branch. Early demo: https://www.youtube.com/watch?v=RYUiiGw-hHw

**Comment by Huaxan** [comment]
Hi Rovak, is there any news on the ledger support?
