### ISSUE TITLE
[BOUNTY]: tronscan : All pages except the home page doesn't have footer links

### ISSUE THREAD

**Issue by rahulsharmablr** [tronscan/tronscan-frontend#193]
What did you do?
If possible, provide a recipe for reproducing the error.
Navigate to tronsr.org
Navigate to different pages
Verify footer links

What did you expect to see?
Footer links should be displayed.

What did you see instead?
No footer links in other pages.

**Comment by BaCoNL** [comment]
This was on purpose, only the homepage has the full footer
