### ISSUE TITLE
[BOUNTY] TRONSCAN: blockchain statistics page has alignment issues in mobile web app

### ISSUE THREAD

**Issue by rahulsharmablr** [tronscan/tronscan-frontend#194]
What did you do?
If possible, provide a recipe for reproducing the error.
Navigate to Blockchain-> Statistics page from a mobile web app
Verify the alignment of different portlets.

What did you expect to see?
All alignment to be proper.

What did you see instead?
Alignment distorted for multiple portlets.

**Comment by joe-meyer** [comment]
@rahulsharmablr can you provide any more detail? When I visit the statistics page in chrome everything looks OK to me. Can you provide the type of device and/or browser you are using so that this can be replicated and patched?
