### ISSUE TITLE
[Bounty] Tronscan V2 - Token Creation - website without function

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#2]
Bug Report 
--------------
after the custom token is created I get a positive feedback. However, the website will then no longer be usable. 
![image](https://user-images.githubusercontent.com/39301026/40118318-e3b82532-5919-11e8-81b0-6bf8e8bdc0eb.png)

it would be better to get an overview of the created token and have the possibility to create one more custom tokens.

currently you have to change back to another menu and then click again on the button token->Create

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
16. may 2018 3:00pm

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

**Comment by Rovak** [comment]
Fixed in #158

![screenshot from 2018-06-09 13-00-45](https://user-images.githubusercontent.com/376155/41190780-29b3bff0-6be5-11e8-8e75-49be91753b83.png)
