### ISSUE TITLE
[Bounty] Tronscan V2 - Participate - Firefox - incorrect display of icons and customs pics

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#20]
bug report
------------
incorrect display of icons and custom pics
Firefox:
![grafik](https://user-images.githubusercontent.com/39301026/40276533-fff67c6c-5c0c-11e8-8e0c-f383471be1b0.png)

![grafik](https://user-images.githubusercontent.com/39301026/40276537-1f4d7728-5c0d-11e8-8ee6-9e4bd13c4a7e.png)

Google Chrome:
![grafik](https://user-images.githubusercontent.com/39301026/40414402-656a0952-5e78-11e8-9a12-c3222507d419.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
20. may 2018 8:00am (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

**Comment by Rovak** [comment]
I'm unable to reproduce this on chrome or firefox

**Comment by PMD3VSolution** [comment]
Yes, I could only reproduce the problem at the weekend, currently the problem does not exist!  I think we can close the case.

**Comment by PMD3VSolution** [comment]
now i could repoduce the issue on firefox:
![grafik](https://user-images.githubusercontent.com/39301026/40412453-a9cd0036-5e73-11e8-8c1c-c220800d2896.png)
