### ISSUE TITLE
Search, account not found

### ISSUE THREAD

**Issue by fbsobreira** [tronscan/tronscan-frontend#208]
1. What did you do?
Search for account by address

2. What did you expect to see?
Account page if exists 

3. What did you see instead?
Warning! Record not found

![image](https://user-images.githubusercontent.com/8503176/41399357-18bb5ef0-6f88-11e8-8d60-6242832a0ea7.png)

The account is populated
 
![image](https://user-images.githubusercontent.com/8503176/41399395-3188785a-6f88-11e8-8803-84aced3f2ede.png)

**Comment by Rovak** [comment]
fixed
