### ISSUE TITLE
[Bounty] Tronscan V2 - unable to change the account name

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#22]
Bug-Report
---------
it is not possible to change the name via the account

![image](https://user-images.githubusercontent.com/39301026/40280596-437e5a38-5c56-11e8-8755-4e6e6f44c8b2.png)

i enter the new name:
![image](https://user-images.githubusercontent.com/39301026/40280606-8dd4b21c-5c56-11e8-849d-3f96ccc5b7d6.png)

no matter what I enter I always get an errormessage:
![image](https://user-images.githubusercontent.com/39301026/40280619-d13b318e-5c56-11e8-8fb1-64878c0e8a7f.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
20. may 2018 5:00pm(UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

**Comment by PMD3VSolution** [comment]
you need TronPower to change the name? it worked, but only after I've frozen trx?
please adjust the status message!

**Comment by PMD3VSolution** [comment]
![image](https://user-images.githubusercontent.com/39301026/40281277-03c71a6a-5c60-11e8-901f-f9aca39a950a.png)

**Comment by Rovak** [comment]
I agree that there should be a message when there isn't any frozen TRX. I shall add this to every transaction screen

**Comment by PMD3VSolution** [comment]
Perfect, thanks for your update
