### ISSUE TITLE
Tron deposit from Binance

### ISSUE THREAD

**Issue by sorma77** [tronscan/tronscan-frontend#223]
Hello,

I just opened an account and wanted to deposit TRX from Binance but there's a message that I shouldn't use the test address. How can I transfer TRX from Binance to my Tronscan account in order to participate in the election of the super representatives?
Thanks

**Comment by msdos622** [comment]
hello,
"Do not send TRX from your own wallet or exchange to the above account address of testnet!" you need to request TRX for testnet, last option in your wallet TRX:
 "When requesting TRX you will receive 10000 TRX which you can use for testing on the testnet"
but curently this option is not working, I don't know why :-(
Regards

**Comment by sorma77** [comment]
Ok, thank you.
