### ISSUE TITLE
Question/Recommendation 

### ISSUE THREAD

**Issue by issaomar** [tronscan/tronscan-frontend#226]
In regards to gaming - when a video game for example like fortnite: who releases exclusives skins (costumes) for certain occasions like the World Cup. In a few days or weeks these skins will no longer be available for sale by fortnite - can the users who bought the exclusive skins go ahead an resale it to other users who did not get the opportunity to buy st whatever the demanding price would be?

**Comment by BaCoNL** [comment]
No relevance to tronscan
