### ISSUE TITLE
Tron template

### ISSUE THREAD

**Issue by CITYUPTAKE** [tronscan/tronscan-frontend#227]
Hello this is cityuptake sr candidate. I thought I was updating a file on my template. It seems its stuck on fork refresh or something. Was wondering if any known issue was going on with github?

**Comment by CITYUPTAKE** [comment]
Will not refresh

**Comment by BaCoNL** [comment]
Your repo is empty:

https://github.com/CITYUPTAKE/tronsr-template

**Comment by CITYUPTAKE** [comment]
It will not refresh

**Comment by BaCoNL** [comment]
It should look like this: https://github.com/cryptoguyinza/tronsr-template

fork the repo, and use git to commit and push your changes to your forked repo.

**Comment by BaCoNL** [comment]
I'm closing this issue, it is not is issue because it is not a issue in retrospect to tronscan

**Comment by CITYUPTAKE** [comment]
When I fork it, its locked on refresh fork screen
