### ISSUE TITLE
on  the markets page

### ISSUE THREAD

**Issue by travisj127** [tronscan/tronscan-frontend#236]
When you click on one of the exchanges it says do you want to go to external page. There are a bunch of little white squares that start flashing. How much do I get paid for reporting this bug?

![trx bug](https://user-images.githubusercontent.com/37807674/41614369-306dfa84-73ad-11e8-8b11-2537f6c71c70.JPG)

**Comment by zk19862018** [comment]
This bug can not be reproduced on my PC, try chrome browser

**Comment by travisj127** [comment]
The bug is not in chrome it is in the Tron browser

**Comment by travisj127** [comment]
when you click on binance trx/btc you get this on the tron scan desktop

**Comment by Rovak** [comment]
i'm unable to reproduce this on the desktop version on Ubuntu
