### ISSUE TITLE
HELP HELP HELP!!!!!!    Hello!!! 500,000 TRX have disappeared from my wallet. !!!!

### ISSUE THREAD

**Issue by Sergey343443** [tronscan/tronscan-frontend#237]
Hello!!! 500,000 TRX have disappeared from my wallet. !!!!

my wallet . TAc9gen6H9HpneB5dNL8SHDuGkF5eX8DAs

**Comment by Rovak** [comment]
Hi @Sergey343443, the network has been reset and all funds have been reset. The current TRX on the network are purely for test purposes and hold no value.

**Comment by Sergey343443** [comment]
Thank you!!!!!
