### ISSUE TITLE
[Bounty] Tronscan V2 - MARKETS - trading volume and currency - price per Trx remains on US dollar

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#24]
Bug Report
-------------
if the currency is changed, the price per Trx remains on US dollar

![image](https://user-images.githubusercontent.com/39301026/40129196-fb05f1fa-5933-11e8-8dc4-e326f13ecf74.png)

changed to EUR:
![image](https://user-images.githubusercontent.com/39301026/40129301-3db4ce54-5934-11e8-83c1-2d47b66c414d.png)

the diagrams remain in USD:
![image](https://user-images.githubusercontent.com/39301026/40129363-64280f92-5934-11e8-8c49-1f5cfab8ac1f.png)

result:
price for 1 TRX in USD
![image](https://user-images.githubusercontent.com/39301026/40129287-324b73d8-5934-11e8-9f8f-f360b2287cf2.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
16. may 2018 6:00 pm (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

**Comment by Rovak** [comment]
Fixed
