### ISSUE TITLE
[Bounty] [Desktop]: On connecting ledger and opening account doesn't display the copy address icon

### ISSUE THREAD

**Issue by rahulsharmablr** [tronscan/tronscan-frontend#244]
1. Open Tron desktop app
2. Connect it to ledger TRX app
3. Navigate to my account page
4. Copy icon is not displayed against the address.

Note: after doing any activity this works fine.

**Comment by rahulsharmablr** [comment]
![image](https://user-images.githubusercontent.com/37593091/41734327-37d7db2a-75a4-11e8-9ab1-7a3c6b386802.png)

**Comment by Rovak** [comment]
looks like a font awesome issue, all icons won't work the first time. see the bandwidth and power blocks. I'll look into it
