### ISSUE TITLE
[Bounty] [FATAL ERROR] Tronscan V2  - Google Chrome- search function faulty - website is no longer available

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#25]
Bug Report
------
when i search for a block and enter a number all navigation elements of the website disappear. there is only the background image to see.
![image](https://user-images.githubusercontent.com/39301026/40280842-4fc9f3ee-5c59-11e8-9987-478fb9e79dab.png)

Result:
![image](https://user-images.githubusercontent.com/39301026/40280837-3dd1402a-5c59-11e8-99f7-164be4b66a80.png)

i got some errors:
![image](https://user-images.githubusercontent.com/39301026/40280794-ee7e3adc-5c58-11e8-8d45-ae447f486ddb.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
20. may 2018 6:00pm(UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

**Comment by Rovak** [comment]
Fixed
