### ISSUE TITLE
[Bounty] Tronscan V2 - Incorrect translation / German and English mixed

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#27]
Bug Report
------
the complete translation of the website still needs to be revised.
I can help you with that!
please contact me !

![image](https://user-images.githubusercontent.com/39301026/40281049-70e9d2ee-5c5c-11e8-9e3a-a7f8112237b1.png)
German and English?

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
20. may 2018 6:30 pm (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

**Comment by Rovak** [comment]
Translations have to be contributed by the community. I don't consider this a bug
