### ISSUE TITLE
[BUG] SECURITY RISK !!! Able to sign back in after sign out [Private key sign in]

### ISSUE THREAD

**Issue by corytam** [tronscan/tronscan-frontend#272]
Managed to be able to click the "sign in" button after clicking sign out.
Was able to this several times. Able to access account details etc.

This occurs when private key is entered to sign in.

Able to duplicate issue

If you like to support me please donate TRX at:
TMtjXJEjd29nYxTyhuYKPqr5SbdnWZDEoC

Thank you!

**Comment by joe-meyer** [comment]
I can confirm this behavior and agree, if you sign out your private key should be completely forgotten.

**Comment by artinpetrossian** [comment]
+1

**Comment by joe-meyer** [comment]
@rovak I believe this should also be closed by https://github.com/tronscan/tronscan-frontend/commit/439886e1ccf3b93907f2a8d4723e630fe893bd9e right?

**Comment by Rovak** [comment]
@joe-meyer correct, thanks for pointing out!
