### ISSUE TITLE
[Bounty][FRQ] Tronscan V2 - CSS different object size

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#274]
Feature Request/ Bug Report
---------

![grafik](https://user-images.githubusercontent.com/39301026/41859578-c19a3524-789c-11e8-8bcb-bd4caf2c66d6.png)

different object sizes -> please check -> margin ;)
![grafik](https://user-images.githubusercontent.com/39301026/41859823-57aaf0e4-789d-11e8-80d4-948c94f38a16.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
25. June 2018 5:00 pm (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

Bounty Program
--
https://twitter.com/justinsuntron/status/1002072890349531137

**Comment by zk19862018** [comment]
fixed
