### ISSUE TITLE
[Bounty][FRQ] Tronscan V2 - missing status information - Token - no tokens (available)

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#277]
Bugreport
-----------
if no tokens are available an empty page is displayed.. it would be nice if the user received a corresponding message...no tokens (available)
![grafik](https://user-images.githubusercontent.com/39301026/41861578-fef8e866-78a1-11e8-936b-79b90ee3c2c4.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
25. June 2018 5:00 pm (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

**Comment by zk19862018** [comment]
fixed

**Comment by PMD3VSolution** [comment]
Great, thanks!
