### ISSUE TITLE
Search block - Table - missing age informations

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#285]
Bugreport
-----------
Search block - Table - missinge age informations:
![grafik](https://user-images.githubusercontent.com/39301026/41898088-5910ceae-7929-11e8-8dc7-eff68a767792.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
26. June 2018 6:00 am (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

**Comment by joe-meyer** [comment]
Is this only an issue for block 0? Or is it perhaps that all of those transactions and transfers are set as unconfirmed and thus they wouldn't have an age? Just speculating.

**Comment by Rovak** [comment]
This is only a problem for the genesis block, working as intended
