### ISSUE TITLE
diagram  - mouse over faulty scale

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#287]
Bug Report
------------
The scale does not match with the detail values:
![image](https://user-images.githubusercontent.com/39301026/41908910-d2adb1e8-7945-11e8-8924-a6bf61c1028b.png)
6.20am is not 6 o'clock am

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
26. June 2018 10:00 am (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

**Comment by joe-meyer** [comment]
I believe I've identified the issue here. I'll try out a fix and put in a pull request for this tonight.
