### ISSUE TITLE
[Bounty] Minor Bug on Token Participation Page

### ISSUE THREAD

**Issue by Jacob8765** [tronscan/tronscan-frontend#29]
![image](https://user-images.githubusercontent.com/33853949/40281183-fabc5ba8-5c2b-11e8-9002-c04d62129c9d.png)
Should be page 1 of 1

**Comment by PMD3VSolution** [comment]
i found the same issue: [Bounty] Tronscan V2 - incorrect table informations
i think it is a db related issue... i created a token but can't find it (Tokens->Overview)

**Comment by Rovak** [comment]
Duplicates #28
