### ISSUE TITLE
Representative

### ISSUE THREAD

**Issue by Leesungkun** [tronscan/tronscan-frontend#296]
![image](https://user-images.githubusercontent.com/9384553/42018237-66c7c7ae-7aec-11e8-9e03-78c67aeb9bab.png)

bug page: https://tronscan.org/#/address/TGj1Ej1qRzL9feLTLhjwgxXF4Ct6GTWg2U/voters

Bug report

You will not be taken to a page where you can see the next voter on that page. Please confirm.

my address: TMbR93Qnuu9pDnaEJsibYo6JLeR33MNG53

**Comment by Leesungkun** [comment]
![image](https://user-images.githubusercontent.com/9384553/42018373-e066c86c-7aec-11e8-9c08-810d30920c42.png)

added

**Comment by Voidrays** [comment]
Yes, it will be fixed. See #294

**Comment by Leesungkun** [comment]
Okay. Thank you.

**Comment by joe-meyer** [comment]
@rovak can this be closed?
