### ISSUE TITLE
Hitbtc trx token migration problem

### ISSUE THREAD

**Issue by raathmd** [tronscan/tronscan-frontend#297]
It appears that Htbtc apparantly gave special instructions for the token migration, however, i cannot find these instructions.
In addition, after converting to ETH and trying to transfer to Gate.io so that i can purchase TRX again,  they are not allowing any currency withdrawals.
I want to purchase TRX again but need to get off this exchange. Can Tron assist with finding out what the process is for converting the tokens?
bEST REGARDS
Marcus Raath
South Africa

**Comment by Rovak** [comment]
Hi Marcus, unfortunately i can't help you with converting your tokens. please try the official telegram group for help
