### ISSUE TITLE
Participation button

### ISSUE THREAD

**Issue by conormcgregor99** [tronscan/tronscan-frontend#299]
Hello,
While issuing a token on Tronscan, the participation button for a buyer requires he/she go through a longer process than necessary. 
Tokens>Participate>Search through the /view page>buy

Instead it would be far more convenient and better for a 'participate' button to be on the token info page itself where website, start date etc is provided. So that a issuer can directly link this page to the buyer instead of having to go through the whole list on '/view' page.

This will become an increasingly difficult issue once the number of issued tokens increases, people surely cant go through all the pages to search. Hence having a participate button on the token page itself is going to be very useful

I hope this is implemented as soon as possible.

Thank you.

**Comment by Rovak** [comment]
Fixed
