### ISSUE TITLE
[Bounty] Tronscan V2 - Tokens Overview - only 15 records are displayed

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#30]
Bug Report:
-------------
only 15 records are displayed!???
![image](https://user-images.githubusercontent.com/39301026/40281198-8de83bea-5c5e-11e8-8807-5abacc42da0d.png)

there is also no navigation bar to get to the next page... Page 1 of 0 ?

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
20. may 2018 6:00 pm (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

**Comment by Rovak** [comment]
Only 15 tokens have been created so far. In the previous version a user could create more tokens on the same address. Since the update you can only create 1 token for every address. This may be the cause that there are less tokens now
