### ISSUE TITLE
Withdrawal on binance

### ISSUE THREAD

**Issue by porcomus** [tronscan/tronscan-frontend#303]
Withdrawal for TRX will be suspended during the mainnet swap and will open again once we deem the mainnet to be stable
### **this is normal? 7 days?**
![binance](https://user-images.githubusercontent.com/40756073/42152597-4ae56a3c-7de9-11e8-9e4f-eef60d47c06f.png)

**Comment by Rovak** [comment]
Hi @porcomus, unfortunately i cannot help with Binance related issues, try contacting Binance on twitter https://twitter.com/binance
