### ISSUE TITLE
Not able to get testnet coins

### ISSUE THREAD

**Issue by Anil402** [tronscan/tronscan-frontend#304]
I have set up the gRPC and full node for tron.
I have created a new address by using this API 
curl -X POST -k http://127.0.0.1:18890/wallet/generateaddress.\
It gives me the address and key.
Now how can I get some testnet coins? as I have run full node in tesnet mode.

And also when I am using account info API.
curl -X POST  http://127.0.0.1:18890/wallet/getaccount -d '{"address": "base 64 encoded address pasted here"}'
it return {} blank object

**Comment by Rovak** [comment]
Hi @Anil402, this issue is related to the https://github.com/tronprotocol/java-tron project, please try submitting an issue there
