### ISSUE TITLE
Confusion in syncing

### ISSUE THREAD

**Issue by Anil402** [tronscan/tronscan-frontend#305]
I have started the full node jar in with testnet config 
I am getting output like this
17:55:38.058 INFO  [pool-3-thread-1] [o.t.c.n.n.NodeImpl](NodeImpl.java:638) LocalNode stats:
============
MyHeadBlockNum: 0
advObjToSpread: 0
advObjToFetch: 0
advObjWeRequested: 0
unSyncNum: 0
blockWaitToProc: 0
blockJustReceived: 0
syncBlockIdWeRequested: 0
badAdvObj: 0

17:55:47.774 INFO  [main] [o.t.c.n.n.NodeImpl](NodeImpl.java:739) other peer is nil, please wait ... 
17:55:48.058 INFO  [pool-12-thread-1] [SyncPool](SyncPool.java:138) -------- active connect channel 0
17:55:48.058 INFO  [pool-12-thread-1] [SyncPool](SyncPool.java:139) -------- passive connect channel 0
17:55:48.058 INFO  [pool-12-thread-1] [SyncPool](SyncPool.java:140) -------- all connect channel 0
17:55:48.058 INFO  [pool-12-thread-1] [SyncPool](SyncPool.java:161) Peer stats:
Active peers
============
Other connected 

Is it ok?

**Comment by Rovak** [comment]
Hi @Anil402, this issue is related to the https://github.com/tronprotocol/java-tron project, please try submitting an issue there
