### ISSUE TITLE
Frozen expire date

### ISSUE THREAD

**Issue by Rovak** [tronscan/tronscan-frontend#306]
"A question about my TronScan Wallet. The exipre date of my balance is 7/1/2018 because I froze my trx 6 days ago. But I haven't unfrozen my funds so I guess the date is wrong and it should be 7/7/2018 in reality, 3 days from now, right?"

**Comment by Voidrays** [comment]
I assume you did not freeze the balance again. So the expire date of frozen amount won't change until you freeze that again.
