### ISSUE TITLE
[BUG] https://tronscan.org/#/nodes website crashes

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#309]
Bugreport
-----------
https://tronscan.org/#/nodes
the page crashes and I get a lot of error messages

![image](https://user-images.githubusercontent.com/39301026/42295961-1128cf88-7ff0-11e8-88e6-5cffde7fafbd.png)

![image](https://user-images.githubusercontent.com/39301026/42295964-1add4da6-7ff0-11e8-9061-f79e8e10fe8b.png)

**Comment by Rovak** [comment]
fixed
