### ISSUE TITLE
Private Key

### ISSUE THREAD

**Issue by machopli** [tronscan/tronscan-frontend#318]
I didn't realize I had created a new wallet before sending my TRX to this new wallet.  I do not have the private key associated with this new wallet.  Is there anyway to reverse a transaction in my Tron wallet without having the private key?  Is there anyway to retrieve the private key?

**Comment by machopli** [comment]
Any help is appreciated.  I see the TRX in the wallet, but cannot access it.

**Comment by Rovak** [comment]
If you did not save the private key then there is no way to retrieve the TRX from the wallet unfortunately

**Comment by machopli** [comment]
That is sad.  Is there anywhere the private key would have been saved on my computer if I didn't download it?
