### ISSUE TITLE
My Tron's wallet Address is different that my Private key Print out

### ISSUE THREAD

**Issue by guerrero19209** [tronscan/tronscan-frontend#319]
Hello

I just transferred 150K Tronix. When I created my wallet, I printed out my private key and address. I accessed my wallet many times before transferring anything. I just transferred from Binance to my Tron wallet. I used the scan feature for the transfer. Now, when I access my wallet by manually entering the private key, the address that appear is different than my print out address.

The address that I scanned and its in my print out paper is
TYEZzZusdNypHFmQRontnViTVjPabXFm7nm, the funds are there

Now, when I enter my private key manually, a new address appears
TTFBjKvxWzaaLDnLvDh6yJmHKwG3AAFrxD, no funds here.

How can I access my funds? please help

Luis Guerrero

**Comment by guerrero19209** [comment]
Sorry, I know what happened. It creates a different address when the characters are typed in small caps.

**Comment by Rovak** [comment]
good to see you got it resolved
