### ISSUE TITLE
[Bounty] Creating a wallet - Receive TPX for the test - Send TRX

### ISSUE THREAD

**Issue by Adsize** [tronscan/tronscan-frontend#32]
1. 
OPEN WALLET->Private Key->enter various arbitrary characters for example
12@:-)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))
Trying to get TRX for testing on the testnet.
Getting to the balance 100,000 TRX
We continue to try to get more. 
"Error Limit (10 requests) reached for address 27a7pkp1K1crdMahEiJoPHnrD22rYegaUHq"
After about 30 attempts:
"10,000 TRX Have been added to your account!"
We continue to try to get more.
We have on balance 200,000 TRX

2.
Trusted on different browsers and accounts. If you specify "0" in the recipient's 
address field, for example SEND TO:
00000000000000000000000000000000000
instantly there is a magic - from a site there will be only a background.

Voluntary donation TRX: 0x00cb09ec70354ab8b7c328da2c0e5e4629f411da

**Comment by ffera** [comment]
I need to use which address here to help to take care of the balance

**Comment by ffera** [comment]
which address I need to write Tron address writes me wrong says ETH says wrong which address yazacam to attract

**Comment by Rovak** [comment]
Duplicate
