### ISSUE TITLE
Something went wrong while submitting my votes...

### ISSUE THREAD

**Issue by ironbeeper** [tronscan/tronscan-frontend#324]
Hi! I have been trying to vote for all SR who have their "Team Page" but there is an error. I have enough TP to vote...
You can check my votes: TWhvGqSCDdfKZoTRY9fKSMfLk8UnfoUfPY

![image](https://user-images.githubusercontent.com/17235949/42586618-d28af3d4-8538-11e8-9d11-d0a801b82bbe.png)

**Comment by JWhiteUX** [comment]
The same thing is happening to me. I'm trying to remove votes to unlock some TRX to trade elsewhere. I'm receiving the same error message.

I'm using TronScan + Ledger Nano S

<img width="1165" alt="screen shot 2018-08-13 at 11 29 55 am" src="https://user-images.githubusercontent.com/12961108/44050594-3fb7ecec-9eec-11e8-82fc-52b518940332.png">

**Comment by angusmcnab** [comment]
Happens all the time to me.

**Comment by tlarock80** [comment]
Happens all the time to me.
