### ISSUE TITLE
 transcan.org  I'm trying to transfer the wrong address ,he always says ? what account will he have ?

### ISSUE THREAD

**Issue by ffera** [tronscan/tronscan-frontend#33]
I'm trying to transfer the wrong address ,he always says ? what account will he have ?  ?why can't I transfer trx here

**Comment by Rovak** [comment]
It is unclear what exactly the problem is, could you describe it in more detail?

**Comment by ffera** [comment]
I want to draw tokens now, but I wrote to another account Tron address says wrong

**Comment by ffera** [comment]
I want to do send but tell me which wrong address says
 wallet I need to use it.   transcan.org I want to get TRX in the address, but I always said wrong address says TRX I wrote my address said wrong ?

**Comment by ffera** [comment]
![adsiz](https://user-images.githubusercontent.com/35933394/40390244-3b77092a-5e1d-11e8-952f-e7e10da9401b.jpg)
 

look at the picture

I wrote my address correctly, but he says

**Comment by ffera** [comment]
he says it's wrong

**Comment by Rovak** [comment]
ah right, the transfer window checks if the address already exists, but if there hasn't been any transfers yet then it doesn't. i'll fix it

**Comment by ffera** [comment]
I wrote the right address, but it says it's wrong.

**Comment by ffera** [comment]
you saw the picture.

**Comment by ffera** [comment]
????I need to write in which coin address

**Comment by Rovak** [comment]
@ffera i double checked your address, you are trying to send it to an Ethereum address. Testnet is not connected to the Ethereum network and all tokens are test tokens which hold no value.
