### ISSUE TITLE
[Bounty] Tronscan V2 - Google Chrome - after logging off a blank page is displayed

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#34]
Bug Report
---------
i click on the logout button .... and i got a blank page 
![image](https://user-images.githubusercontent.com/39301026/40369344-0be2843a-5dde-11e8-92ce-cd6e4c346bd2.png)

i got many error messages :
![image](https://user-images.githubusercontent.com/39301026/40369361-16f8ddec-5dde-11e8-8daf-9a69915fdcc6.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
22. may 2018 4:00 pm (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 -> NOT Effected
IE 11 -> NOT Effected

**Comment by Rovak** [comment]
Fixed
