### ISSUE TITLE
Tronscan wallet problem

### ISSUE THREAD

**Issue by mnjc33** [tronscan/tronscan-frontend#340]
I created a wallet at tronscan and was given an address and private key. Upon being creted i was logged into the wallet automatically and proceeded to transfer two amounts to the wallet address provided. Transcaction was successful and logged out. Went back to log in using the private key given to me and suddenly the wallet address is different and the TRX balance is 0.
How can this be corrected please.

**Comment by haiderali443** [comment]
the same thing happened to me too. i don't know what is this. my public address changed too

**Comment by Rovak** [comment]
i'm unable to reproduce this problem, I've tried creating several wallets and the address didn't change when i tried to use the same private key. Can you provide some steps to reproduce it?

**Comment by mnjc33** [comment]
In trying to figure this problem out, i noticed the following; when i highlighted and "copied" my private key from a saved pdf format and "paste" it in the open wallet logon screen the private key was reversed. It logged me in but to a different account where the address was difference due to the private key being different (reverse).
After realising this, i logged in by typing out my private key and i was able to logon to my original account with the correct address.
