### ISSUE TITLE
multiple public addresses on tronscan.org

### ISSUE THREAD

**Issue by haiderali443** [tronscan/tronscan-frontend#341]
hi, i'm Haider. 14 hours ago i withdrew my trx from binance and sent them to tronscan.org at this address : TLs97k44iFwH732BpxHRJFYQxrEtXBq4Z3
I froze my trx & voted for tron' SR sesameseed. 

Today when i logged into my account using the same Private Key it doesn't show any trx or transaction in my account and i also see a different public address. This is the current public address being displayed right now :   
TUtwPt2waLLsRPeCDd9gbDC9dFo6xVnAiX

I would like to know the solution. that whether my tronscan.org has created multiple address or not? how do i switch between these addresses? in short i would like to have access to my trx frozen at tronscan.org

**Comment by Rovak** [comment]
i'm unable to reproduce this problem, can you provide the steps to reproduce this issue?

**Comment by haiderali443** [comment]
I logged into my tronscan.org account with my private key. So instead of logging into my account i was logged in another account. I sent my trx from binance to this account's receiving address (TLs97k44iFwH732BpxHRJFYQxrEtXBq4Z3) and voted for SesameSeed in the Tron SR elections and froze my trx.

the next day when i logged in with the private key i was logged into some other account and i didn't have any trx in it or tron power. Since yesterday i'm being logged into a account with a different public address (TUtwPt2waLLsRPeCDd9gbDC9dFo6xVnAiX). 

I would like your help to find a solution that how to log into this account and recover my trx (TLs97k44iFwH732BpxHRJFYQxrEtXBq4Z3) or transfer my trx to this account (TUtwPt2waLLsRPeCDd9gbDC9dFo6xVnAiX). 

Please
Thanks.

**Comment by haiderali443** [comment]
![binance withdrawl](https://user-images.githubusercontent.com/41188531/42722944-3453fa02-876e-11e8-8139-3b2dd426415d.JPG)

This is the transaction slip from my binance account
