### ISSUE TITLE
Setting up ecommerce website to accept TRX

### ISSUE THREAD

**Issue by Stemulite** [tronscan/tronscan-frontend#342]
Hello, 
Please, How can I set up my e-commerce website https://www.StemuliteFitnessFormula.com so that I can offer TRX as a form of payment but also to help in proliferation of the network through my traffic and customer base?

I would also ask about how I could run this site on your network? This possible at this time?

Thank you in advance for any help, Great job you guys!!!

Matthew Wagner
StemuliteFitnessFormula.com
541-997-6100
702-597-9449
805-591-9488 m

**Comment by Rovak** [comment]
https://www.coinpayments.net/ provides a way to accept TRX on your website
