### ISSUE TITLE
Password sign up, transactions...

### ISSUE THREAD

**Issue by ironbeeper** [tronscan/tronscan-frontend#343]
Hi! While creating a wallet there is requirement to set your password! When I want to sign into my wallet there is no need to enter your password and unlock the wallet!!! So if somebody steal my private key, there is zero security barriers (like password,ect...)
![image](https://user-images.githubusercontent.com/17235949/42699563-68800238-86c1-11e8-95d8-159eea21a18a.png)

**Comment by Rovak** [comment]
working as intended for now
