### ISSUE TITLE
Ledger wallet address on the tronscan.org not visible

### ISSUE THREAD

**Issue by idforcrypto** [tronscan/tronscan-frontend#345]
hi,

I have a ledger nano S. i have deposited my tron and voted for SR using my ledger. 

I can search for my address and its available.

Why does the address not shown on accounts page on tronscan.org. also the no. of account is not rightly calculated as ledger address is missed. Indicating the correct number of address is a confidence booster for the project.

**Comment by Huaxan** [comment]
The ledger nano S is only useable trough the Tronscan desktop app
