### ISSUE TITLE
[Bounty] Tronscan V2 - accessing the website with exception

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#35]
Bug Report
-----------
when you visit the website you get the following exception:
![image](https://user-images.githubusercontent.com/39301026/40371663-4549c742-5de3-11e8-96e3-ba38d952ef8b.png)

![image](https://user-images.githubusercontent.com/39301026/40371676-4fd090e2-5de3-11e8-8e6e-6f2ac740fcde.png)

Troubleshooting/Solution
-------------
https://github.com/SumiMakito/Awesome-qr.js/blob/master/README.md

the path is not correct;
![image](https://user-images.githubusercontent.com/39301026/40371848-adfe231e-5de3-11e8-9f2b-031f93b27975.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
22. may 2018 5:00 pm (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

**Comment by Rovak** [comment]
The plugin doesn't allow this to be fixed with webpack and this isn't really an issue now
