### ISSUE TITLE
Loss of funds

### ISSUE THREAD

**Issue by spartinvic** [tronscan/tronscan-frontend#350]
I sent 10,000 Tron (TRX) to the Tron Cash Contract Address ( TJdSvPXNCF7fKUjxoagmupEzjc1TVVY1NR ) via the webpage, http://troncash.network/ to buy TRXC at 25% off. Tron Cash was not automatically sent to my TRX address. This is the transaction hash:1cd91ff7fa90a07168d25b9caf68d6b0f48f64f5903310b6c1ff64e0b9437be9
My Tron Address: TQX3uqVcBJgx2ZMzvqpCcE4sH848wAKfex
Can anyone help me?

**Comment by Rovak** [comment]
Buying tokens is done on the [Participate](https://tronscan.org/#/tokens/view) page. You don't need to send TRX to an address. To get your funds back you will need to contact the owner of the address
