### ISSUE TITLE
Kann nicht von der Wallet senden

### ISSUE THREAD

**Issue by beeroy77** [tronscan/tronscan-frontend#354]
Hallo, ich kann kein TRX zu Binance schicken. Es kommt eine Fehlermeldung. Was kann ich machen?

**Comment by PMD3VSolution** [comment]
Was erhalten Sie denn für eine Fehlermeldung? An welche Adresse möchten Sie TRX senden? Wir tun alles um Ihnen schnellstmöglichst zu helfen!

**Comment by beeroy77** [comment]
TFqok53uEZT4XByjWxhJP6naA3RP6ydh2n

**Comment by beeroy77** [comment]
Fehlermeldung:
Beim senden der Transaktion ist ein Fehler aufgetaucht

**Comment by PMD3VSolution** [comment]
kannst du ein Screenshot erstellen? bzw. gibt es eine Transaction-ID?

**Comment by beeroy77** [comment]
Duplikat von #
<img width="1680" alt="bildschirmfoto 2018-07-15 um 12 14 11" src="https://user-images.githubusercontent.com/40612179/42733342-3a4702d4-8830-11e8-97e9-e8d08d6d267e.png">

**Comment by PMD3VSolution** [comment]
hast du genug tron power / Bandbreite auf deinem Konto?
Versuch mal ein TRX einzufrieren und die Transaktion zu wiederholen

**Comment by beeroy77** [comment]
Hallo, das problem besteht immer noch

**Comment by PMD3VSolution** [comment]
Hallo, von welcher trx adresse versuchen Sie das guthaben zu übertragen? Kann ich Sie auch direkt erreichen? Per Email? Evtl. Können wir gerne auch eine TeamViewer Sitzung machen!

**Comment by PMD3VSolution** [comment]
Ich habe versucht das Problem nachzustellen, ich habe keine Probleme mit dem Transfer!

**Comment by beeroy77** [comment]
Hallo, ich habe 35 TNX eingefroren, jetzt hat es geklappt. Wieso muss man token einfrieren?

**Comment by PMD3VSolution** [comment]
Hallo, ja sie müssen trx einfrieren um bandbreite und tron power zu generieren! Ist erforderlich um trx zu übertragen!

**Comment by PMD3VSolution** [comment]
Fixed!
