### ISSUE TITLE
Token Partcipation

### ISSUE THREAD

**Issue by raulnetusa** [tronscan/tronscan-frontend#358]
Hello,

I created one token and i can see the token on the list.I am not seen the token on the "Participate" list.
Is that something that i need to do on my end to get it listed?

Best,

**Comment by PMD3VSolution** [comment]
The start time is not yet reached!  The token is only displayed after the start time has been reached!

**Comment by PMD3VSolution** [comment]
What is the token name?

**Comment by raulnetusa** [comment]
Livesoccer

**Comment by raulnetusa** [comment]
You are right! Was my mistake. I apologise
