### ISSUE TITLE
Ошибка tronscan.org

### ISSUE THREAD

**Issue by Evilcat26** [tronscan/tronscan-frontend#361]
Ошибка проявляет себя когда я хочу сделать максимальную ставку голосов Суперпредставителей, сайт просто перестает показывать какие либо знаки, отображается только картинка...

**Comment by PMD3VSolution** [comment]
could you provide more informations? for better understanding, please take a screenshot of the error

**Comment by Evilcat26** [comment]
Вот как видно на фото, при добавлении последнего голоса, все пропадает,
приходится держать 1 голос не использованным.

ср, 18 июл. 2018 г. в 22:25, PMD3VSolution <notifications@github.com>:
