### ISSUE TITLE
tokens

### ISSUE THREAD

**Issue by alfo688** [tronscan/tronscan-frontend#364]
I was away from home during the mainnet lauch so I missed the deadline. Will there be a way for me to exchange my old TRX token to the new ones?

Alain F.

**Comment by Kyle-Kidd** [comment]
I believe you can still deposit erc-20 TRX to your ETH address on Binance, then withdraw it to your TRX mainnet address.  Try testing this with a small amount.

**Comment by alfo688** [comment]
Thanks, i did try earlier today and it works,   thanks
