### ISSUE TITLE
Wallet address not valid

### ISSUE THREAD

**Issue by kse2336** [tronscan/tronscan-frontend#374]
I just opened a wallet and I am not able to send anything to it because Tronscan doesn’t recognize the address even though it was created on the website.  I am able to log in and but not able to transfer anything to that address.  This is the address that is invalid and issued by TronScan.
  TPSbYRvhiS2mJcFvqRgugRkvrQRWDU5kk

I checked and rechecked to make sure I entered correct and it matches the address when I sign into the wallet.

**Comment by Rovak** [comment]
the address is missing one character at the end, could it be that you missed a character while trying to copy the address?

**Comment by kse2336** [comment]
No because when I log into Tronscan it is the exact same. Address

**Comment by kse2336** [comment]
I could screenshot the wallet but I don’t see where I can attach a picture.

**Comment by Rovak** [comment]
since that wallet is empty i would like to know which private key you are using, because that address should not be possible. could you send it to royvankaathoven@gmail.com

**Comment by kse2336** [comment]
On the way
