### ISSUE TITLE
Web Bug

### ISSUE THREAD

**Issue by astronomerforfun** [tronscan/tronscan-frontend#382]
Hello, 

Is there any way to get back into this account?  TXit4BaytkhxCgmB88L9fKytzpGXUQJn3u.  I went through the steps on Tronscan.  Saved my key, etc.  Sent myself tokens but the address seemed to have changed.  What are your thoughts on this?  

My email is shockley7772@icloud.com

A request to withdraw 11808 TRX from your Liqui account to address TXit4BaytkhxCgmB88L9fKytzpGXUQJn3u was just made.

**Comment by joe-meyer** [comment]
Seems like this is a duplicate to #381. Probably doesn't merit a second issue being opened unless there is a separate bug here?

**Comment by astronomerforfun** [comment]
You are correct.  It's a duplicate.

On Jul 19, 2018, at 05:32 PM, Joe Meyer <notifications@github.com> wrote:

Seems like this is a duplicate to #381. Probably doesn't merit a second issue being opened unless there is a separate bug here?
