### ISSUE TITLE
Freezing new trx. 

### ISSUE THREAD

**Issue by brianross92** [tronscan/tronscan-frontend#386]
I’m not sure if this was intentional but when you freeze the rewards you get from the airdrop, it resets the “freeze” date and adds 3 more additional days.

**Comment by Rovak** [comment]
This is the way the Tron Protocol works, i don't know if this will be changed in the future2

**Comment by brianross92** [comment]
Okay perfect. Makes sense. That way people have to freeze there trx even longer if they want to vote. Appreciate the answer.
