### ISSUE TITLE
Tronscan desktop

### ISSUE THREAD

**Issue by jerry68** [tronscan/tronscan-frontend#387]
Hi,  

I just tried the Tronscan desktop with Ledger Nano S (to recieve & send TRX), here are my suggestion for improvements:

1. To change the zip file to a better installation file (it is complicated/inconvenient for users to unzip/extract files, and locate the exe file to launch the program)
2. There is no "paste" function in the send address box.  I need to type in the address manually.  It is very risky (there are chances of typo error)

Hope you can look into it to enhance the user's experience.

Best regards,
Jerry

**Comment by Rovak** [comment]
I've solved the paste function in version 1.1.1.
I will be adding a installation process later

**Comment by jerry68** [comment]
No... problem has not been solved yet.  I downloaded version 1.1.1 (windows
version), and tried to paste the copied receiving address in the "Send"
box  (by right clicking my mouse), nothing came out from the screen.
Please check.

[image: image.png]
