### ISSUE TITLE
Web issue: 0 Transactions in transaction count

### ISSUE THREAD

**Issue by zeshanvirk** [tronscan/tronscan-frontend#388]
![image](https://user-images.githubusercontent.com/19382057/42988951-d8139d20-8c17-11e8-8421-31d7187612e9.png)

i've 1 transaction in transaction list but the count is still 0.

**Comment by PMD3VSolution** [comment]
This is a caching problem in Firefox. Please press the F5 key to update the page or use Google Chrome.

**Comment by Rovak** [comment]
^
