### ISSUE TITLE
Tronscan -> Nano S

### ISSUE THREAD

**Issue by GPose** [tronscan/tronscan-frontend#394]
Hi,
-I installed the Tron app on the device as directed using Ledger Manager Chrome app
-I transferred my TRX to Tronscan while my ledger was connected. 
-Tron does show up on home screen of the device.
-Tronscan shows my correct balance. However when I disconnect the Nano... it still shows my balance, and according to my friend who has done this successfully, it should NOT show my balance when the Nano is NOT connected. Meaning the TRX is NOT on the device. Is this correct?
My question: How do I move TRX to the device from Tronscan? 
Thanks for any help on this...
Greg

**Comment by Rovak** [comment]
Your TRX will never be ON your device or ON Tronscan. All your TRX will always be stored on the blockchain and your Nano S merely holds the key to access your TRX. The key on your Nano S will never be shared with Tronscan and Tronscan will never be able to make transactions without your consent
