### ISSUE TITLE
Голосование за Суперпредставителя

### ISSUE THREAD

**Issue by MazaiNikolaevish** [tronscan/tronscan-frontend#397]
Здравствуйте. В процессе голосования выявиласть такая ошибка. Я не могу проголосовать всеми монетами. Если выставляю в голосование все монеты то меня выкидывает с сайта tronscan.org Поэтому оставляю всегда 1 голос в резерве. Браузер Google Chrome
Версия 67.0.3396.99 (Официальная сборка), (64 бит)
![default](https://user-images.githubusercontent.com/41501602/43032905-89ee1a3c-8cc9-11e8-8a81-81e0df108c50.JPG)
![2](https://user-images.githubusercontent.com/41501602/43032906-8a0d698c-8cc9-11e8-9c29-65f7021113b5.JPG)
![3](https://user-images.githubusercontent.com/41501602/43032907-8a27d47a-8cc9-11e8-8cd4-3e5db8f4be44.JPG)
![4](https://user-images.githubusercontent.com/41501602/43032908-8a43c70c-8cc9-11e8-8ce0-0db0bca6ab60.JPG)

**Comment by PMD3VSolution** [comment]
i can't recreate your problem, have you tried another browser?
