### ISSUE TITLE
My token balance says 0!

### ISSUE THREAD

**Issue by romano1125** [tronscan/tronscan-frontend#402]
I transfered 50k tokens from my binance account to tronscan 6 days ago.  I received a email verification when I sent it also.  it was transferred successfully as I checked my wallet later that day.  I went to check my account today to transfer more tokens into my wallet but come to find out my wallet says 0. I doubled checked my binance withdrawals and everything says it transferred.  can you please help me find my tokens as I am new to crypto.

**Comment by conormcgregor99** [comment]
2-3 things here. 
Did you save the keystore file/password and the Private key safely? while creating account on Tron Scan?
Did you manually type the Private key or copy paste it?
Are you able to log in? If so,
Did you double check that the public key of your account is the same as the public key you sent the tokens from binance, letter to letter? 
Does your wallet show any transactions transferring the tokens out of the wallet? 
Could you provide your PUBLIC key address?

**Comment by romano1125** [comment]
Thanks for the reply but I got it figured out.  Just freaked out lol
Sent from Yahoo Mail on Android 
 
  On Sun, Jul 22, 2018 at 11:45 AM, conormcgregor99<notifications@github.com> wrote:   
2-3 things here.
Did you save the keystore file/password and the Private key safely? while creating account on Tron Scan?
Did you manually type the Private key or copy paste it?
Are you able to log in? If so,
Did you double check that the public key of your account is the same as the public key you sent the tokens from binance, letter to letter?
Does your wallet show any transactions transferring the tokens out of the wallet?
Could you provide your PUBLIC key address?
