### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by JusticeForMikeBrown** [tronscan/tronscan-frontend#403]
Hi Everyone

I own a Trezor which does not currently support TRX.

Until that happens could anything be done to improve Tronscan security such as adding 2FA?  

I think that pasting my private key into the site, or opening up the file from my laptop, isn't adequate security.  

What if the keys were stolen?

Though in that scenario if 2FA were also required then at least the wallet could not be accessed.

**Comment by Rovak** [comment]
Tronscan wallet intends to work the same as MEW and you are responsible for your own private key. 2FA wouldn't prevent anyone with the private key to make transactions.
