### ISSUE TITLE
Additional feature request for tronscan.org

### ISSUE THREAD

**Issue by CITYUPTAKE** [tronscan/tronscan-frontend#404]
Hello and thank you for your time. I wanted to request a feature that would allow you to participate directly from the search on tronscan.org. For example when you search for the token I created CITYUPTAKE (a diversified SR  ETF/fund and trade desk rewards.) It would be very convenient that when you search and info is listed like  website, address, and token holders you could participate in the token some how directly from there. It can be frustrating to go through list to find token. Once again thank you for your time

**Comment by CITYUPTAKE** [comment]
wow you guys added it thanks

**Comment by Rovak** [comment]
Added!
