### ISSUE TITLE
[Bounty] Issue a Token - status message not meaningful

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#41]
Bug Report
----
when fill out the form and click on the "Issue Token" button.. i got an error Message:
![image](https://user-images.githubusercontent.com/39301026/40404682-6739516c-5e59-11e8-9096-152705e59e4e.png)
The status/error message not meaningful, it should be classify the problem.

One Problem is .... the total supply exceeds the TRX balance:
![image](https://user-images.githubusercontent.com/39301026/40404800-f65dba9a-5e59-11e8-8c0f-471adf827d1f.png)
the default value should not exceed the TRX balance

the second Problem is the Participation start date
![image](https://user-images.githubusercontent.com/39301026/40404855-41cd45c2-5e5a-11e8-970b-fd318b24629d.png)
the default start date should be in the future

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

timestamp of the test
--------------------
23. may 2018 7am

tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

**Comment by Rovak** [comment]
First problem is fixed. Second problem is fixed in #158
