### ISSUE TITLE
token holder list have a problem 

### ISSUE THREAD

**Issue by wonban** [tronscan/tronscan-frontend#417]
token holder list doesn't show all of holder list
and
it show information of token holder's trx quantity not their own token's quantity.

for example 
i have Tarquin.
i want to see my ranking of holder.

there are 531 token holders.
but the list show about 40 token holder's address and have not next page button.
 
i can't see other's Tarquin quantity or percentage in token holder list.
it just show Tarquin holder's trx quantity or percentage.

i thing token holder list inform about their own token holder.

thank you for reading.

**Comment by conormcgregor99** [comment]
Same problem. Has been raised here since weeks. No resolution.
