### ISSUE TITLE
Add payment request format

### ISSUE THREAD

**Issue by Rovak** [tronscan/tronscan-frontend#422]
`tron:TDGmmTC7xDgQGwH4FYRGuE7SFH2MePHYeH?amount=5`

**Comment by fbsobreira** [comment]
I think we should use trx:TDGmmTC7xDgQGwH4FYRGuE7SFH2MePHYeH?amount=5

**Comment by joe-meyer** [comment]
Just for the sake of clarity would this support fractional requests as well or would that just be sent as sun?

` trx:TDGmmTC7xDgQGwH4FYRGuE7SFH2MePHYeH?amount=5`
 `sun:TDGmmTC7xDgQGwH4FYRGuE7SFH2MePHYeH?amount=5000000`

**Comment by kookiekrak** [comment]
if you guys are gonna support tokens too, prob should casesensitive, and also treat TRX as sun like joe mentions

**Comment by fbsobreira** [comment]
Token name, sun as well, we should add as parameters of the uri,
?token=CryptoChain
Or ?sun=true
Decimal should be supported if sun not presebted

**Comment by fbsobreira** [comment]
issue: #476 I have add the format @dbuarque is using in his wallet... 
Can we use the same?
