### ISSUE TITLE
Hi guys have a q reg participation

### ISSUE THREAD

**Issue by lxxmng** [tronscan/tronscan-frontend#428]
I just made a new coin with Tron - paid all, it is generated - https://tronscan.org/#/token/Seara but i dont see it in the list of coins at https://tronscan.org/#/tokens/view

it is normal? it shud be there as far as i understood?

**Comment by Rovak** [comment]
hi @lxxmng, the start date of your token is tomorrow, so tomorrow it will be visible in the list of coins

**Comment by lxxmng** [comment]
Thanks a lot, Roy! Do u have some guy in charge tp talk with your mainmet use? Im cbdo for searates.com - we are very strong in logistic- own a saas marketplace with more then 500k users - we want to do a lot with smart contracts for logistic and need a steong partner and support to buikd it properly and right.

Brgds
Alexei Shatunov

**Comment by Rovak** [comment]
We have a slack channel with developers who can help you with your questions. You can request access to the slack channel by sending a mail to tian@tron.network

**Comment by lxxmng** [comment]
Hi Roy,

it is still not there, can you check what is the problem there? thanks!

ср, 25 июл. 2018 г. в 21:07, Roy van Kaathoven <notifications@github.com>:
