### ISSUE TITLE
Feature request: please add transfer direction icon to the transfer list

### ISSUE THREAD

**Issue by aritmeester** [tronscan/tronscan-frontend#429]
Could you please add an icon to the grid which shows the direction of the transfer. In the header there are icons used for the incoming/outgoing transaction. Please add these icons to the list as well.

![tronscan-transfers](https://user-images.githubusercontent.com/644662/43226366-fa176aa8-905b-11e8-838b-1d6b659dd502.png)

**Comment by PMD3VSolution** [comment]
thank you for your request , i will discuss it with a tron employee

**Comment by cccyyc** [comment]
We will add this.
