### ISSUE TITLE
Many translation errors in Swedish!

### ISSUE THREAD

**Issue by slay0r** [tronscan/tronscan-frontend#448]
Hi. just wanted to let you know that you have tons of translation errors in swedish. One example is the one a draw a red circle around in the image, it says "Body fluids" haha.

![bild](https://user-images.githubusercontent.com/41839213/43359548-34b3bcee-92a4-11e8-9039-56027e63afd0.png)

Let me know if you need any helt translating from english to swedish, I'm a native.

**Comment by porcomus** [comment]
translation to ukrainian has errors.
![default](https://user-images.githubusercontent.com/40756073/43363560-181bdae6-9310-11e8-8882-383c67e73637.png)

**Comment by PMD3VSolution** [comment]
![image](https://user-images.githubusercontent.com/39301026/43363755-109e9b2c-930c-11e8-96b8-e34de8dbf4f9.png)

**Comment by PMD3VSolution** [comment]
i have fix it -> представники
it will be available at the next update
