### ISSUE TITLE
Transfer not showing in tronscan

### ISSUE THREAD

**Issue by Shecter24** [tronscan/tronscan-frontend#451]
Made a transfer from Binance to tron scan. Trx shows in my account but there is no record of it under transfer tab. 2 prior transfer show but not the third.

**Comment by Shecter24** [comment]
Made a 4th transfer from binance. 3rd transfer still not showing. when i search the hash get warning 
. What is going on with this? Please. Transfer shows on binance but not on tron scan. coins recieved just no record?

**Comment by Rovak** [comment]
What is the address that you are sending your coins to?

**Comment by Shecter24** [comment]
NOT SHOWING ON TRONSCAN CHAIN.

Completed    TRX   1971     2018-07-28 18:59:42

Address:  TQqxk3cy72BKzeuY4eg49j54LLuy2ooz7Y


Txid:    faf1aad73bbc417ed5d26183746fdeab5be198923fb0e3b95838d3a45ece6fc1

**Comment by Rovak** [comment]
Shows up right here https://tronscan.org/#/transaction/faf1aad73bbc417ed5d26183746fdeab5be198923fb0e3b95838d3a45ece6fc1
