### ISSUE TITLE
1000 etolar showing when viewing my TRX balance on my ledger nano s 

### ISSUE THREAD

**Issue by NickBoughton** [tronscan/tronscan-frontend#456]
Hi there, When connecting to the tronscan with my ledger nano s I can view my TRX balance correctly and send and receive TRX but now as of yesterday July 30th 1000 etolar tokens are showing up. Can you please explain why this is in my personal account ? Also, what version of Tronscan should I be using 1.1.0 (compatible with ledger) or newer version 1.1.1  Thx

**Comment by Rovak** [comment]
There are tokens being sent to random addresses on the network, so you may receive more random tokens anytime. Both 1.1.0 and 1.1.1 are OK. The 1.1.1 version fixes a copy-paste problem in MacOS

**Comment by NickBoughton** [comment]
Ok cool thx Rovak
