### ISSUE TITLE
[Bounty] Tronscan V2 - Firefox & Chrome - send TRX - enter an invalid address (00...000) -> website crashed

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#46]
Bug Report
---------
when i enter an invalid address (40x 0)
![grafik](https://user-images.githubusercontent.com/39301026/40416005-8975ce22-5e7c-11e8-9cbd-a49e0a97d124.png)

Website crashed:
![grafik](https://user-images.githubusercontent.com/39301026/40416148-d953a0b8-5e7c-11e8-8ecf-9adeadaa71ae.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

timestamp of the test
--------------------
23. may 2018 7am

tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

**Comment by ffera** [comment]
My problem :(  the problem still continues I live in the same problem waiting for the site owner to fix this issue

**Comment by ffera** [comment]
current address which will be Tron coin address
 ???
