### ISSUE TITLE
please take away from these scammers my trx

### ISSUE THREAD

**Issue by Grandmilky** [tronscan/tronscan-frontend#464]
I translated trx from binance to livecoin. The dressing was confirmed right away, and nothing was credited to the account. Support does not help. Take away from these scammers my trx and send to my address TNrcTN8jf55axehuGao7vWyDd95np5ZsB1 
https://tronscan.org/#/transaction/c15d49b2a4b0ddf5298730f7fe24a8b44d7f512420addd4364b0b9da398ee6ec
![1](https://user-images.githubusercontent.com/42027361/43572300-d64f6d72-9647-11e8-8ee0-0fbefd2cbf40.png)
![2](https://user-images.githubusercontent.com/42027361/43572305-da07a9e8-9647-11e8-908a-bb545e6cfb03.png)

![screenshot_13](https://user-images.githubusercontent.com/42027361/43573514-898a4680-964a-11e8-967f-2ed5308c7ed6.png)

**Comment by adrianlambertz** [comment]
Buddy they only build the interface to accessthe blockchain, they can't recover your tokens and stuff.
