### ISSUE TITLE
BUG TRONSCAN DESKTOP for LEDGER NANO S

### ISSUE THREAD

**Issue by TRON-FAN** [tronscan/tronscan-frontend#474]
The wallet would have to open in the fourth step and not block.

1. Open Tronscan Desktop

2.  Open Wallet
![image](https://user-images.githubusercontent.com/42068552/43647902-41b1e030-9739-11e8-91a7-2d3488884eed.png)

3. Choose Ledger
![image](https://user-images.githubusercontent.com/42068552/43647964-663c408a-9739-11e8-8242-745064445b88.png)

4. Type Password Ledger and open TRON APP

5. Is not open the wallet, because you must chang the option before wallet open
![image](https://user-images.githubusercontent.com/42068552/43648022-8ca25836-9739-11e8-80d3-46f314d7b00a.png)

6. You must click private key, keystore file or trezor
![image](https://user-images.githubusercontent.com/42068552/43648086-bae93eda-9739-11e8-9eba-b0e4681094e4.png)

7. At last you click "ledger option" and the wallet is open.

**Comment by jkatshor** [comment]
I had a similar issue but what you did to remedy did not work for me. Reinstalling tronscan fixed the issue you noted for me.
