### ISSUE TITLE
Hide tokens with 0 balance

### ISSUE THREAD

**Issue by Rovak** [tronscan/tronscan-frontend#475]

**Comment by TRON-FAN** [comment]
yes, this is a good idea :D

**Comment by Adsize** [comment]
Quote: "By the way, I have long thought about why the user is constantly shown this information about the zero balance"
https://github.com/tronscan/tronscan-frontend/issues/127#issuecomment-395017049

P.S. I hoped that the "Foundation" would objectively assess my achievements. Disappointed.
