### ISSUE TITLE
Add payment request page

### ISSUE THREAD

**Issue by Rovak** [tronscan/tronscan-frontend#476]
Some businesses are using tronscan to confirm transactions, see https://www.youtube.com/watch?v=cGrwgJFG_Oc&feature=youtu.be

It would be great to add a page where the cashier can input an amount which generates a QR code that a wallet can understand. The transaction will contain a unique id that will be looked for when waiting for a payment confirmation.

Example: https://twitter.com/Mesqueeb/status/1022774885439889408

**Comment by fbsobreira** [comment]
Dio is using a Json stringfy i.e.
{“token”:“TRX”, “address”:“TJo2xFo14Rnx9vvMSm1kRTQhVHPW4KPQ76", “amount”: “12",“data”:“One cup of tea”}

can we use the same for compatibility?
