### ISSUE TITLE
Add open wallet with facebook, twitter, peiwo etc... account

### ISSUE THREAD

**Issue by TRON-FAN** [tronscan/tronscan-frontend#478]
I hope you find a way to open a secure wallet with social media accounts.
If people want let upload there picture to tronscan profil account.
Reactivate wallet about social media account.

Import the history (example: the posts) from social media account in tronscan.org

Invite friends and you get TRONPOWER TO VOTE YOU SR FAVORITE, but Tronpower you get for invite friends will delete after 1 Month, but the earn trx for vote is yours!

**Comment by myfocus** [comment]
We will submit this feature to tronscan's product staff for evaluation.
