### ISSUE TITLE
Idea proposal Coin freeze

### ISSUE THREAD

**Issue by TRON-FAN** [tronscan/tronscan-frontend#481]
Freeze 14 days for TronPower, if you want unfreeze earlier coinburn an amount of trx to get your coins express back! every 14days the coins automatically freeze again

3 days freeze its a must only in the first 14days

——-

or you make a second option to freeze one month and your votes count double up
1 TRX COUNT AS = 2 TRONPOWER

example:
3 day freeze = 1 TRX = 1 TRONPOWER
30 days freeze = 1 TRX= 2 TRONPOWER (Supertronpower)

so if sombody change the mind and want unfreeze supertronpower, this express unfreeze costs 1% of the freeze trx amount (burn)

is only an idea, if is a good idea i dont know??? what think other tron lovers her about this?

**Comment by jkatshor** [comment]
I like the concept
