### ISSUE TITLE
add mail account, every trx adress is in tronscan.org a mailbox

### ISSUE THREAD

**Issue by TRON-FAN** [tronscan/tronscan-frontend#483]
If you want to write TRX addresses, then you can write to all personally and this costs trx (trx costs are burned or earned the receiver) the recipient consumes the advertising

**Comment by Rovak** [comment]
You mean that for example if you have the address `TYVJ8JuQ6ctzCa2u79MFmvvNQ1U2tYQEUM` that you can use a `TYVJ8JuQ6ctzCa2u79MFmvvNQ1U2tYQEUM@tronscan.org` mail account to receive messages?

**Comment by TRON-FAN** [comment]
This is also a way to receive emails from outside tronscan. For internal mails you only need the trx address.
