### ISSUE TITLE
ledger

### ISSUE THREAD

**Issue by louismartinze** [tronscan/tronscan-frontend#486]
hello, 

I can not connect to my ledger to see my tronix unfortunately,
this is the first time I install this application by trusting I ask myself questions

**Comment by louismartinze** [comment]
it's still loading to access my account

**Comment by TRON-FAN** [comment]
first open app in ledger and the click open wallet and click ledger button

**Comment by jkatshor** [comment]
I am having the same issue. I've tried following your comment instructions, Tron-Fan, but still cannot connect. I am locked out and don't feel Im getting the proper support on this topic. The tron community deleted my post for help and I am left alone to get this remedied.
