### ISSUE TITLE
Add text box: ^heritage coins^ MORE SECURITY for wallets

### ISSUE THREAD

**Issue by TRON-FAN** [tronscan/tronscan-frontend#488]
More security for accounts. If I do not log in for 2 years, the following TRX address will inherit my coins. If one of them loses his seeds or dies then Tronscan can trigger an automatic sending of the coins. You can add an Exchanger adress as an example of being registered and I personally would feel better if something happens or i lost my seeds!

Extension: Enter years yourself! Maybe also how many coins will be sent per year, so you could also inherit his children coins, but it will not be sent all at once.

**Comment by Rovak** [comment]
This is not something that Tronscan should do, but maybe a nice idea for a smart contract or a dapp
