### ISSUE TITLE
False error: Only one token per account

### ISSUE THREAD

**Issue by angusmcnab** [tronscan/tronscan-frontend#491]
Receiving an error when clicking on Create Token: "You may create only one token per account".  I have never created a token before.  Had this in 2 wallets now.
TronScan v2.02

**Comment by Rovak** [comment]
I haven't released a v2.02 version so i'm not sure if you are using the Tronscan desktop client. What is the address for which you try to create a token?

**Comment by angusmcnab** [comment]
<img width="659" alt="screen shot 2018-08-05 at 13 53 52" src="https://user-images.githubusercontent.com/31489469/43686040-0b1701d4-98b7-11e8-92dd-b3d256b2a158.png">
See attached.  Mac Desktop client

**Comment by angusmcnab** [comment]
My mistake: 2.0.2

**Comment by angusmcnab** [comment]
Ok - I think this is happening with all Tron frozen in my wallet. In one of my other wallets - containing nothing but and therefore with no tokens frozen - it lets me see the input form to Create a Token.
Can you validate this behaviour?  i.e. all Tron frozen = unable to create a token?
