### ISSUE TITLE
Can't get my Ledger to open my Tronscan wallet.

### ISSUE THREAD

**Issue by sp5433** [tronscan/tronscan-frontend#492]
The problem is that I didn't use the ledger to begin with. I got my paper keys and then I used the ledger to open the wallet. But once I closed it, the Ledger would not open it again. I'm thinking I need to start all over again. What do you suggest?

**Comment by jkatshor** [comment]
I just had a similar issue. I tried at least 10-15 different approaches to remedy. What ended up working for me was to uninstall and reinstall tronscan. Truly hope you get this figured out and good luck.
