### ISSUE TITLE
[Bounty] Tronscan V2 - send custom Token to an other wallet -> Not working

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#50]
Bug Report
-----------
i have buy an custom token and try to send this token to an other wallet:
![grafik](https://user-images.githubusercontent.com/39301026/40417920-4234e2fa-5e81-11e8-876b-b295b79c414f.png)

i select the custom token, an trx address and the amount:
![grafik](https://user-images.githubusercontent.com/39301026/40417950-5b48bafa-5e81-11e8-87ef-0b8fc85a760b.png)

![grafik](https://user-images.githubusercontent.com/39301026/40418020-89633780-5e81-11e8-8b80-06923504db31.png)

confirmation:
![grafik](https://user-images.githubusercontent.com/39301026/40418078-a9f9af88-5e81-11e8-80dc-1abcdf05da10.png)

but i cant found the transaction in the protocol:
![grafik](https://user-images.githubusercontent.com/39301026/40418144-dca6d2bc-5e81-11e8-837b-ad9fcd985437.png)

and when i reopen the "Sent Token Dialog"... all Tokens are availible
![grafik](https://user-images.githubusercontent.com/39301026/40418185-f3d02254-5e81-11e8-8566-5da7e647ccdf.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

timestamp of the test
--------------------
23. may 2018 11:30am

tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

**Comment by Rovak** [comment]
fixed
