### ISSUE TITLE
Security on Tronscan

### ISSUE THREAD

**Issue by leek21** [tronscan/tronscan-frontend#500]
If someone gets your private key they can easily take all your coins.

You need second/third level security.  Something like Google Authenticator to withdraw funds.
Binance uses Google Authenticator but also sends you an e-mail to confirm the withdraw of coins.

Way, way too easy to withdraw money on Tronscan.  Please add more checks before allowing someone to withdraw their funds.

**Comment by Rovak** [comment]
Working as intended
