### ISSUE TITLE
[Bounty] Errors on the page tronscan.org/#/wallet/new

### ISSUE THREAD

**Issue by Adsize** [tronscan/tronscan-frontend#51]
This bug in browsers
Google Chrome 66.0.3359.181
Opera 52.0.2871.99
In the browser Firefox Quantum 57.0.4 this error is missing
When you change the page scale, the frame borders disappear

![00011](https://user-images.githubusercontent.com/39515013/40425969-86f94f22-5ea2-11e8-8dee-777cfdf1970e.jpg)

![00012](https://user-images.githubusercontent.com/39515013/40426638-407c37ec-5ea4-11e8-8868-f6199217f8f6.jpg)

![00013](https://user-images.githubusercontent.com/39515013/40427445-6c48bf92-5ea6-11e8-821d-85fae63fc3c0.jpg)

This bug in browsers
Google Chrome 66.0.3359.181
Opera 52.0.2871.99
Firefox Quantum 57.0.4 
When you select an empty field, the left mouse button displays a hidden inscription "too short"

![00014](https://user-images.githubusercontent.com/39515013/40427693-1cbb41c4-5ea7-11e8-9b1c-ab79af8797c3.jpg)

Voluntary donation TRX: 0x00cb09ec70354ab8b7c328da2c0e5e4629f411da

**Comment by Rovak** [comment]
Optimizing the website for different zoom levels won't be supported
