### ISSUE TITLE
Layout breaks on markets page

### ISSUE THREAD

**Issue by kyleglen** [tronscan/tronscan-frontend#511]
The layout on [this page](https://tronscan.org/#/markets) breaks when you resize your browser. 
<img width="815" alt="screen shot 2018-08-09 at 6 34 53 pm" src="https://user-images.githubusercontent.com/42257152/43934289-8816d7dc-9c03-11e8-84e9-f0653a884cd6.png">

**Comment by kyleglen** [comment]
This issue occurs on every page that uses these tables.

**Comment by PMD3VSolution** [comment]
which browser do you use? do you call the website from a tablet?

**Comment by kyleglen** [comment]
I am using Chrome on a mac
