### ISSUE TITLE
Wrong Translate German Words "Werkzeuge" and "Brieftasche"

### ISSUE THREAD

**Issue by TRON-FAN** [tronscan/tronscan-frontend#512]
Werkzeuge="Tools" better use englisch words tools

Brieftasche="Wallet öffnen" or if you want german words = "Geldbörse öffnen"
i like wallet open but if you want coorect german word is better GELDBÖRSE ÖFFNEN
Brieftasche means more open letterbag from postman

![image](https://user-images.githubusercontent.com/42068552/43950684-46f45980-9c91-11e8-9378-52bfffcee5ef.png)

**Comment by PMD3VSolution** [comment]
It makes no sense to translate all proper names!

**Comment by TRON-FAN** [comment]
hey mein freund :) würde doch seriöser aussehen :) es wurde schon angepasst und es sieht doch besser aus oder nicht?

**Comment by PMD3VSolution** [comment]
Hallo =) ich habe das Thema noch einmal abgeklärt , Tools werden wir ändern ;) Wallet würden wir gerne so lassen.

**Comment by PMD3VSolution** [comment]
fixed in #517
