### ISSUE TITLE
Does not look nice in german website... abbreviate text QUICK LINKS

### ISSUE THREAD

**Issue by TRON-FAN** [tronscan/tronscan-frontend#514]
Change **"Für einen Super Repräsentant abstimmen"** = **"Super Repräsentanten wählen"** looks better and everyone understands what is meant

![image](https://user-images.githubusercontent.com/42068552/43952964-c7e9ba16-9c97-11e8-83f7-b4554502ac39.png)

**Comment by PMD3VSolution** [comment]
Yeah, perfect, thanks for the improvement.

**Comment by PMD3VSolution** [comment]
fixed in #517
