### ISSUE TITLE
[Bounty] Issues with creating Tron Token

### ISSUE THREAD

**Issue by zionopia** [tronscan/tronscan-frontend#52]
1. Exchange Rate
    You can`t input a TRX or Token Amount with decimal. As example : TRX Amount : 1 / Token Amount : 0.1

2.  Participation
   During the process of creating a Token the Start Date seem to take a specific time. It seems that this Start Date is syncing with the actual date at the desktop, where this coin is created, so after changing the start date to a time after the PC Desktop time, issuing a Token was available. You should state at what time the start date is actually beginning (example EST time, etc.) and inform the user what the start date actually means.

3. Sending Tokens.
 After setting up a Fotocoin Token with 1:1 ratio, I was trying to send this to another account.
When sending in the form only 1 Fotocoin, I was actually sending 10,000,000 Fotocoins instead.
This seems to be a real bug. You can test it also with other created tokens.

![image](https://user-images.githubusercontent.com/2923960/40464317-86698df2-5f55-11e8-95db-71dd3624d547.png)

**Comment by Rovak** [comment]
Fixed
