### ISSUE TITLE
Tronscan - display USD values - suggestion

### ISSUE THREAD

**Issue by Arky128** [tronscan/tronscan-frontend#524]
Hi,
Really like the Tronscan wallet - it is absolutely loaded with features.  

However, I was thinking it would be nice on the wallet account page to be able to see USD values of Tron Power.  Currently, you can put your cursor over the Balance and see the USD value (which is nice) but I think it would be cool to get that same readout when you put your cursor over Tron Power.

Perhaps I am missing something, but I don't believe there is a way to see total USD.  I frequently tally what my crypto holdings are doing related to USD and with the Tronscan wallet,  I don't believe there is a quick way to get a total USD value....

**Comment by Rovak** [comment]
Done, will be deployed soon

**Comment by Arky128** [comment]
Thanks!!!
