### ISSUE TITLE
[Bounty] Input field for Private Key: type="email"

### ISSUE THREAD

**Issue by Adsize** [tronscan/tronscan-frontend#53]
Input field for Private Key: type="email"
It is proposed to introduce email.
input class="form-control" placeholder="" type="email"

In the browser Firefox Quantum 57.0.4

![00015](https://user-images.githubusercontent.com/39515013/40482969-18cc1bc0-5f5f-11e8-84fa-3d777c7e80a4.jpg)

In the browser Opera 52.0.2871.99

![00016](https://user-images.githubusercontent.com/39515013/40482991-2b4ff000-5f5f-11e8-8881-bc2a3c2990f8.jpg)

Voluntary donation TRX: 0x00cb09ec70354ab8b7c328da2c0e5e4629f411da

**Comment by PMD3VSolution** [comment]
Good work ;) nice bug!

**Comment by Adsize** [comment]
Hi, PMD3VSolution! Thanks for the feedback. I myself have long wanted to comment on your research.
In any case, all we do now is an interesting experience.

**Comment by Rovak** [comment]
@PMD3VSolution i also want to thank you for the test results you have submitted, really valuable feedback. Due to a lack of time i'm slow to respond but i'll be going through all the issues soon.

**Comment by Adsize** [comment]
:)

![00017](https://user-images.githubusercontent.com/39515013/40497956-439a09da-5f86-11e8-9a7f-cd0e9b9b105a.png)

**Comment by PMD3VSolution** [comment]
As an investor it is important to me to support the project as best as possible.  I am very convinced of the idea and will continue to do so!  We all share the same goal and are happy to work on an idea that will change the world.  Thanks for your great work!

**Comment by Rovak** [comment]
Fixed
