### ISSUE TITLE
can't send trx token to binance

### ISSUE THREAD

**Issue by Brian369** [tronscan/tronscan-frontend#530]
HI.
Here my problem:
First, I cannot paste the TRX deposit address, it does nothing. So I have to enter each digit manually.
Second, once done, after I click send and then click on my ledger to confirm, a red message appears on the "send screen" saying  something went wrong and then go back to the "send screen".
I have reinstalled Tronscan from GitHub and I get the same result.

**Comment by caroldorrell** [comment]
Hello, I see this thread is closed but I don't see a solution.  Is there one?
