### ISSUE TITLE
Create new token error "You may create only one token per account"

### ISSUE THREAD

**Issue by adrianlambertz** [tronscan/tronscan-frontend#540]
I can't create a token, i receive the following message: "You may create only one token per account".

But I never created a token before. The only thing i did was checking out the form to create a token just to check the options i have.

I never submitted the form und never created a token.

This happens on tronscan.org and in the desktop app.

**Comment by Killawasper** [comment]
I have the same issue. I have not created a token and for some reason this thing does not even let me get to the form. Any feedback will be welcome !
