### ISSUE TITLE
Sign in problem

### ISSUE THREAD

**Issue by Tadlo1** [tronscan/tronscan-frontend#561]
I have not been able to paste my private key into the sign in box, too access my wallet. This has been since approximately 04:00 GMT as I live UK.

**Comment by CurtisAAF** [comment]
I'm having this same issue.  Have you been helped yet?

**Comment by Tadlo1** [comment]
No response as yet. only way I can get around it is too, change orientation too landscape on my phone and pull the sign in box as far down as possible. From the cursor is slightly visible, you can just about tap it to bring up the paste/copy menu.

Hope this helps
