### ISSUE TITLE
On the address page, 'Tron power' and 'total_balance' are suddenly displayed as zero.

### ISSUE THREAD

**Issue by AhnSinYong** [tronscan/tronscan-frontend#570]
On the address page, 'Tron power' and 'total_balance' are suddenly displayed as zero.
![image](https://user-images.githubusercontent.com/2742452/44589550-cfccd800-a7f3-11e8-85a8-384a07871297.png)

**Comment by Rovak** [comment]
Fixed in https://github.com/tronscan/tronscan-frontend/commit/ae76504a8b6aa4794fdf90b27a35cd391a393dd7, will be deployed soon
