### ISSUE TITLE
"Create Token"

### ISSUE THREAD

**Issue by B3NzoNa** [tronscan/tronscan-frontend#574]
When I click on "Create Token" I recieve a message, "You may create only one Token per account
![create](https://user-images.githubusercontent.com/42702351/44621650-d6e0fe00-a866-11e8-888a-133e752e46c9.PNG)
" I have never made a Token. Thanks

**Comment by Rovak** [comment]
Is this in the web or desktop version?

**Comment by B3NzoNa** [comment]
I'm new to this but it looks like it opens an HTML page.
![create2](https://user-images.githubusercontent.com/42702351/44622128-eadd2d80-a86f-11e8-8412-cf9f11edf427.PNG)
