### ISSUE TITLE
[Bounty] Tronscan V2 - Token Creation - negative values can be defined

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#58]
Bug Report
----------
negative values can be entered. this makes sense for both "Total Supply" and "Frozen Supply". the user should not be able to enter negative values.

![image](https://user-images.githubusercontent.com/39301026/40513540-67e2aa5c-5fa6-11e8-8caa-89de6ee3ffaf.png)

![image](https://user-images.githubusercontent.com/39301026/40513565-75ffd4ca-5fa6-11e8-8cbf-597063a08b3d.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

timestamp of the test
--------------------
24. may 2018 10pm (UTC+1)

tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

**Comment by Rovak** [comment]
Fixed
