### ISSUE TITLE
Tronscan wallet not syncronizing

### ISSUE THREAD

**Issue by zahyar** [tronscan/tronscan-frontend#588]

**Comment by zahyar** [comment]
Tronscan wallet is not syncronizing with the network...And i can´t do any transactions . When i  put the recipient adress it tells me not valid with any adress...please help!!!

**Comment by Rovak** [comment]
To which address are you trying to send?

**Comment by zahyar** [comment]
i try to move my trx to binance.when right click to paste the adress nothing happened.the copy/paste command is not working ..so i try mannualy and still the same answer:not a valid adress...

**Comment by zahyar** [comment]
i´m connecting from a ledger nanos
