### ISSUE TITLE
Wallet Lockout

### ISSUE THREAD

**Issue by CurtisAAF** [tronscan/tronscan-frontend#590]
Hello,

 I just created my wallet this morning and now I can't get in.  Who can I get to help me with this problem. 

Thanks,

**Comment by Rovak** [comment]
Hi, what do you mean with "locked out". Do you still have the private key or keystore file?

**Comment by CurtisAAF** [comment]
Rovak,

Thanks for responding. I have a long code, which I do believe is the private key, but when I enter it in when opening my wallet. It does not allow the sign in button to appear so I can't sign in. I didn't get a keystore file when I set it up this morning.



This Information About Brokerage Services disclosure is required to be shared with you if you are a potential client - Texas Real Estate Commission Information About Brokerage Services <http://%20https//drive.google.com/open?id=0BwMpzqvBq9x1TDZZRmw3djdRdTg>

Curtis Davis
Owner | Licensed Realtor

Aggieland Apartment Finders
 | Property Management
 | Home Sales

123 Walton Dr, College Station, TX 77840
Office (979) 693-4900<tel:%28979%29%20693-4900> Cell (979)-218-7612

**DISCLAIMER**
The information contained in this e-mail and any attachments are confidential property of the sender. The information is intended only for the use of the person to whom it was addressed. Any other interception, copying, accessing, or disclosure of this message is prohibited. If you have received this e-mail in error, please immediately notify the sender and purge the message you received.  Although every effort is made to provide accurate information, sender and Aggieland Apartment Finders accepts no responsibility or liability for the content of this message or for the consequences of any actions taken on the basis of the information provided. Additionally, any terms, rates, materials, etc. are subject to change at any time as determined by Aggieland Apartment Finders.


________________________________
