### ISSUE TITLE
Impossible to copy/paste any adress to send some funds

### ISSUE THREAD

**Issue by zahyar** [tronscan/tronscan-frontend#595]
Hi...i try to send some coins outside tronscan wallet and i can't copy paste any receiver adress with TRX and even the other tokens.When i do it manually it continue to tell me "please put a valid adress"...
I don't understand where is the problem...

**Comment by ssh5638** [comment]
TDFE9Z2qGgeSksbaFrfCeoXeWjWzzQsDmG

**Comment by ssh5638** [comment]
TDFE9Z2qGgeSksbaFrfCeoXeWjWzzQsDmG
