### ISSUE TITLE
Presently, there is no way to discover what the fees are for a transaction

### ISSUE THREAD

**Issue by dooglio** [tronscan/tronscan-frontend#598]
Hello! I'm a dev with Exodus Movement, and we use your API to get information about transactions and addresses on the Tron blockchain for our desktop wallet.

In the event of going over the free bandwidth allocation for an account, there is no way to detect what the fee is that the network automatically assigns. 

For example, this tx here:
https://api.tronscan.org/api/grpc/full/gettransactionbyid/c4fea3a76919a49fc5251c10f3d7fd449041be407876273205f145869ca429e7

The Tron devs say they can discover the fee via this RPC call:
```
curl -X POST  http://127.0.0.1:8091/walletsolidity/gettransactioninfobyid -d '{"value" : "c4fea3a76919a49fc5251c10f3d7fd449041be407876273205f145869ca429e7"}'
```

But the Tronscan API call does not give the fee in the return set. Obviously, we can't make use of the RPC call because we don't require our customers to install a full node.

Please change the API so we can determine what the actual fee is.

**Comment by Rovak** [comment]
https://github.com/tronscan/tronscan-api/issues/44

**Comment by dooglio** [comment]
Thank you!
