### ISSUE TITLE
[Bounty] Tronscan V2 - search function faulty - brings up an error if 2 values start with the same initial letters

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#6]
Bug Report
------------

test preparation
--------------
+create 2 testtoken with the same initial letters
+clear the console

![image](https://user-images.githubusercontent.com/39301026/40111752-1cef3dce-5904-11e8-8b4b-9c027670de6b.png)

![image](https://user-images.githubusercontent.com/39301026/40108836-5a9cf09c-58fc-11e8-9659-f96319f16422.png)

testprocedure
-------------------
enter the search term and click on the search button:
![image](https://user-images.githubusercontent.com/39301026/40111841-5f6a3dde-5904-11e8-9399-c137cc76ec45.png)

the last value created is displayed and the following error appears in the console.
![image](https://user-images.githubusercontent.com/39301026/40111877-7e0d5dfc-5904-11e8-96cb-a9ade37383ab.png)

Error:
![image](https://user-images.githubusercontent.com/39301026/40111962-c4cacce8-5904-11e8-8d2f-a4ef192226c4.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

timestamp of the test
--------------------
16. may 2018 1:30pm

tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

**Comment by Rovak** [comment]
The error isn't nice but intended behavior, the search just checks several endpoints for results and will redirect the user to the first endpoint that returns a result.
