### ISSUE TITLE
Suggestion:-  Allow users to freeze TRX for longer periods in exchange for TRX dividends.

### ISSUE THREAD

**Issue by OneCoinWillRuleThemAllTRX** [tronscan/tronscan-frontend#602]
Allow the community to support TRX buy holding on to their TRX for longer periods of time in exchange for agreed TRX dividends by percentage of TRX held.

For example if you have 1000 TRX and freeze for:-

6 months - 1% = 10 TRX dividends
12 months - 2.5% = 25 TRX dividends
24 months - 6% = 60 TRX

Rather than set a set % you could tie this into a percentage of how much TRX has gained in the period.  If there is no gain then no dividends are awarded (given that long term investors want to support Tron they may not mind if nothing is distributed if within the frozen period the price drops.  They could be given an additional % if they opt to freeze again and continue their support.

**Comment by dbriggsie** [comment]
Probably more a sugguestion for TronProtocol github, not Tronscan.
