### ISSUE TITLE
Tronscan does not ask the user to confirm their password for a second time.

### ISSUE THREAD

**Issue by OneCoinWillRuleThemAllTRX** [tronscan/tronscan-frontend#603]
It's possible users will type in an incorrect letter or number if there isn't a second confirmation of the password entered.

![password](https://user-images.githubusercontent.com/42871282/45189161-92bf0780-b22f-11e8-84cd-2c46a863aa4c.png)

**Comment by fassassi** [comment]
Completely concur. I am actually struggling to open my wallet because I suspect that my password may have been typed incorrectly when saving it.  I also, unfortunately, do not have my private key, but just my keyfile.
