### ISSUE TITLE
Suggestion:-  Can the value of frozen TRX still be present in this screen?

### ISSUE THREAD

**Issue by OneCoinWillRuleThemAllTRX** [tronscan/tronscan-frontend#607]
Most users would appreciate if the value of their frozen TRX is still displayed in the account screen?  At the moment it does not show a value.

![image](https://user-images.githubusercontent.com/42871282/45209306-8b761900-b284-11e8-97b9-ea859966f2d8.png)

**Comment by cf777** [comment]
> Most users would appreciate if the value of their frozen TRX is still displayed in the account screen? At the moment it does not show a value.
> 
> ![image](https://user-images.githubusercontent.com/42871282/45209306-8b761900-b284-11e8-97b9-ea859966f2d8.png)

Thanks for your advice. We will discuss your requirement. The balance may be divided into two categories, some are available balance and some are unavailable. Of course there may be a total balance displayed. How do you like this?

**Comment by OneCoinWillRuleThemAllTRX** [comment]
> > Most users would appreciate if the value of their frozen TRX is still displayed in the account screen? At the moment it does not show a value.
> > ![image](https://user-images.githubusercontent.com/42871282/45209306-8b761900-b284-11e8-97b9-ea859966f2d8.png)
> 
> Thanks for your advice. We will discuss your requirement. The balance may be divided into two categories, some are available balance and some are unavailable. Of course there may be a total balance displayed. How do you like this?

I like this idea of having available balance / unavailable balance and total balance.  Ideally the user should be able to specify what currency they would like to see too.  E.g.  BTC, USD, GBP, EUR (the main currencies you would expect to see for valuation of a portfolio)
