### ISSUE TITLE
Inconsistent value of TRX displayed by wallet and in account screen

### ISSUE THREAD

**Issue by OneCoinWillRuleThemAllTRX** [tronscan/tronscan-frontend#608]
In the wallet the display value for TRX value held is shown as 0.005 TRX but in the account screen it is displayed as 0.00475 TRX.

![issue1](https://user-images.githubusercontent.com/42871282/45243062-58667080-b2ea-11e8-8ce3-68e29bd9309a.png)

![issue2](https://user-images.githubusercontent.com/42871282/45243069-5dc3bb00-b2ea-11e8-8c79-7f7fe3a311c9.png)

**Comment by cf777** [comment]
Thanks, we will fix this bug
