### ISSUE TITLE
[Suggestion] Count of how many addresses were active in the past 24 Hrs.

### ISSUE THREAD

**Issue by dbriggsie** [tronscan/tronscan-frontend#609]
Could you please add a Count of how many addresses were active in the past 24 Hrs.
Activity could be of sending 1 transaction of any type. This can be added to Statistics Page on Tronscan

This would help Tron be listed on CMC when sorting by 24hr activity
https://pbs.twimg.com/media/DmYGzo8U4AAYAce.jpg

**Comment by cf777** [comment]
> Could you please add a Count of how many addresses were active in the past 24 Hrs.
> Activity could be of sending 1 transaction of any type. This can be added to Statistics Page on Tronscan
> 
> This would help Tron be listed on CMC when sorting by 24hr activity
> https://pbs.twimg.com/media/DmYGzo8U4AAYAce.jpg

Great idea. We will consider your suggestion carefully. In my opinion I think the information of the active addresses is useful. Thanks a lot.
