### ISSUE TITLE
[Bounty] Tronscan V2 - Firefox - Token Freeze - input of letters 

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#61]
Bug Report 
----------

In Firefox the input of letters is possible.
![image](https://user-images.githubusercontent.com/39301026/40515637-e4e37f48-5fad-11e8-91f4-b3de9254dac1.png)

if you use google chrome this is not possible
![image](https://user-images.githubusercontent.com/39301026/40515680-fe04b33e-5fad-11e8-9a32-a2bad0bf13f6.png)

Issue Reproducible: YES
-------------------------

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
24. may 2018 11:20pm (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

**Comment by zk19862018** [comment]
because firefox does not support <input type='number'>
