### ISSUE TITLE
Ballance zero Tronwatch

### ISSUE THREAD

**Issue by Voljanin** [tronscan/tronscan-frontend#613]
Good afternoon. I transferred the transaction from the Bittrex exchange to my wallet, and in the purse 0. What should I do?
TxId00281dec989bb270ce67ebbd54430998c63ecb1a6ecce7cc3ceab5384395bb20
Date2018/09/08 10:57:11
SymbolTRX
AddressTXvzoJcMwVNZYBQhHK9csVUecKVEbt59HJ
Quantity247.99700000
StatusCompleted
AuthorizedYes
Confirmations0
And when reinstalling the purse using private kei I get another address TDS9y4nv7GHHBnXdazoJy4mRq5GLZtCf5y
![kohelek](https://user-images.githubusercontent.com/16429234/45257007-58787600-b3a7-11e8-8a57-c13e7f827254.JPG)

**Comment by Rovak** [comment]
This issue is related to https://github.com/TronWatch/Desktop-Wallet, please direct your question to that repository
