### ISSUE TITLE
create a coin

### ISSUE THREAD

**Issue by tyranosaurusrex** [tronscan/tronscan-frontend#617]
when I go to create a token it tells me. "you may create only one token per account." but I have never created a token before and I have more than 1000 trx 

my address is: TJujNQ2wxj8fGdg21ycpQDeM4P94DnnZxt
chris maher

**Comment by TRONDApp** [comment]
we checked again, both the API and front page works well. We can't find recurrent your problem. Can you provide screenshot or video

**Comment by dbriggsie** [comment]
Possibly sign out and make sure when your signed in, you are still logged when on that page.
