### ISSUE TITLE
It doesn't appear there is a timeout set for tronscan after you've logged into the wallet with your private key

### ISSUE THREAD

**Issue by OneCoinWillRuleThemAllTRX** [tronscan/tronscan-frontend#618]
Possible security issue for users as it doesn't appear there is a timeout set after you have logged into your wallet with your private key.

**Comment by cf777** [comment]
> Possible security issue for users as it doesn't appear there is a timeout set after you have logged into your wallet with your private key.

Thanks for your support. We will do some research about the timeout set for tronscan-wallet
