### ISSUE TITLE
[Bounty] Cross-browser compatibility

### ISSUE THREAD

**Issue by Adsize** [tronscan/tronscan-frontend#62]
In the browser Firefox Quantum 57.0.4

![00021](https://user-images.githubusercontent.com/39515013/40531527-502a9d34-6005-11e8-92bf-d0c896965eff.jpg)

In the browser Google Chrome 66.0.3359.181

![00022](https://user-images.githubusercontent.com/39515013/40531642-9a62ce94-6005-11e8-878a-8d35d8e52e60.jpg)

I understand that now the width of this message is not important :) But ... sending coins in the browser Firefox Quantum 57.0.4

![00023](https://user-images.githubusercontent.com/39515013/40533153-7513dd22-600a-11e8-91e8-2104dede1983.jpg)

Voluntary donation TRX: 0x00cb09ec70354ab8b7c328da2c0e5e4629f411da

**Comment by Jacob8765** [comment]
It looks fine on Firefox 60.0.1

**Comment by Adsize** [comment]
Thank you for noticing, you are absolutely right! Such remarks are our task.
Right now it looks like:
In the browser Firefox Quantum 57.0.4 and Firefox 43.0.1 

![00026](https://user-images.githubusercontent.com/39515013/40559657-2dd8befe-6060-11e8-9762-40b909bf18dc.jpg)

But we also get a green circle like this:

![00027](https://user-images.githubusercontent.com/39515013/40559821-aff8837e-6060-11e8-990d-6d71567fdd5a.jpg)

I am sure, if necessary, this will be corrected.

**Comment by Adsize** [comment]
Speaking of a familiar warning:

![00028](https://user-images.githubusercontent.com/39515013/40586220-2b274536-61c8-11e8-8bea-1a8396c1fe6a.jpg)

**Comment by Rovak** [comment]
It is based on the Sweet Alert (https://sweetalert.js.org/guides/) library
