### ISSUE TITLE
Bug:-  Don't seem to be able to freeze decimal amount TRX after multiple attempts

### ISSUE THREAD

**Issue by OneCoinWillRuleThemAllTRX** [tronscan/tronscan-frontend#623]
Bug:-  Don't seem to be able to freeze decimal amount TRX after multiple attempts

![image](https://user-images.githubusercontent.com/42871282/45557346-4b3f0980-b835-11e8-8fea-1069cd6716d0.png)

![image](https://user-images.githubusercontent.com/42871282/45557365-56923500-b835-11e8-884c-f30be1151fbc.png)

**Comment by Rovak** [comment]
It is not possible not freeze fractions of TRX. working as intended, but i'll keep this issue open to make the error more clear
