### ISSUE TITLE
Enhancement: Show name of asset transferred in the "Transactions" panel.

### ISSUE THREAD

**Issue by Kyle-Kidd** [tronscan/tronscan-frontend#629]

**Comment by Kyle-Kidd** [comment]
As well as amount and maybe a portion of the to/from address.

**Comment by cf777** [comment]
Actually on the detail page of any transaction it would show the amount and more information. How do you like it?

**Comment by Kyle-Kidd** [comment]
I see it's now on the main account page.  Looks good.
