### ISSUE TITLE
tronscan wallet doesn't work

### ISSUE THREAD

**Issue by dragonshl** [tronscan/tronscan-frontend#63]
I can't send trx to the tronscan wallet, and registered in tron still doesn't support transfer of trx between acct and tronscan. what a pity!

**Comment by PMD3VSolution** [comment]
Currently Tron trx is an etherium Erc20 token an not compatible with tronscan! Tronscan is currently in phase test network. It is not possible to send an erc 20 token to an tronscan address. Please read and follow the notes on tronscran and tron.network

**Comment by PMD3VSolution** [comment]
It is not an issue, please close the case
