### ISSUE TITLE
Trons

### ISSUE THREAD

**Issue by patrickpattie** [tronscan/tronscan-frontend#630]
Dear GitHub,

Here my adres of my TRON (TRX) Coins

TWLrC3eh4sfGENkRv1Vc3PKpfwQXsGsfA2

I've had 25.690 TRONS in total

I send 15.100 to another adres. So I've now 10.590 left on this TRON account!

Today I looked and there are NO TRONS power left?

How is that possible is my question?

With regards

Patrick

**Comment by cf777** [comment]
The balance in your account means how many TRX you have at present. The TRON power is just the number you can vote for representative.
