### ISSUE TITLE
Typo in creating token English Copy: "Frozen Suppluy"

### ISSUE THREAD

**Issue by JamesHutchison** [tronscan/tronscan-frontend#631]
There is a typo in the English translation when creating a new token and setting the frozen supply. It is misspelled as "suppluy" in the title and also where it indicates the total frozen supply. It is spelled correctly in the description. See attached screenshot.
![frozen_suppluy](https://user-images.githubusercontent.com/6948206/45658859-5cdb1800-baa6-11e8-94c4-c0c74246a695.png)

**Comment by cf777** [comment]
> There is a typo in the English translation when creating a new token and setting the frozen supply. It is misspelled as "suppluy" in the title and also where it indicates the total frozen supply. It is spelled correctly in the description. See attached screenshot.
> ![frozen_suppluy](https://user-images.githubusercontent.com/6948206/45658859-5cdb1800-baa6-11e8-94c4-c0c74246a695.png)

Thanks for your reminding. We have revised it.

**Comment by JamesHutchison** [comment]
Looks good. Thanks for fixing!
