### ISSUE TITLE
Votes

### ISSUE THREAD

**Issue by Tadlo1** [tronscan/tronscan-frontend#633]
Can no longer see the number of votes from IPhone, since update. Also virtually impossible to paste personal key in sign in box too login to wallet, since update

**Comment by cf777** [comment]
> Can no longer see the number of votes from IPhone, since update. Also virtually impossible to paste personal key in sign in box too login to wallet, since update

Thanks for your reminding. We are going to optimize the displayed effect on mobile phone. Sorry for the inconveniences.

**Comment by Tadlo1** [comment]
Thank you

Kind Regards 
Mark

**Comment by chuckyloco** [comment]
Still can not open Vote .. when i want to go to vote and press on the button it wont open whats up with that??

**Comment by paulmeade7** [comment]
What is going on with Tron. I've been a major believer in TRX and have been a HODL. I've been experiencing this for the last day and a half. I can't do anything on Tronscan now. This is super frustrating since I can't seem to get any answer from Tronscan to fix the situation.
