### ISSUE TITLE
Sorting token balances page

### ISSUE THREAD

**Issue by FerruFx** [tronscan/tronscan-frontend#635]
Hey, Would be great to have the possibility to sort by column (name, balance) in our token balances page. Thank you. Keep up the great work!

**Comment by FerruFx** [comment]
Now the sorting is per ID ... which is making even worse to find a specific token in a long list. Would be really great to have at least a sorting option alphabetical.

**Comment by blmatthews** [comment]
I'm still seeing sorting by balance so maybe it's not rolled out everywhere, but it doesn't matter, because I agree, sorting by ID is at least as useless as sorting by balance. If there's only one hard-coded sort, alphabetical by token name seems the only one that makes sense.

**Comment by blmatthews** [comment]
Why was this closed? Is it not going to be fixed?

**Comment by blmatthews** [comment]
Same question as my previous comment.
