### ISSUE TITLE
get test trx

### ISSUE THREAD

**Issue by account2033** [tronscan/tronscan-frontend#637]
How can i get test trx?

**Comment by wuno** [comment]
You are supposed to get test TRX from, 

[https://test.tronscan.org/account](https://test.tronscan.org/account)

When we try to get test TRX we get the same error message stating something about not being able to obtain test TRX at this time and we should contact support. 

What is the solution to this and is it being worked on? I have not found any other way to obtain test TRX to test my D-Apps on the test network.
