### ISSUE TITLE
Tapos Check Error

### ISSUE THREAD

**Issue by ppsdang** [tronscan/tronscan-frontend#638]
I am getting Tapos Check Error while requesting for testnet Tron coins from https://test.tronscan.org/account

**Comment by Rovak** [comment]
This is a known issue, will be fixed soon...

**Comment by rcrofoot1** [comment]
I am also getting a "Tapos Check Error" when trying to spend from the TronWatch desktop wallet (running windows 7)...When will this be fixed???
Thanks, Rick

**Comment by Rovak** [comment]
tronwatch desktop is no longer maintained, any questions can be asked there https://github.com/TronWatch/Desktop-Wallet
