### ISSUE TITLE
%ATM  Token Bug

### ISSUE THREAD

**Issue by GamerOfChains** [tronscan/tronscan-frontend#640]
when looking at other tokens you can click on them and see additional information. %ATM after being clicked goes to a blank tronscan page that cant be backed out of.
The token was created on a mobile platform offered on the tron official site. The token is in use and being traded but the information and trade history can't be viewed like the others.
Any help would be great, thank you!

**Comment by cccyyc** [comment]
hi，could you provide the issue address of the token ?
That will help us find the reason quickly.

**Comment by GamerOfChains** [comment]
TEqXSx3cZ6xqqPuxa1hiyzWjseV3odNYNc

**Comment by GamerOfChains** [comment]
Thank you for taking time to have a look. Let me know if there is anything
else I can do to help

**Comment by cccyyc** [comment]
We are checking that.

**Comment by cccyyc** [comment]
Have you ever opened it successfully before?

**Comment by GamerOfChains** [comment]
No the information page on tronscan, no
