### ISSUE TITLE
Transaction error

### ISSUE THREAD

**Issue by afatsumakca** [tronscan/tronscan-frontend#643]
Im stil waiting my TRX transaction but this transaction has not done yet for 20 hours :(
I only see tuloading_transaction on this page. Please fix and send my tokens.

https://tronscan.org/#/transaction/b370c584b4b0323d4d67fbe5198eca5391d0cfa4953c20db79c1661e80ee5581

**Comment by Rovak** [comment]
This is an exchange issue, please contact the exchange from which you are trying to withdraw trx
