### ISSUE TITLE
I cant login into my Tronscan wallet (Desktop Version)

### ISSUE THREAD

**Issue by chevkevs** [tronscan/tronscan-frontend#651]
Dear Tron,

I am a proud user and hodler of tron but at the moment i can't login into my desktop wallet. I can login into tronscan web but if i use the desktop version it says "No wallet to open when i enter my key" if i enter the same key on the web it is no problem.

My account adress is: TPVkcFYTEi9Dia45AveiTcaYoaU9ux7xC7 (chevkevs)

I am rewarding adresses that are making transactions and blocks with coins. maybe u guys saw this as spam? i dont know but i want to use the desktop version because this is safer for me.

I hope u guys can find the problem and help me out

![portomonnee](https://user-images.githubusercontent.com/43635964/46133320-7f0c2d00-c240-11e8-8130-a323abacd48e.png)

**Comment by kehaarhraka** [comment]
TronScan wallet seems to be down at this point. Will not load.
