### ISSUE TITLE
Frozen trx

### ISSUE THREAD

**Issue by brett20** [tronscan/tronscan-frontend#653]
I have had trx frozen on tronscan.org and today I am not able to unfreeze or send any trx out of my account. My frozen trx have passed their expiration date and that is the only thing It’s says when I click to unfreeze it. Any help would be appreciated!

**Comment by paulmeade7** [comment]
Same exact thing with mine. I asked one of the questions before yours. My Loading Super Representatives section just keeps trying to load and it will not show any Total Votes in that section too. Can't unfreeze mine either or even freeze the ones I've earned the day before.

**Comment by cccyyc** [comment]
It's OK now
