### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Jeanseb77** [tronscan/tronscan-frontend#656]
I clic on ''vote''  nothing load, i try to send SEED Token to an adress to receive TRX...   I see it in the ''transactions'' but the SEED tokens are still there and after validating my transaction on my Ledger, a message appear telling me that a problem occur during the trasanction ;-(   
It's like that everytime i try...

**Comment by blcavalcanti** [comment]
I have this same problem in my account also to send seed, says that some kind of problem has occurred.

**Comment by Jeanseb77** [comment]
They are working on it 

Envoyé de mon iPhone
