### ISSUE TITLE
I can not unfreeze my trx.

### ISSUE THREAD

**Issue by blcavalcanti** [tronscan/tronscan-frontend#659]
the message "TRX can not be thawed. This may be caused because the minimum freeze period has not yet been reached." I've been using IOS version 10.13.6 (17G65), until today I've never had any problems with TRONSCAN, my tokes are stuck and I can not negotiate.

**Comment by Rb2the3** [comment]
I'm having similar issues. Did yours get resolved?

**Comment by cccyyc** [comment]
This message means TRX must be frozen at least 3 days before you unfreeze it. Please check the time limit first.

**Comment by Rovak** [comment]
Are you using the desktop or web client?

**Comment by chuckyloco** [comment]
Desktop (explorer) he je bent nederlands zie ik.
Ik heb hem op mijn laptop en kon eerst gewoon voten en freeze indrukken.
Dit kan dus allemaal niet meer.
Het moment dat ik op Vote bijvoorbeeld druk zou die nieuwe pagina moeten laden nopes nada.
Hoorde ergens dat ze bezig waren met patch voor windows?

Groet,

Mano

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: Roy van Kaathoven <notifications@github.com>
Verzonden: Monday, October 1, 2018 12:05:08 PM
Aan: tronscan/tronscan-frontend
CC: chuckyloco; Comment
Onderwerp: Re: [tronscan/tronscan-frontend] I can not unfreeze my trx. (#659)


Are you using the desktop or web client?

**Comment by wongzhunhou** [comment]
Unable to unfreeze
Unable to unfreeze TRX. This could be caused because the minimal freeze period hasn't been reached yet.
This keep showing up when i try to unfreeze it. I clearly waited for over 3 days but it is still saying this. I am using the tronscan.org website too but it is not working. Please help
