### ISSUE TITLE
Freeze Button Not Working

### ISSUE THREAD

**Issue by Rb2the3** [tronscan/tronscan-frontend#661]
Cannot Freeze my coins.
Please advise.

**Comment by cccyyc** [comment]
Any screenshot or video about that? These will help.

**Comment by chuckyloco** [comment]
I'am really want to unfreeze but stil it isn't working and nobody that helps me from TRON. I  can't even open freq. ask qustions looks like the buttons aren't working. Wel i will get my trx thats in my wallet of this and as soon i can get my trx unfrozen wil get them off to...this sucks tron no help at all allready over a month
