### ISSUE TITLE
Log in Timestamp on Tronscan

### ISSUE THREAD

**Issue by leek21** [tronscan/tronscan-frontend#671]
It would be great if Tronscan displayed the date and time of each login, the user could easily check.
This would help alleviate some paranoia about others accessing your account.
ie. if you keep your tron all forzen in your account, even if someone accesses it they can't transfer the coins out.  However you will never know someone else is accessing your account.

I imagine it wouldn't take much to display this log, or at least the last log in date and time.

**Comment by Rovak** [comment]
keeping a log of successful logins into a wallet is outside the scope of Tronscan. Logging into a wallet happens client side and no data is shared with the server. I also believe that keeping a log raises privacy concerns.
