### ISSUE TITLE
Don't combine two values in a single column in CSV download

### ISSUE THREAD

**Issue by blmatthews** [tronscan/tronscan-frontend#673]
In the CSV download, the amount and token type are in a single column. This makes it difficult to select only a single token type or to do things like create pivot tables to summarize by token type. Instead, there should be an amount column and a token column.

**Comment by iNDULG3NC3** [comment]
I have also requested this.

**Comment by blmatthews** [comment]
I just tried this and it hasn't changed, has it been fixed and will be rolled out later, or not fixed, or...?

**Comment by myfocus** [comment]
We have optimized the download of Excel and currently support up to 2000 data. We have processed a single address and a single token data.
