### ISSUE TITLE
[Bounty] New Wallet

### ISSUE THREAD

**Issue by Adsize** [tronscan/tronscan-frontend#68]
Not really my field of knowledge, but I'll try to explain it clearly. I'm not looking for answers.
When trying to enter a password for a new purse, the server is already trying to create a file with an encrypted key.
I see this:

![000021](https://user-images.githubusercontent.com/39515013/40617989-b6e194b6-6298-11e8-9d55-92c4793cc14e.jpg)

Depending on the duration of the pressure, after some time I see this:

![000022](https://user-images.githubusercontent.com/39515013/40618028-d85e5b38-6298-11e8-8a77-2e4d5b297691.jpg)

Conclusion:
1. Reloading the page at these stages practically does not work.
2. CPU power is wasted.
3. Enemies are millions.
4. But the servers try to create their own file with the key.
5. Enemy clamps any key for 10 minutes ...

Voluntary donation TRX: 0x00cb09ec70354ab8b7c328da2c0e5e4629f411da

**Comment by Rovak** [comment]
It looks like the password strength checker is the cause of the high CPU usage. This has to be done every time the password changes. It will also only impact the CPU of the client so i don't see this as a big issue
