### ISSUE TITLE
CSV EXPORT FILE TRANSACTION DONT WORK!

### ISSUE THREAD

**Issue by TRON-FAN** [tronscan/tronscan-frontend#684]
CSV EXPORT FILE TRANSACTION DONT WORK!

![image](https://user-images.githubusercontent.com/42068552/46774360-5127ed80-cd02-11e8-8bde-7c4bc17c66a1.png)

**Comment by cccyyc** [comment]
On which page did this happen ?Could you provide a screenshot of this ?
