### ISSUE TITLE
SAME PRIVATE KEY

### ISSUE THREAD

**Issue by shankz29** [tronscan/tronscan-frontend#692]
MY PRIVATE KEY ON POLARIS.DEX..
ICONEX.. ETHERDELTA..
 CAN BE USE TO SIGN IN AT TRONSCAN..
UNFORTUNATELY THERE IS NO AVAILABLE BALANCE.. I AM WAITING OTHERS TO CREATE NEW WALLET ADDRESS.. WITH THE SAME PRIVATE KEY ABOVE MENTIONS

**Comment by Rovak** [comment]
i'm not sure what you mean and it isn't really recommended to paste the polaris private key in tronscan

**Comment by shankz29** [comment]
try then.. create account on polaris.. use that private key.. open it at tronscan

**Comment by shankz29** [comment]
try then.. create acc on the mention exchange.. use that private key.. it will open on tronscan..
    On Monday, October 15, 2018, 10:48:23 AM GMT+8, Roy van Kaathoven <notifications@github.com> wrote:  
 
 
i'm not sure what you mean and it isn't really recommended to paste the polaris private key in tronscan
