### ISSUE TITLE
Tron, Freezing TRX and voting for SR

### ISSUE THREAD

**Issue by iamfastwalker** [tronscan/tronscan-frontend#694]
Hey there,

I tried to freeze more of my TRX but the window froze on me, i also tried to vote for the SR but this also froze on me. Thanks for listening ;0
TRON ON!!

Regards,

Fastwalker

**Comment by Terrygil** [comment]
Using a Nano Ledger S I am getting "ERROR" when I try to freeze tron and I get the same message when I vote. After several (probably 8-15) attempts it will accept my request. Is this a bug in the app or is it a bug in the Ledger? Are there any suggestions to correct problem noted above?
