### ISSUE TITLE
[Bounty] Tronscan V2 - incorrect display - Cellphone IOS Iphone

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#7]
Bugreport
-----------
there are problems with the presentation and formatting of the website on mobile devices
![image](https://user-images.githubusercontent.com/39301026/40217841-12776986-5a6f-11e8-8100-60e7b9013ad9.png)

![image](https://user-images.githubusercontent.com/39301026/40217856-20dedb9e-5a6f-11e8-9e12-cc25154212fb.png)

![image](https://user-images.githubusercontent.com/39301026/40217873-2f1d75bc-5a6f-11e8-8568-47e9ddbc72c9.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

timestamp of the test
--------------------
18. may 2018 07:30 am

tested OS
---------
IOS Device

Browser
-------
Safari Browser

**Comment by Rovak** [comment]
Fixed
