### ISSUE TITLE
Oculus/Steam VR software booting

### ISSUE THREAD

**Issue by Huaxan** [tronscan/tronscan-frontend#70]
Recently i started to have this problem when i visit the tron.network my
oculus and steam VR drivers are loading up. have been visiting alot, just got this recently

**Comment by Rovak** [comment]
I'm not fully understanding the problem, what do you mean with "loading up"?

**Comment by Huaxan** [comment]
Sorry for the late response, when i visit the tron.network the driver from STEAM VR is starting up, with no virtual headset connected to my computer it keeps trying to connect untill i close the site (tron.network).
I'm using the latest firefox and steam drivers, and never had this problem few months ago
