### ISSUE TITLE
Not recieving rewards

### ISSUE THREAD

**Issue by jp222222** [tronscan/tronscan-frontend#700]
Hi, have not received any rewards for voting in a few days. I have 150k tron, and no voting rewards. Thank you.

**Comment by Smacker8** [comment]
same here..worked fine for me for a week and a half....has anyone answered you on this?

**Comment by sanxiahaoren** [comment]
which sr?

**Comment by jp222222** [comment]
I just received a reply asking which Sr’s. It has been several coins that I haven’t received from, nut mostly Sesame seed.

Sent from Mail for Windows 10

**Comment by Smacker8** [comment]
Mine was on Tronspark and then seasameseed... it shows up on trnexplorer.io but on tronscan rewards don’t show up so I can freeze new coins and add to voting balance ..not sure why you can see it on trxplorer but not tronscan.... they eventually show up but days later

Ed Elder
Charter Specialist

ed@americanyacht.net
305.758.2500 main
561.385.3677 mobile

**Comment by jp222222** [comment]
Yes, I can definitely sat Tronspark was one of them. I’m hoping they show up, I have  a lot of trx frozen. Thanks for the response.

Sent from Mail for Windows 10
