### ISSUE TITLE
Fails to send Tron

### ISSUE THREAD

**Issue by catibarrilli** [tronscan/tronscan-frontend#706]
Hi.
Two days ago I made a withdrawal from Tron and the transaction is confirmed but the amount is not in my Exodus wallet. Please, can you help me?

![img_3688](https://user-images.githubusercontent.com/44166124/46952696-3a123400-d051-11e8-8d9c-8820a8352462.jpg)
![img_3689](https://user-images.githubusercontent.com/44166124/46952702-3bdbf780-d051-11e8-8ebb-4cdf5fef45e5.jpg)
![img_3690](https://user-images.githubusercontent.com/44166124/46952724-501ff480-d051-11e8-8d4f-6d76502c04bc.jpg)

**Comment by sanxiahaoren** [comment]
we are fixing this issue, balance has been in mainnet. don't worry;

**Comment by catibarrilli** [comment]
Still problem!!!! I Don’t see my 152 TRX


Enviado desde mi iPhone
