### ISSUE TITLE
I cannot unfreeze my TRONPower

### ISSUE THREAD

**Issue by viny486** [tronscan/tronscan-frontend#709]
I froze my tron 1 month ago. And I wanna unfreeze my tronpower. But I cannot unfreeze.
refer to attached picture.
![error](https://user-images.githubusercontent.com/44191513/47000409-2d7e0080-d163-11e8-9749-9c3883fe39b6.png)

How can I solve this problem?
MY Address : TTzcWBaYoCW8KwEBMwCSH7g8W4pZYtQ7G6

**Comment by chuckyloco** [comment]
Still got the same problem to and no anwers yet how i can get my trx onfrozen pffff with me i can't even get the site to open the link when pushing the button Vote. Can't reach nothing on the site. And TRON hasn't done nothing yet!!! My trx allready frozen for like 2 or more months somebody from tron please explaine!!
