### ISSUE TITLE
[Bounty] Tronscan V2 - faulty errormessage - Create Token - User not logged in

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#71]
Bug Report
----------
if a user is not logged in he gets an incorrect status message. only the variable is displayed and the panel size is not correct
![image](https://user-images.githubusercontent.com/39301026/40700569-5db610ae-63da-11e8-939e-3db6e85b5aa9.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
30. may 2018 6:00 am (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

**Comment by Rovak** [comment]
Should be fixed by language contributors
