### ISSUE TITLE
My account is going to get hacked please help

### ISSUE THREAD

**Issue by jp222222** [tronscan/tronscan-frontend#710]
I posted a comment on twitter, and it accidentally had a picture in it with my Private key, I deleted it right away but it may still be up some how, I have 150k tron freezing right now till 2;29 on 10-19,  is there a way to protect my account, it wont let me unfreeze them and withdraw Please help, or I know it will all be lost Please.

**Comment by TRON-FAN** [comment]
> I posted a comment on twitter, and it accidentally had a picture in it with my Private key, I deleted it right away but it may still be up some how, I have 150k tron freezing right now till 2;29 on 10-19, is there a way to protect my account, it wont let me unfreeze them and withdraw Please help, or I know it will all be lost Please.

freeze the amount every day and you need a programmer who can unfreeze with bot and send out imidiently!!!

contact me in TELEGRAM @TRXlongInvest my leader DIRK from TRON EUROPE can help you!
or contact @Rovakk 

you can freeze all the amount every day, send 1 TRX and freeze it, first find a solution and than wait for unfreeze!!!

**Comment by jp222222** [comment]
Thank you so much for the help. I will use the contacts you listed, and I will continually freeze until I have the solution. Thanks again, I can sleep tonight.

Sent from Mail for Windows 10
