### ISSUE TITLE
daily reward not showing up

### ISSUE THREAD

**Issue by Smacker8** [tronscan/tronscan-frontend#717]
Hello everyone... so ive been voting for about 2 weeks...everyday everything worked fine..getting daily reward..then couple days ago it just stopped...tronscan shows no new reward to freeze...trxplorer show there is some but less than my usual daily amount..and i havent lowered my votes.... can you help?

**Comment by sanxiahaoren** [comment]
which sr?

**Comment by Smacker8** [comment]
It was for TronSpark.... I moved it to Sesameseed and it delayed as well....Im back it tronspark and rewards are not showing on tronscan.... trxplorer shows stuff

**Comment by bogdan73** [comment]
Up until yesterday my TERC voting rewards were coming as usual. Since yesterday even if transactions appear in transaction log, I have 0 TERC tokens in the wallet. Please help.
