### ISSUE TITLE
Cant access Wallet with Ledger... Please Help

### ISSUE THREAD

**Issue by Rcbrownr7** [tronscan/tronscan-frontend#719]
HI I recently created a wallet on TronScan using my Ledger Nano S. I tested it with a few transactions in and out of the account and then moved all of my funds into the wallet. Earlier today I tried to free some coins but I could not get it to work. It would ask me to confirm on the ledger which I did but then nothing would happen on the screen. It would continue as if it is still waiting on me. Now I cannot open the wallet. I have the Tron app on my ledger but it continues to just say please open Tron app. Please help.

**Comment by TonyMcC** [comment]
Have the same issue... try to log in but comes up with ""No wallet view"
What's the answer and how do you fix it!!
