### ISSUE TITLE
Transfer to Tronscan wallet Confirmed but not received 

### ISSUE THREAD

**Issue by mnjc33** [tronscan/tronscan-frontend#720]
Good day
I sent 200,000 TRX from exchange to my Tronscan wallet. The hash shows that the transfer from exchange to tronscan was correct (address is correct) and also shows the transaction status as confirmed yet the 200,000 TRX has not been received in my wallet.

# Hash  d7f8e0e6ac451f32c7061816d40aa6b40565c981ef459b32f116fa6329444516
Block    3359283
Time     10/20/2018 4:22 PM 

Transfer contract;
From  TAUN6FwrnwwmaEqYcckffC7wYmbaS6cBiX  
To       TFEKCi8tFrHYjnzKE4JXGG6x52z7juK1Ew

Please can i request assistance to get the TRX i transferred into the wallet.

![screen shot 2018-10-20 at 5 40 40 pm](https://user-images.githubusercontent.com/41185939/47254656-7b5e7580-d48f-11e8-8f43-58dac05423e4.png)

**Comment by alexpeman21b** [comment]
Same here! :(
