### ISSUE TITLE
help me.. plz..

### ISSUE THREAD

**Issue by rjiky1234** [tronscan/tronscan-frontend#721]
The freezing progresses for an hour.

![2018-10-21 00 29 32](https://user-images.githubusercontent.com/44322502/47257714-3efd3a80-d4cc-11e8-8ab7-88c960faf2d4.PNG)
![2018-10-21 00 29 42](https://user-images.githubusercontent.com/44322502/47257716-415f9480-d4cc-11e8-832c-748225424006.PNG)

**Comment by sanxiahaoren** [comment]
we are fixing this issue, balance has been in mainnet.
