### ISSUE TITLE
Transfer to Tronscan wallet Confirmed but not received

### ISSUE THREAD

**Issue by alexpeman21b** [tronscan/tronscan-frontend#724]
Status: CONFIRMED
Hash: 0ee897068ae513d01282cc8e7141a989116919ed391ba757fe86b41c27a79b66
Block: 3361621
Time: 10/20/2018 1:19 PM

From: TAUN6FwrnwwmaEqYcckffC7wYmbaS6cBiX
To: TSDJJCHU25dNaajaiDpMX2AgrfgHQ6bUZ5

**Comment by wlcy** [comment]
hello

**Comment by cccyyc** [comment]
We are fixing that.

**Comment by sanxiahaoren** [comment]
we are fixing this issue, balance has been in mainnet.

**Comment by sanxiahaoren** [comment]
fixed already.

**Comment by alexpeman21b** [comment]
True, but I can't freeze my TRX yet

**Comment by cccyyc** [comment]
It will take a period to finish freezing

**Comment by Hazy8619** [comment]
Hey Alex can you tell me more about that transaction? Who was sending the trx to you? Do you know who owns that wallet?

**Comment by Hazy8619** [comment]
Alex  I suspect that account is stealing trx from people I have seen a complaint about it. Do you know who the account belongs to?

**Comment by alexpeman21b** [comment]
Hello @Hazy8619 it was me sending myself the trx from Binance...why?

**Comment by Hazy8619** [comment]
ok awesome I have seen a few messages about it not sending trx I thought it might of been a scam address but I guess its just Binance trasfers getting stuck
