### ISSUE TITLE
Rewards not in account

### ISSUE THREAD

**Issue by Mobrules1968** [tronscan/tronscan-frontend#725]
Received 504 TRX today per tronscan but it is not showing up in account.

**Comment by sanxiahaoren** [comment]
we are fixing this issue, balance has been in mainnet.

**Comment by Mobrules1968** [comment]
I appreciate the response.

 

David D’Aprile - President

NMLS ID 314988

Diversified Lending Group LLC

Synergy Mortgage LLC

NMLS ID 1018322

469.301.0599
