### ISSUE TITLE
Tron Available Balance

### ISSUE THREAD

**Issue by u00caa1** [tronscan/tronscan-frontend#727]
You can see Hash: b42a9f34bd70b9c68d7a1094d98e1ae5accf999aa8b1355d36adc4a07583fb27, Block 3379859, on 10/20/2018 at 9:31 PM transferred 92.636267 TRX from TTMNxTmRpBZnjtUnohX84j25NLkTqDga7j to TFGe1aBmrARShnVugVh27kyXXPmmxVtH4S.  However, my available TRX balance is only 91.233029 even though I don't show any transactions after that.  How is this possible?

**Comment by sanxiahaoren** [comment]
we are fixing this issue, balance has been in mainnet.

**Comment by u00caa1** [comment]
When will this be fixed?

**Comment by sanxiahaoren** [comment]
fixed already.
