### ISSUE TITLE
unfreeze

### ISSUE THREAD

**Issue by Dirkbelgie** [tronscan/tronscan-frontend#728]
saterdag i tried to unfreeze my trx  Sit said it was ok but now 2 days later there still not unfrozen  Does anyone no how it comes???

**Comment by Dirkbelgie** [comment]
adress    TEU9snQhEMCk6KqJ8RUMmCtnuiJe67uxTA


https://tronscan
org/#/transaction/326c943f8a0019aadc3f5512925ee93497a2f38f41151e69e299c847980
8ca7    
1 day agoUNFREEZEBALANCECONTRACT


grts

Dirk
 
 
 
 
-------Oorspronkelijk bericht-------
 
Van: sanxiahaoren
Datum: 10/22/18 15:26:48
Aan: tronscan/tronscan-frontend
Cc: Dirkbelgie;  Author
Onderwerp: Re: [tronscan/tronscan-frontend] unfreeze (#728)
 
what's the transaction id?

**Comment by Dirkbelgie** [comment]
i did not received these trx

TRANSACTIE   
Hash 680fa34002da94f0941de811dbb87a1a0809548c7fb604a1650e085b5d5780b1
Status:UNCONFIRMED
Hash:680fa34002da94f0941de811dbb87a1a0809548c7fb604a1650e085b5d5780b1
Blok:3433122
Tijd:23-10-2018 01:28 


Transfer ContractTRX transfer tussen adressen
VanTZBqUM2KV8XcmoWaDHR8VYhnhHaevEHvZb
TOON QR CODEVERZEND TOKENS
NaarT9ykEBv9UJ2NnVyrLk9yXgDCnMwUwR93Db
TOON QR CODEVERZEND TOKENS
Hoeveelheid50 TRX

**Comment by Dirkbelgie** [comment]
Hoi

is it possible to transfer my huobi tokens in my tronaccount to my huobi
exchange into HT ???

i tried a several times ,but always got the message wrong adress,and the
adress i enter is correct

even a transfer to my ethernetwallet did not work??

grts
Dirk Anthoni

**Comment by wongzhunhou** [comment]
I still dont get back my TRX after i unfreeze it. It is still showing as tron power. Please help me out with this!

**Comment by Wintron200228** [comment]
Ik kan mijn transactie niet beheren. Vanaf vorige jaar 2020-11-19 heb ik een transactie gedaan, maar kan nog steeds niet mijn transactie binnenhalen ! 
ID : ab8b2d21ab8bbeb375ab6395b7ff2c62faa86cecdcd28da2c7b7cdcbc4e3dc41
Block : 25155239	
184dagen 21 uur geleden
Van :  TAUN6FwrnwwmaEqYcckffC7wYmbaS6cBiX
Naar: TTLZJQqMeuH2VfRTCKeodC7hsgC5bxVFgJ
TRX overdragen	

BEVESTIGD
SUCCES	3.383.725803	
TRX
Hoe kan ik mijn transactie gegevens binnenhalen en verwerken zodat ik mijn fonds kan gebruiken?? Help help help
