### ISSUE TITLE
Testnet is empty

### ISSUE THREAD

**Issue by mpmprudencio** [tronscan/tronscan-frontend#73]
Hi guys, this afternoon I open up the browser and the Testnet tokens are totally gone, my tokens are gone including the UVR Token I created this morning. Can't find any register about it in the Testnet. I logged out and logged in again and was the same, everything is gone.

**Comment by Rovak** [comment]
Tronscan is transitioning to main net and data has been reset. Tronscan will be fully operational on main net shortly.
