### ISSUE TITLE
TronScan Tolken Balance not increasing after drop

### ISSUE THREAD

**Issue by newjobplease** [tronscan/tronscan-frontend#732]
Hi there I noticed I'm getting drops of tokens but the token total has started not being added to the existing tile balance. so I see the token drop with the balance not added to the total. This is for

**Comment by newjobplease** [comment]
... For Tarquin. This is happening to my friend's account as well.

**Comment by cccyyc** [comment]
We are fixing that. Your  token will not be lost.

**Comment by newjobplease** [comment]
Thank you for the very fast reply! Great work 👍🏻

**Comment by sanxiahaoren** [comment]
hello, fix now,please check it.
