### ISSUE TITLE
Tron Available Balance

### ISSUE THREAD

**Issue by u00caa1** [tronscan/tronscan-frontend#734]
I need this fixed ASAP.  My available balance is not updating on Tronscan.org.  My balance should be 345.491485 with 554,050 in TRON Power.  My balance is only showing 91.233029 and it will not allow me to freeze or unfreeze even though the time frame has passed.  Please advise ASAP.

**Comment by sanxiahaoren** [comment]
hello，please give me your address, and also check your address in tronscan again, we have fixed it
