### ISSUE TITLE
Can't vote

### ISSUE THREAD

**Issue by u00caa1** [tronscan/tronscan-frontend#736]
I have 554,050 in TRON Power with 255 TRX still available to vote but it wont let me vote.

**Comment by sanxiahaoren** [comment]
did u vote from tronscan.org?

**Comment by u00caa1** [comment]
Yes

**Comment by cccyyc** [comment]
Could you please provide more detail about it. For example a screenshot.

**Comment by u00caa1** [comment]
It appears to be fixed. Next time I’ll
Provide a screenshot.
