### ISSUE TITLE
cant freeze my trx

### ISSUE THREAD

**Issue by bernardcehner** [tronscan/tronscan-frontend#738]
Hello
I have a problem with freezing my trx, i have enough balance on my wallet but i can not freez it because it says i dont have enough trx. I have on my wallet 1003 trx. can u help me?
here is a screenshot:
https://prnt.sc/l9ey27

**Comment by alexpeman21b** [comment]
Same here ✋

**Comment by cccyyc** [comment]
Cannot reproduce it. Please try again and give more details.

**Comment by bernardcehner** [comment]
whitch details do you need? i dont know what else to give :)

**Comment by bernardcehner** [comment]
it still the same thing. cant freeze my trx couse it still thinks that nothing is there :) i will provide details, just point me what i have to do :)

**Comment by bernardcehner** [comment]
this is interesting when i closed this banner TRON power can be gained through freezing TRX, 1 TRX for 1 TRON power https://prnt.sc/la2tfv , the text that i can not freeze trx doesnt appear,what appears is blank site

**Comment by bernardcehner** [comment]
https://prnt.sc/la3163

**Comment by bernardcehner** [comment]
receiving page with qr code trx is working, sending trx loading blank page

**Comment by cccyyc** [comment]
We are trying to reproduce it.
One thing you can do is clearing the browser cache, and try again. Tell me if it works

**Comment by bernardcehner** [comment]
i did what you said and the problrm still persists. ill try it in a while again,clearing cache... ill be back with my findings :) thanks

**Comment by bernardcehner** [comment]
i downloaded tronscan desktop and here everything is vorking fine and i can freeze my trx.
