### ISSUE TITLE
Can not send funds!

### ISSUE THREAD

**Issue by pastet89** [tronscan/tronscan-frontend#739]
When I click on "Send" I get blank screen. Both on desktop and web.

**Comment by cccyyc** [comment]
We have not reproduced this problem for now. Please try again and give more details. ty!

**Comment by Kirilldenisenko** [comment]
Такая же проблема, при нажатии на кнопку отправить, появляется просто пустой экран, эта проблема не у всех, у меня ещё один кошелёк и в нём всё норм

**Comment by cccyyc** [comment]
Do you have enough balance there?
If so, try clearing the browser cache and then do it again.

**Comment by farurockkk** [comment]
cccyyc sir please help me to withdraw my trx from tronscan web wallet i'm sending you more screen shots of my web wallet 
![w](https://user-images.githubusercontent.com/44433338/47491758-57d55b00-d800-11e8-84fc-9e82c1fc21df.JPG)
![w2](https://user-images.githubusercontent.com/44433338/47491759-586df180-d800-11e8-9428-b01b52f9dff3.JPG)

**Comment by tronservice** [comment]
Hello, write to us we will try to solve your problem tronservicetrx@gmail.com

**Comment by cccyyc** [comment]
We are fixing it. You can contact me directly.
TRON community official email are ended with @tron.network.
