### ISSUE TITLE
Token Balance Error

### ISSUE THREAD

**Issue by sherwher** [tronscan/tronscan-frontend#743]
hi I'm sherwher

I found something that people could misunderstand.

![image](https://user-images.githubusercontent.com/9384553/47400041-84449500-d776-11e8-9455-c0539e212f6d.png)

but Tab TokenBalance

![image](https://user-images.githubusercontent.com/9384553/47400068-9e7e7300-d776-11e8-9df8-55aea6376526.png)

I have 258.101085 TRX but TokenBalance is 258,101,085 ?

I do not have more than 250 million Tron.
I would be very happy if I had 250 million tron. But it is not.
 I want this part fixed.

thank you

**Comment by cccyyc** [comment]
Please provide your address

**Comment by cccyyc** [comment]
We will fixing that

**Comment by cccyyc** [comment]
It has been fixed now. The balance of TRX should only shows in the account page. So we hide it of the address page.
