### ISSUE TITLE
All candidates have an error message when clicking on the button "OPEN TEAM PAGE"

### ISSUE THREAD

**Issue by TRON-FAN** [tronscan/tronscan-frontend#744]
![image](https://user-images.githubusercontent.com/42068552/47421303-962b3580-d780-11e8-8f98-218251766cdf.png)

![image](https://user-images.githubusercontent.com/42068552/47421316-9d524380-d780-11e8-8022-e127264faab5.png)

**Comment by cccyyc** [comment]
Already fixed.
