### ISSUE TITLE
TRON WEB WALLET SEND OPTION IS NOT WORKING 

### ISSUE THREAD

**Issue by farurockkk** [tronscan/tronscan-frontend#745]
![w](https://user-images.githubusercontent.com/44433338/47431763-8a744a80-d751-11e8-9b39-9787074a30fa.JPG)
![w 2](https://user-images.githubusercontent.com/44433338/47431881-c3acba80-d751-11e8-9338-6fbb6437f591.JPG)

BEFORE 2 MONTHS I DEPOSIT MY TRX FROM BINANCE TO TRON WEB WALLET AND THERE IS  BEING SHOW MY BALANCE WITHOUT TRON POWER AND NOW I WANT TO WITHDRAW BUT WHEN I CLICK ON SEND OPTION THEN PAGE IS BEING STOPPED AND COMING AGAIN LOGIN PAGE ,,,,PLEASE HELP ME HOW CAN I WITHDRAW MY TRX FROM MY WEB WALLET ...

**Comment by Kirilldenisenko** [comment]
Здравствуйте! Могу помочь решить вашу проблему
