### ISSUE TITLE
Не могу отправить TRX c кошелька tronscan web 

### ISSUE THREAD

**Issue by Kirilldenisenko** [tronscan/tronscan-frontend#746]
Не могу отправить TRX с кошелька Tronscan web. Не могу отправить TRX, открывается просто белый экран, выходит из кошелька

**Comment by Vova201** [comment]
Появились проблемы с тронсканорг,не могу вывести монеты,контакты техподдержки недействительны,никаких адресов для связи более нет. Кто это такие и почему прячутся?

**Comment by Neiroyn** [comment]
помогите пожалуйста, есть проблема, как мне с usdt перевести в trx именно с сайта tronscan 
![помогите ](https://github.com/tronscan/tronscan-frontend/assets/148005972/6d676fa2-a128-4f5a-930a-316ad91599ee)
потому у меня показывает 0 на счету хоть я пополнил, в tron link не показывается эти usdt
