### ISSUE TITLE
TRX transferrred but not able to freeze

### ISSUE THREAD

**Issue by kenjb** [tronscan/tronscan-frontend#748]
![image](https://user-images.githubusercontent.com/34899879/47506031-4fe7dc00-d83d-11e8-9dcc-1899172038b8.png)

We transferred TRX to our new wallet.  It showed up after 1 day.  But it still does not show a token balance or allow for freezing.  Please advise.

**Comment by cccyyc** [comment]
Already fixed it.
Please check it.
