### ISSUE TITLE
Zero bandwidth, can't freeze trx, can't send them away

### ISSUE THREAD

**Issue by Yntelligence** [tronscan/tronscan-frontend#749]
My bandwidth was stucked in negative numbers for a long time and wasn't changing, I think it was few weeks since I unfreezed my tokens (I didn't notice if it was negative before as well). After I received some random tokens, it increased to 0, but it didn't move from that time (5 days).

**Comment by cccyyc** [comment]
Hey，sorry to bring a bad user experience. 
1. Each address has 5000 free bandwith .This are not shown in the bandwith balance now.
We will support it next version. You can make transactions.
2. please provide a screenshot of send and freeze. We will help solve this problem.
3. Now the freeze function are a bit of slow, you can wait for a while.

**Comment by Yntelligence** [comment]
Thanks for the reply. Here are screens of sending tokens. On the second screen is the logo loading and nothing else happens. I'll wait for your respond and eventually try the freeze, but I don't want to wait three days if it would work

**Comment by cccyyc** [comment]
1. It's a display error and will be fixed soon.
2. Now the bandwith shows correctly in tronscan. Your bandwith points are 5000.
3. It looks like you can send your TRX ,already transfer successfully?

**Comment by Yntelligence** [comment]
No, I can't. It just keeps loading infinitely, nothing else will happen, no error, no transfer

**Comment by cccyyc** [comment]
Please provide your address.

**Comment by Yntelligence** [comment]
Any suggestions?

**Comment by Yntelligence** [comment]
I still can't send it away. I can't even login into my wallet through different browser or in the same browser in incognito mode. I started my tronscan accout long time ago, everything was fine, but now i can't do anything with my tokens, not even freeze them. It looks like it is just a mirror of my account without any tokens...

**Comment by Yntelligence** [comment]
Please

**Comment by cccyyc** [comment]
Are you visiting https://tronscan.org/#/  ?

**Comment by Yntelligence** [comment]
I tried it now after few days and now there is an error message already. And yes, it was tronscan.org
![untitled](https://user-images.githubusercontent.com/43995812/48209965-b826d980-e376-11e8-9e45-a51a3fc179f3.png)

**Comment by Yntelligence** [comment]
Import pk worked and I sent it through tronwatch wallet, thanks!
