### ISSUE TITLE
Tron Link Chrome Token Tab Issue

### ISSUE THREAD

**Issue by sticklerlangki5** [tronscan/tronscan-frontend#750]
Dear Sir/Madam

I have found out that in the Token tab on the TronLink is having a problem in displaying all the tokens.
Some of the Tokens goes missing because there is no scroll .
I have attached an image along to show the error . Please do look into this error.

![issue](https://user-images.githubusercontent.com/788421/47517322-75103500-d8a5-11e8-98d3-ec2e518d433e.PNG)

Trx address: TRvDKmckJtRmYGb3A7EFU5uBL6pkRM2w7G

Thanking You.

**Comment by cccyyc** [comment]
Already give a feedback to the TRON link team.

**Comment by Rovak** [comment]
Belongs to the https://github.com/TronWatch/TronLink project

**Comment by sticklerlangki5** [comment]
@cccyyc didnt get you.
@Rovak thank you.
