### ISSUE TITLE
Participate TOKEN wrong translation

### ISSUE THREAD

**Issue by TRON-FAN** [tronscan/tronscan-frontend#755]
![image](https://user-images.githubusercontent.com/42068552/47638734-ad429c80-db5f-11e8-96af-1746ba5119eb.png)

Look language is english?

![image](https://user-images.githubusercontent.com/42068552/47638761-c77c7a80-db5f-11e8-8d91-b23f832d41a2.png)

**Comment by cccyyc** [comment]
It's a translation error and we will optimization it in the next version.
