### ISSUE TITLE
ledger nano s not opening on tronscan wallet program using macbook air

### ISSUE THREAD

**Issue by tcivil412** [tronscan/tronscan-frontend#756]
So i follow the ledger instructions to the T, however, the wallet just seems to load...and load...and load.. i've only opened the wallet once. Not even sure how or why it decided to do so at that time but since then I've had no luck. Could this be mac related? I have a friend using on Windows and he has no issues. Thx

**Comment by TRON-FAN** [comment]
Open the app on the ledger

Then go to Tronscan Desktop and click OPEN WALLET and select the Ledger option, then it should work to 99%: D
