### ISSUE TITLE
Withdraw coin

### ISSUE THREAD

**Issue by SGTMAJ0411** [tronscan/tronscan-frontend#757]
Good Evening,
   I am trying to send one bitcoin to Gemini account but states the address is wrong.  Please help,
Pepe Ramirez

SgtMaj 0411

**Comment by cccyyc** [comment]
Hi，
Is this happening in tronscan?
Please provide a screenshot and your receiving address so that we can help you.

**Comment by TRON-FAN** [comment]
> Good Evening,
> I am trying to send one bitcoin to Gemini account but states the address is wrong. Please help,
> Pepe Ramirez
> 
> SgtMaj 0411


I hope you did not buy the Bitcoin Tron Token

that would be very bad, because this is not a real bitcoin
