### ISSUE TITLE
Funds are dissapearing

### ISSUE THREAD

**Issue by mikedandan** [tronscan/tronscan-frontend#758]
For some reason my earned tokens (trx) are now gone.  2 days prior I was at 157 earned and now at 145?  I am not sure what is going on but to see it go backwards is not a good sign.  Can u explain this and get it fixed because that means I lost a lot more with out my knowledge.

**Comment by cccyyc** [comment]
Hi, several questions i wanna make sure:
1. Is this happening in tronscan.org ?
2. When did this happen?
3. You can check the transaction record to see if there's a theft.
 It would be nice if you can provide your address to us.

**Comment by TRON-FAN** [comment]
> For some reason my earned tokens (trx) are now gone. 2 days prior I was at 157 earned and now at 145? I am not sure what is going on but to see it go backwards is not a good sign. Can u explain this and get it fixed because that means I lost a lot more with out my knowledge.


I think you think the rewards are getting less and less for your vote

the more you vote for a sr, the less trx you get

**Comment by mikedandan** [comment]
That would not reduce your overall balance.  My balance is what had gone
down.  How can you see balance and transactions that would show it go down?

**Comment by cccyyc** [comment]
Do you have a lot transactions.
If your bandwith is not enough it may cost some TRX as transaction fee. See your bandwith here.
![image](https://user-images.githubusercontent.com/39366681/48186195-4482cd80-e372-11e8-87e6-b2e25cb67b01.png)
