### ISSUE TITLE
trx never arrived at tronscan desktopwallet

### ISSUE THREAD

**Issue by boywillems** [tronscan/tronscan-frontend#759]
Made a withdraw transfer on Bitfinex,everything was approved,adres ok
(Tronscan desktopwallet with ledger nano S)
Now ,after contact with Bitfinex,is this what they say;
Thanks for your follow up email and details.
We are glad to let you know that we had since resolved your TRX transfer.
Just to let you know, the reason of the delay is due to downtime experienced by the TRX network itself.
I hope you have a nice day. Please do not hesitate to let me know if you have any other queries.
After all i got still no trx in my wallet, almost 80 hours waiting.
somebody knows what to do??

**Comment by TRON-FAN** [comment]
i think best way to contact Bitfinex, but i hope you get your TRX till today :D
