### ISSUE TITLE
Something went wrong submitting this transaction

### ISSUE THREAD

**Issue by scapieau** [tronscan/tronscan-frontend#760]
Hi,
I just tried to move my Tron from my nano S to bittrex account and binance but it gives an error.

I do all right i think. I connect the ledger, open tronscan for desktop, connect to the wallet, try to give the addresse from binance, confirm the transaction on mt Nano ledger and then it gives an error: Something went wrong processing this transaction.

What could be wrong? I moved them onto my nano ledger about 2 months ago from binance, so should be on mainnet... why is this not processing?
thanks

**Comment by TRON-FAN** [comment]
may happen from time to time, but I hope you have solved the problem :D

**Comment by angusmcnab** [comment]
Happens all the time to me.
