### ISSUE TITLE
using nano ledger in tronscan

### ISSUE THREAD

**Issue by sungmm** [tronscan/tronscan-frontend#764]
Hello,
I use nano ledger s, so I have to open my wallet using tronscan desktop.
tronscan desktop latest version was released on 19 Jul...

There are many updates in tronscan.
ex) Tron Energy, Note (When I send coins to other address, I can write something) ...

But, I can use this function, becasue tronscan desktop don't supported these updates..
and They are not matched. For examples, Online Nodes, Block Height, Transactions Last Day ...

**So, I want access my wallet using https://tronscan.org/#/ directly. not using Tronscan desktop.**

Please, check this suggestion. and update https://tronscan.org/#/.
Thank you.

**Comment by TRON-FAN** [comment]
you must use tronscan desktop :( other way not possible at the moment :(
