### ISSUE TITLE
Tron wallet on ledger nano s

### ISSUE THREAD

**Issue by rshco** [tronscan/tronscan-frontend#765]
Downloaded latest version of Tron app for mac from Tronscan clicked on open wallet then open wallet again click on Ledger......connected Ledger as requested but no connection just three dots to say waiting for connection ?

Im guessing the nano will create address/wallet and i don't have to create a new wallet on the home page of the Tron app any help would be great 

Can create and open a new wallet by creating new secret ket/key file but don't want to use wallet this way ?

**Comment by TRON-FAN** [comment]
connect ledger open the tron app and than go open wallet tronscan and choose the ledger option :D
