### ISSUE TITLE
Ledger wallet without address

### ISSUE THREAD

**Issue by kokolorentz** [tronscan/tronscan-frontend#766]
Hello,
I'm trying to use the Tronscan Wallet (v2.0.2) on Win7 64bit with a Ledger Nano S.
The "Ledger Connected" screen in the Open Wallet dialog still shows the wallet address correctly.
But after click on "open wallet", the wallet view shows the address for brief moment - then the address disappears and cannot be accessed anymore (not even thru the copy icon).
See... 
![tron-empty-address](https://user-images.githubusercontent.com/31376271/48019557-039d7580-e134-11e8-9023-cf09c80d621c.jpg)

The "Show QR-Code" also shows an empty window:
![tron-empty-qrcode](https://user-images.githubusercontent.com/31376271/48019670-4b240180-e134-11e8-9c81-5416f6a3acbe.jpg)

Selecting the menu "Wallet" -> "Receive" shows an empty address and QR-Code:
![tron-empty-receive](https://user-images.githubusercontent.com/31376271/48019820-a524c700-e134-11e8-9d8b-3dc53d60ff61.jpg)

Selecting the menu "Wallet" -> "Send" empties the whole Tronscan application window, so there is no interface anymore and you can do nothing but just close the whole application:
![tron-empty-send](https://user-images.githubusercontent.com/31376271/48019937-ef0dad00-e134-11e8-8bc6-dc73237b95bf.jpg)

Not a really trust creating wallet to store your cryptos in....

Sincerely, 
Kokolorenz

**Comment by kokolorentz** [comment]
Of course. 
If wouldn't follow this description, I couldn't even open this "Ledger Connected" screen in the Open Wallet dialog. And as I said, on this screen it even shows the wallet address correctly.
But after click on "open wallet", the wallet view shows the address just for brief moment - then the address disappears and cannot be accessed anymore...
Did you read my description above?

**Comment by JWhiteUX** [comment]
Wait until you do get an address and you can't Freeze/Unfreez ALL of your tokens and you're sitting around waiting for these guys to release a patch/update.

I was able to freez & vote 3 months ago, but now, now I can't unfreeze anything and what wasn't frozen is unavailable for freezing/voting

**Comment by kokolorentz** [comment]
You mean waiting until there will be a software update, which gives me an address for my wallet? Right now I can't and and don't dare to even deposit my tokens on this scary wallet...

**Comment by JWhiteUX** [comment]
Yeah, I have ALL of my TRX in this wallet and I can't unfreeze any of it, and I recently, as a test, sent ~1100TRX from an exchange to my wallet and it just updated the balance and still shows zero Tron Power. Again, I'm unable to un/freeze them so that leaves me sitting on a wallet that cant do jack and squat. The dev team has been completely unresponsive which only makes this worse.

**Comment by kokolorentz** [comment]
Oh man, that sounds so bad - big sorry for you and good luck!
I'm so happy that I still have my TRX on the exchange. Although not recommended, it looks like a much better option than this scary wallet.
I don't understand, how developers can publish a wallet like that, where people who really believe in the project might store big savings.

**Comment by dfv219** [comment]
I have the exact same problem as kokolorentz. Just wanted to mention. There are more affected people.
![image](https://user-images.githubusercontent.com/13416470/49035852-4a700f80-f1b6-11e8-9c49-ee598d094163.png)
![image](https://user-images.githubusercontent.com/13416470/49035919-84411600-f1b6-11e8-84be-20c0e9f87fad.png)

**Comment by GarethTRelph** [comment]
I have exactly the same issue. I cannot risk sending to the address as I cannot copy and paste it which worries me. I also have the blank address at the final screen. It also states there have been 63000 transactions which is nothing to do with me?

**Comment by J3roen** [comment]
Having the exact same problem with a newly bought Ledger ... Anyone has a solution?

**Comment by kokolorentz** [comment]
With this issue, and 363 other issues, I would say this wallet is extremely unsafe. 
Solution: Don't use it!
Currently loosing my trust in the whole Tron project and starting to regret my investments in it.... :-/

**Comment by Colerbear** [comment]
Ive had the same issue but when i turned on browser support in the nano for tron my address showed up just fine after.
