### ISSUE TITLE
[Bounty] Tronscan V2 - receiving test tokens - faulty

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#77]
bug Report
-------------
after creating a new account i try to request test tokens. unfortunately the process doesn't work anymore
![image](https://user-images.githubusercontent.com/39301026/40803931-2cf59746-651a-11e8-8390-e0577469be7b.png)

![image](https://user-images.githubusercontent.com/39301026/40803942-35e0612e-651a-11e8-9ccd-44c96b63a709.png)

after few minutes:
![image](https://user-images.githubusercontent.com/39301026/40803958-454d14e0-651a-11e8-96e6-9f6229c26f77.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
31. may 2018 9:30 pm (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

**Comment by Rovak** [comment]
Fixed in #150
