### ISSUE TITLE
Strong recommendation:-  Add value amount column next to smart contracts and date?

### ISSUE THREAD

**Issue by OneCoinWillRuleThemAllTRX** [tronscan/tronscan-frontend#771]
Can you add two columns next to smart contracts that shows value and the date of the smart contract took place?

It is impossible to search through smart contracts looking for a value amount when you have hundreds of smart contracts.

Date would help narrow down too.

**Comment by cccyyc** [comment]
![image](https://user-images.githubusercontent.com/39366681/48603219-c1d0c280-e9b0-11e8-8554-a2ffca0f4e81.png)
![image](https://user-images.githubusercontent.com/39366681/48603254-d745ec80-e9b0-11e8-942e-d41819fc47a9.png)

**Comment by cccyyc** [comment]
Already have the balance.
Showing the time is a good point. Will think about that.
