### ISSUE TITLE
我提现1个trx，但是提现账户却扣了4个trx，为什么？

### ISSUE THREAD

**Issue by menshen** [tronscan/tronscan-frontend#787]
我上线了一个dapp，然后发现每次处理trx交易的时候数都不对。
比如标题中讲的，我提现1个trx，但是提现账户却扣了4个trx！
还有我在合约中转给账户10.3个trx，但是对应的账户trx不但没有增加，却少了6个trx？
对应的solidity代码在测试环境都是ok的！
这是什么问题，是矿工费特别高吗？

**Comment by cccyyc** [comment]
合约调用需要使用Energy，尝试冻结更多TRX以获取energy，energy不足会扣掉TRX作为手续费

**Comment by menshen** [comment]
@cccyyc 
如何给合约冻结trx呢 ？
有相关文档吗 ？
是不是给合约冻结了trx，调用合约的用户就可以不用消耗trx了呢？
