### ISSUE TITLE
[Bounty] New wallets on different servers at once

### ISSUE THREAD

**Issue by Adsize** [tronscan/tronscan-frontend#79]
1.
All in Chrome. On one home IP.
We get a new wallet. https://tronscan.org/#/
"Private Kay" -> random ciphers and letters -> "sing-in".
In the next tab, we also get another one wallet.
We update the page and find ourselves in the first profile.
Cookies are read, the server identified me. Everything is fine.

2.
We go to:
https://www.zoomeye.org/searchResult?q=https%3A%2F%2Ftronscan.org%2F%23%2F

![000333](https://user-images.githubusercontent.com/39515013/40815389-d28b58ce-654e-11e8-8c19-5d669357a990.jpg)

In a new window, we open two tabs with HTTP / 1.1 server responses. 200 OK
http://18.221.104.145:8080
http://18.216.126.238:8080
Also we get new different wallets in each.
When updating the pages, it is logical to assume that the servers will recognize me.
But this does not happen. Total two windows and three different wallets.

Complement later: Connect and interact with the specified unprotected http protocol.

Voluntary donation TRX: 0x00cb09ec70354ab8b7c328da2c0e5e4629f411da

P.S. 
I do not know if this information helped, I tried to be useful to the society.

P.P.S.
By the way not on the topic.
https://twitter.com/justinsuntron/status/1002072890349531137
This message relates to the merits of the search participants in this topic?

______________________________________
Bounty Program
https://twitter.com/justinsuntron/status/1002072890349531137

**Comment by Adsize** [comment]
![000333](https://user-images.githubusercontent.com/39515013/41049586-ec7b94d2-69b9-11e8-8aa0-9e7c95dd8387.jpg)

**Comment by Rovak** [comment]
The data is stored in localstorage which is separated by domain/ip, this is intended behaviour.

**Comment by Adsize** [comment]
If it matters ...
http://18.221.104.145:8080
http://18.216.126.238:8080

![0009998](https://user-images.githubusercontent.com/39515013/41189646-df2d9cd6-6bd9-11e8-878b-e6c1673c8d52.jpg)
