### ISSUE TITLE
Dex giving an error when purchasing

### ISSUE THREAD

**Issue by Mobrules1968** [tronscan/tronscan-frontend#793]
You make a purchase and it tells you it failed and can;t broadcast. This is getting around the community so please get this rectified. 

![image](https://user-images.githubusercontent.com/42687534/48525957-823c9600-e84b-11e8-9555-fefc4c74e0fd.png)

**Comment by brnxfinest** [comment]
Same is happening to me

**Comment by paulmeade7** [comment]
I have the same problem, how is it that someone hasn't come up with an answer to why this is happening. Everything sounds like it's so easy to purchase on DEX though I can't do anything. Very disappointing. Please help.

**Comment by cccyyc** [comment]
here's a guide book
https://coin.top/production/js/2018-11-27-14-01-15DEX_guidebook.pdf

**Comment by Mobrules1968** [comment]
I do not need a guide book. Beyond that have you see the errors all over it? Please have this reviewed.

 

David D’Aprile - President

NMLS ID 314988

Diversified Lending Group LLC

Synergy Mortgage LLC

NMLS ID 1018322

469.301.0599

**Comment by cccyyc** [comment]
It's not a bug~It's just a tip based on bancor. Just have a look at the guidebook,you will know more about DEX ~

**Comment by Mobrules1968** [comment]
I figured it out thanks indeed

 

David D’Aprile - President

NMLS ID 314988

Diversified Lending Group LLC

Synergy Mortgage LLC

NMLS ID 1018322

469.301.0599

**Comment by cccyyc** [comment]
👍
