### ISSUE TITLE
DEX

### ISSUE THREAD

**Issue by laceypearls** [tronscan/tronscan-frontend#795]
I was wondering why is the information updated for price of WIN in the information page but on the DEX it’s still selling at .13 Trx instead of the new price at 1024 Trx?

**Comment by laceypearls** [comment]
![252378f6-e93a-4a52-b789-3d9a1c4f39b0](https://user-images.githubusercontent.com/45076903/48572656-02104200-e8d8-11e8-9ec6-1a6bdd31b767.jpeg)

**Comment by cccyyc** [comment]
ICO price is different from it's market price.
