### ISSUE TITLE
My Tron is still locked

### ISSUE THREAD

**Issue by jp222222** [tronscan/tronscan-frontend#796]
It was supposed to be unfrozen 3 hours ago, is there usually a delay. Im missing DEX. Thank you JP

**Comment by JWhiteUX** [comment]
I'm unable to unfreeze ALL of my TRX. Despite adding unfrozen TRX to my wallet. I have not heard anything from the dev team on the matter.

**Comment by cccyyc** [comment]
clear cache and retry it.
