### ISSUE TITLE
[Bounty] Tronscan V2 - Custom Token - Missing Var Reference

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#80]
Bug Report
----
missing description fields - only the variables are referenced

![image](https://user-images.githubusercontent.com/39301026/40823903-6791f5fe-6572-11e8-8ebe-7f9bb313ef69.png)

![image](https://user-images.githubusercontent.com/39301026/40823953-8e09761c-6572-11e8-9e72-ee73cbcfe690.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
01. June 2018 8:00 am (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

Bounty Program
--
https://twitter.com/justinsuntron/status/1002072890349531137

**Comment by Rovak** [comment]
Missing languages will be contributed later
