### ISSUE TITLE
TRONGOLD

### ISSUE THREAD

**Issue by jp222222** [tronscan/tronscan-frontend#804]
Hello, maybe someone can answer this please. I purchased 53k GOLD on Tronscan, and it was 1 to 1 TRX, then I found it on Trxinfo for.032, basically 30 GOLD to 1 trx can anyone explain the massive price increase of buying on Tronscan vs' Trxinfo? Is this correct? It doesn't seem like a fair play...

**Comment by Mobrules1968** [comment]
I can answer. One is on an exchange and one is not. If you buy direct from Trongold they have their price and the exchange is market driven.

 

David D’Aprile - President

NMLS ID 314988

Diversified Lending Group LLC

Synergy Mortgage LLC

NMLS ID 1018322

469.301.0599

**Comment by jp222222** [comment]
Thank you, I can understand that, but why is Tronscan seemingly gouging thousands of loyal clients, I see order history of 100,000 GOLD everywhere on Tronscan, that’s is huge price jump. A little unethical in my opinion, fortunately the $1500 u.s. I put in wasn’t my only money, but a lot of people are not happy. 100,000 on trxinfo is only 3349 trx….

Sent from Mail for Windows 10

**Comment by Mobrules1968** [comment]
It is not Tronscan  that is selling Trongold for that price. It is Trongold themselves.  I don’t see Trongold on the Tronscan Dex just yet. 

 

People can be upset if they like but it’s misplaced. Most likely what has happened is when Trongold hit the Dex it dropped in price.

 

David D’Aprile - President

NMLS ID 314988

Diversified Lending Group LLC

Synergy Mortgage LLC

NMLS ID 1018322

469.301.0599

**Comment by jp222222** [comment]
Ok, just so you know it is on page 2 of the token participation drop down menu, it hasn’t been listed on DEX yet, but it is available for purchase right now. We’ll I went back totrxinfo, and bought 2,000,000. For the price I got 53,000.
Thx for the response.
Sent from Mail for Windows 10

**Comment by Mobrules1968** [comment]
Well done on the purchase!

 

David D’Aprile - President

NMLS ID 314988

Diversified Lending Group LLC

Synergy Mortgage LLC

NMLS ID 1018322

469.301.0599
