### ISSUE TITLE
missing loveHearts

### ISSUE THREAD

**Issue by karakukakz** [tronscan/tronscan-frontend#806]
Hi, I bought 10.000 LoveHearts via tronscan but 500trx has gone and i did not received any LoveHearts ? (b7524a8ac81edacab2d3b07f9b0416bfafb880b9e213783de69b62815881d2a3)

**Comment by cccyyc** [comment]
It's exactly a transfer transaction:
![image](https://user-images.githubusercontent.com/39366681/49137447-6941e380-f327-11e8-90fb-b6a0fe736e2f.png)
Any chicanery here？
