### ISSUE TITLE
issue unfreezing tron using tronscan and ledger

### ISSUE THREAD

**Issue by gshrinkphd** [tronscan/tronscan-frontend#807]
once i confirm on the ledger to unfreeze...i receive an error message stating it may be due to the freeze time (3 days) not achieved...however, the expiration date is many days past....i reinstalled tronscan many times, same issue...please help.
thanks fam : )

**Comment by britestar7** [comment]
Unable to unfreeze tron on tronscan; help would be appreciated!!
