### ISSUE TITLE
trx all missing 

### ISSUE THREAD

**Issue by jaym73caca** [tronscan/tronscan-frontend#815]
logged on this morning everything was there, logged on just now and all of my TRX is gone. all of the tokens that are frozen are also missing ?

**Comment by cccyyc** [comment]
logged in tronscan?

**Comment by jaym73caca** [comment]
I was able to locate it. I do have a quick question though. I have 2
computers, the computer I use regularly is the one that I logged on using
my private keys and nothing was there. This was a day after I used my
private key to log on at work on my work computer. Now for my home computer
I have to log on using my key store files or again there is no balance
shown. I am however still able to use my private keys on my work
computer??? Can you explain why ??

**Comment by cccyyc** [comment]
Use tronscan.org to retry it.
