### ISSUE TITLE
tronscan bugs

### ISSUE THREAD

**Issue by burakpala** [tronscan/tronscan-frontend#817]
Hi,

- Some tokens like mvision are given to me as bonus. How can i sell them? 
- I can't see the details of my transactions like the price of the token?
- I can't buy and sell tokens at a specific price like i do it in other exchanges like Binance. Are you planning to add this function or is it on purpose?
- I can't see the overall balance in trx when i buy other tokens.

Thanks

**Comment by burakpala** [comment]
No need to reply??

**Comment by Rovak** [comment]
i have been closing outdated issues, but to answer your questions:

1. Most tokens are worth nothing or aren't traded on any exchanges
2. This information should now be added to transaction details
3. Limit prices aren't supported in bancor exchange
4. Which balance, of your wallet or the bancor pair?
