### ISSUE TITLE
I am not able to withdrwa TRX from Tronscan!

### ISSUE THREAD

**Issue by maysara1** [tronscan/tronscan-frontend#820]
Hello, 

I am trying to withdraw some TRX from Tronscan but everytime a message saying "Something Wrong Happened During Submittig Your Transaction". 

Would you please help me with this problem?

Regards,
Maysara

**Comment by cccyyc** [comment]
hi，what do you mean by withdraw?
If you want to transfer ,you can clear the cache and retry. It's ok .
