### ISSUE TITLE
Voting does not work

### ISSUE THREAD

**Issue by Suavely1** [tronscan/tronscan-frontend#824]

**Comment by Suavely1** [comment]
> Voting does not work. Does not respond with a message to confirm and then OK. What is going on?

After many tries, voting was accepted. Cannot tell why it works sometimes but othertimes it does not. The last time it took ~ 10 tries to get a confirmation and OK responses.

**Comment by cccyyc** [comment]
Clear the cache and retry it. It's fast in my tronscan.

**Comment by Suavely1** [comment]
Thanks for suggestion. How or where do I clear the cache? Is it part of
Tronscan or Windows?

Thank you,

Bill

William S. Pitts,
224 Bluebird Ln
Folsom, CA 95630-1702 USA

714-330-3890 Cell
pitts.bill@gmail.com
BillPitts@ieee.org

IEEE CS T&C Board, Member At Large
IEEE CS TCPP, Vice Chair, Retired
IEEE IPDPS, Finance Chair, Retired

**Comment by Suavely1** [comment]
Will not accept my votes. Hangs up. How do I "Clear Cache" as suggested?

**Comment by Suavely1** [comment]
Tronscan is broken and I'll delete it. Solution is to go to Tronscan.org. Everything OK now. Was able to sign in, see tokens, freeze, vote, etc.
