### ISSUE TITLE
Freeze / Unfreeze || display error after confirmation || Ledger NANO S Firmware:1.4.2 ||MCU:1.5 ||  tron sw version:0.02 ||

### ISSUE THREAD

**Issue by lbjenious** [tronscan/tronscan-frontend#827]
TRON POWER Unfreeze / Freeze via Ledger NANO-S: Error Message "Something Went Wrong"
NOTE: This started happening after upgrading to MAC OSX Mojave

Pattern1: Freeze TRX -- A MacBook reboot is required. Although the status displays after asked to confirm FREEZE request, after rebooting OSX Mojave, the TRON POWER successfully display the exact amount of TRX.

Pattern2: To UnFreeze TRX:  Multiple Ledger NANO S HW wallet confirmations now required..

<img width="1280" alt="screen shot 2018-11-25 at 6 14 54 pm" src="https://user-images.githubusercontent.com/25964083/48986246-a5373780-f0e0-11e8-9c8c-9a955c207836.png">
<img width="532" alt="screen shot 2018-11-25 at 6 15 10 pm" src="https://user-images.githubusercontent.com/25964083/48986247-a5373780-f0e0-11e8-8d57-2f87c71f058f.png">

**Comment by tlarock80** [comment]
having the same issue.........
