### ISSUE TITLE
[Bounty] Tronscan V2 - Token Creation - StartTime Second - seconds greater than 60 

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#83]
Bug Report
-----
it is posible to set the value of the seconds greater than 60.
this should be checked, it is easy to implement. the validity range should be between 0 and 60
![image](https://user-images.githubusercontent.com/39301026/40824471-8d01fc56-6574-11e8-914b-468aaac428b6.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
01. June 2018 8:00 am (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

Bounty Program
--
https://twitter.com/justinsuntron/status/1002072890349531137

**Comment by Rovak** [comment]
This is an issue in the chrome picker, not much i can do about this
