### ISSUE TITLE
dex error transaction error message 

### ISSUE THREAD

**Issue by daikokufuto** [tronscan/tronscan-frontend#830]
when placing an order on Dex i get a "transaction broadcasting error unable to complete transaction" error message frequently when i place large and small orders/sells causing me to miss crucial entry exit points in my trades. some times i have to log out and back in just to get a order to complete.  what can be done to fix this issue

**Comment by cccyyc** [comment]
https://coin.top/production/js/2018-11-27-14-01-15DEX_guidebook.pdf
