### ISSUE TITLE
Desktop Apps not being supported anymore

### ISSUE THREAD

**Issue by Harlech** [tronscan/tronscan-frontend#831]
Windows is buggy, listing transactions as failed that are actually going through, will not allow voting, multiple issues and has not been updated since July.  Linux distribution doesn't seem to work at all on various Linux platforms.  At this point I am pulling my tokens off my Ledger due to the lack of support in this product.

**Comment by Rovak** [comment]
we are working on getting Ledger ready for the web version of Tronscan. At the same time we are working on Trezor support so it takes a bit longer to get everything ready.

**Comment by tlarock80** [comment]
THANK YOU...........

**Comment by Rovak** [comment]
A work-in-progress can be found at https://tronscan.github.io/tronscan-frontend, you can use your ledger in the web version. for now only freezing, sending and voting have been implemented, the rest will follow soon
