### ISSUE TITLE
LOST SEVERAL COINS in recent exchange on TRON. Some transactions worked, others not only took my TRX but also took my existing coins. 

### ISSUE THREAD

**Issue by gpacker5** [tronscan/tronscan-frontend#834]
in recent exchange on TRON.org Some transactions worked, others not only took my TRX but also took my existing coins.

**Comment by gpacker5** [comment]
I show no tokens owned on 1 coin I exchanged but was able to Exchange a few back to TRX. So, it appears the GLITCH is in listing the AMOUNT OWNED. I expect it will be corrected soon? thanks

**Comment by cccyyc** [comment]
Tronscan are reviewing the unqualified token. So we recommend that you contact the token issuer to see if the token are in the black list of tronscan.
