### ISSUE TITLE
Will not let me sell my SIT

### ISSUE THREAD

**Issue by drakedillan** [tronscan/tronscan-frontend#836]
I'm trading on DEX and It will not let me sell my SIT unless i drop the trx price by 2/3's which is STUPID.... the price on the charts do not reflect this....

**Comment by drakedillan** [comment]
Now it will not even let me sell over 20000 SIT for 20 TRX.... now I know this is a bug....

**Comment by gpacker5** [comment]
My SIT has completely disappeared from my DEX account! It this a temporary glitch?

**Comment by drakedillan** [comment]
Hello,

Please help me get back my TRX from TRON FUN.

[image: image.png]
Dillan T Drake
918-699-9990
Austin, TX
