### ISSUE TITLE
Reynatokens are gone

### ISSUE THREAD

**Issue by skaminski90** [tronscan/tronscan-frontend#838]
Hello i woke up today and my reynatokens are all gone from my tronscan. They are visinle in trxinfo.org but not tronscan.org. can you tell me if this is a temporary bug or if we should go further and investigate. I own 6 million

**Comment by chimcham28** [comment]
I just realized the same thing happened to me too

**Comment by skaminski90** [comment]
Who is here to help? What the heck is going on
