### ISSUE TITLE
no address in receive

### ISSUE THREAD

**Issue by Crypto-Therapist** [tronscan/tronscan-frontend#840]
I created a new wallet on Tronscan. When I go to 'receive' my public address does not appear in the address area - it is blank.

Please advise.

Dr Jan Resnick - janresnick2@gmail.com

**Comment by GarethTRelph** [comment]
I have the exact same issue. I see an address briefly and an address in the previous screen but the QR code reveals nothing The clipboard symbol does nothing and copy/ paste does not work.
