### ISSUE TITLE
Can't vote and my edx aren't showing up

### ISSUE THREAD

**Issue by hbariche** [tronscan/tronscan-frontend#842]
Today my 10m+ of EdX were not found in my wallet. I don't understand, where they moved or hacked. Plz let me know (i don't remember if other tokens were removed but definitely EdX which i bought legally.

2) it has been 2 weeks, i am unable to vote. I can freeze but when i click on vote, i don't get the right page.
Please help, both situations are scaring me.

**Comment by hbariche** [comment]
I still don't understand why no one is replying to my ticket. 3 weeks now that when I click on voting the page doesn't load or give me the block and the transfers page. I can freeze without voting. Please answer me

**Comment by cccyyc** [comment]
Tronscan are reviewing the unqualified token. So we recommend that you contact the token issuer to see if the token are in the black list of tronscan.

**Comment by hbariche** [comment]
So why don't you release them in order for us to move them to a different platform?

Also it has been 3 weeks i can't vote on tronscan, i get my rewards daily and i can freeze, but once i click on vote i don't get the vote page.
Trued on my cell and on my computer.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by cccyyc** [comment]
If you use ledger, you can try this web version:https://tronscan.github.io/tronscan-frontend/#/
This support sending, voting, freezing and unfreezing.
