### ISSUE TITLE
EDX disappeared 

### ISSUE THREAD

**Issue by waynev911** [tronscan/tronscan-frontend#843]
My edx is not showing on tronscan. It is the only one not showing I see a lot of people on telegram complaining about it. It is still showing it on trxplorer.io
TTmNnRgcPimjEBW7aBnie3kQczJBDzTEbY

**Comment by cccyyc** [comment]
Tronscan are checking the scam tokens. So we recommend that you contact the token issuer to see if
the token are in the black list of tronscan.
