### ISSUE TITLE
My SIT disappeared 

### ISSUE THREAD

**Issue by drakedillan** [tronscan/tronscan-frontend#844]
I had 185536 SIT token that still show up in my TRX info but I cannot trade them out....

**Comment by DilanWij** [comment]
Looks like they delisted SIT - I had 67000 tokens - Is there anyway to get  back my trx?

**Comment by cccyyc** [comment]
Tronscan are reviewing the scam tokens. So we recommend that you contact the token issuer to see if
the tokens are in the black list of tronscan.

**Comment by DilanWij** [comment]
Why were these tokens allowed on Dex if they are going to be delisted after we have invested??

So, does this mean that I have now lost my 17K odd tron?

**Comment by MichaelJackson1958** [comment]
The same has now happened with ton and WIN. Completely gone without any warning. 

We need to be warned about delisting so that we can withdraw on time - even if the price crashes at least we get some of our TRX back. 

I find this extremely not professional at all.

**Comment by AKEK114** [comment]
I have issue of missing TRX (Approx 25k) from my Windows Tron Wallet. This I came to know once I tried to check in few weeks time yesterday. My wallet receive address is TDSRex4NF5egmpZdCUhMXjBvt77BGpAvbV

Can anyone help why TRX are not shown or how to recover? I tried few times with TRX customer service and feedback but ALAS they are really not in mood to help apparently .. at least as of now.
