### ISSUE TITLE
SIT Token Gone

### ISSUE THREAD

**Issue by MichaelJackson1958** [tronscan/tronscan-frontend#846]
We were given no warnings, unlike major exchanges, as to the recent delisting of SIT. I strongly believe we should get our TRX back. Totally not professional, and actually "scam" like to disappear overnight. Not a good image for DEX.

**Comment by cccyyc** [comment]
Tronscan are reviewing the scam tokens. So we recommend that you contact the token issuer to see if
the tokens are in the black list of tronscan.
