### ISSUE TITLE
Unable to freeze, unfreeze, and change my vote 

### ISSUE THREAD

**Issue by Sarthakg96** [tronscan/tronscan-frontend#847]
I froze my TRX months ago and voted for a team. I have since received some TRX as rewards which i tried to freeze tonight. After verifying the "freezing transaction" on my nano ledger S, tronscan just displays an error message asking me to try later. Same thing when i try to unfreeze my previously frozen TRX, as well as when i try to change my vote to a new team. I've scoured the internet for solutions, but the only one i could find; logging off, restarting the tronscan app, and logging back on; did not work. Please help!

**Comment by tlarock80** [comment]
SAME ISSUE,,,,,

**Comment by wingot** [comment]
I have the same issue form weeks ago. I see many people with the same issue asking for a solution, but nobody answer

**Comment by GmanDallas** [comment]
Same issue! Cannot Freeze any new TRX, cannot unfreeze any existing and cannot vote!!!
