### ISSUE TITLE
I can't see some tokens on TronScan

### ISSUE THREAD

**Issue by morisveca** [tronscan/tronscan-frontend#848]
Hi,

I can't see 3 tokens on Tronscan.
However, they are shown and can be transferred in Tronwatch and Tronklink.

Are you cleaning scam tokens? they are Bittorrent, WatsonAI and binance token.

**Comment by EverStone** [comment]
Those are definitely scam tokens. My friend lost 56K Watson. They were never given the OK to purchase.

**Comment by cccyyc** [comment]
Tronscan are reviewing the scam tokens. So we recommend that you contact the token issuer to see if
the tokens are in the black list of tronscan.
