### ISSUE TITLE
Please list TronPay back to your DEX

### ISSUE THREAD

**Issue by Savvepro** [tronscan/tronscan-frontend#849]
I notice that TronPay is missing from your Dex and no they are not a scam token, currently founder are working on applying for Malaysian business company registration and suddenly token delisted from tronscan and now cause all investors thought that TronPay is a scam. This is not fair cause we do not receive any notification on the delisting token. Currently their token are running smooth with few investors participate at their token.
Please look in to this, thanks

**Comment by EverStone** [comment]
Tron has new listing rules on DEX. Please read so you get relisted.

**Comment by Savvepro** [comment]
Care to share the link?

**Comment by cccyyc** [comment]
https://coin.top/production/js/2018-11-29-11-52-31Regulations_on_Trading_Pairs.pdf
More：https://tronscan.org/#/exchange?token=dice/TRX&id=43
