### ISSUE TITLE
My coins are missing fron Tronscan Wallet.

### ISSUE THREAD

**Issue by LahootiHyderi** [tronscan/tronscan-frontend#863]
Watsun AI Coin was listed on Tronscan Token Sale labelled with IBM.  It was on top of list on sale for many days. I found it beneficial so bought many of them as it was costly comparing to other coins. today I found no Watsun AI coin in my walled nor it can be found on Tronscan token sale. 

How can we further believe in other coins

**Comment by Shelley46** [comment]
did they return?  why doesn't anyone answer?

**Comment by LahootiHyderi** [comment]
No they didnt

**Comment by cccyyc** [comment]
> I had Binance coins and are no longer there. What's the suggestion here?

Contact the token team to update more info about their token.

**Comment by stevev0** [comment]
I am missing all of my TRC10 Rey. I did not see that they where switching over to TRC20. Today I log into my acct and see 0 Trc10 and 0 trc20 . Did I lose out because of a cut off date? I went to https://reyna.exchange/#/swap , and it shows that I have 0 TRC10 REY to swap?  Any Help!
