### ISSUE TITLE
New Token Never Showed Up

### ISSUE THREAD

**Issue by coreylanzing** [tronscan/tronscan-frontend#864]
I Created the MNON token a few days ago, and it burned my 1240 trx, but the token never was created.  The Asset Issue Hash says the transaction was completes, however i cannot find my new tokens.
45029e1009c0d335f13a6adc942dbe234d22b82d2164e23d00d03a2f0e428dde

**Comment by cccyyc** [comment]
New tokens will be list unless they pass the reviewing of tronscan. You can contact token@trx.market to see the process ～
