### ISSUE TITLE
Tron wallet not sending

### ISSUE THREAD

**Issue by rickyspires** [tronscan/tronscan-frontend#868]
Hello. 

I am using the Tron desktop wallet and I wanted to send to tron to my Huobi wallet but its not sending ? I just stays stuck sending for ever and never sends. 

This is very worrying for me. 

Please look in to it.

Thanks

**Comment by DavidMerino34** [comment]
A mi me pasa lo mismo, lo he probado hacer abriendo mi billetera desde TRONSCAN y mandandome mis TRON a mi cuenta bitfinex y a otra billetera TRON que tengo y se queda enviando eternamente. NO se porque es.....
