### ISSUE TITLE
[Bounty] Tronscan V2 - Topic News - search function faulty - no response

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#87]
Bug Report
--------------
if you use the search function in the news section you will not receive any feedback
![image](https://user-images.githubusercontent.com/39301026/40833607-afea6126-658e-11e8-8abf-87ba6a8e002a.png)

I found the following exception during debugging:
![image](https://user-images.githubusercontent.com/39301026/40833627-bc9dfa54-658e-11e8-9951-613b160ce6b6.png)

call from the website:
 https://api.tronscan.org/api/block?sort=-number&limit=1&count=true&number=looking4

![image](https://user-images.githubusercontent.com/39301026/40833790-30e6c3d2-658f-11e8-9612-530290b0dc1c.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
01. June 2018 10:00 am (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

Bounty Program
--
https://twitter.com/justinsuntron/status/1002072890349531137

**Comment by zk19862018** [comment]
fixed

**Comment by PMD3VSolution** [comment]
Thanks!
