### ISSUE TITLE
voting link broken

### ISSUE THREAD

**Issue by chillslacker** [tronscan/tronscan-frontend#874]
The voting link seems to be broken for the past week?  Has it changed and I can't figure out how to vote now...

**Comment by Suavely1** [comment]
same here. Now when sign in, I get OK, but asks me to "Open Wallet" when tying to see tokens. Just goes in loop.

**Comment by cccyyc** [comment]
You can use https://tronscan.github.io/tronscan-frontend/#/ which support sending, voting, freezing and unfreezing.
