### ISSUE TITLE
Tronscan desktop

### ISSUE THREAD

**Issue by Wrangler57** [tronscan/tronscan-frontend#875]
I am using Ledger Nano S and it keeps giving me an error response when I am trying to freeze my Tron for voting. Hope you have an answer thanks.

**Comment by peteroosterbroek** [comment]
I still have the same problem. Is it already solved on your side?

**Comment by Wrangler57** [comment]
I downloaded latest tronscan i think it is 1.1 It worked and i think it is ok but will have to try it again next month when i freeze more tron.

**Comment by cccyyc** [comment]
hi, if you are using ledger, try use it on https://tronscan.github.io/tronscan-frontend/#/

**Comment by peteroosterbroek** [comment]
It’s working allready. But thanks for youre reaction. 

Met vriendelijke groet,

Peter Oosterbroek
Tel: +31 (0)6 232 01 265
