### ISSUE TITLE
Ledger Nano S w/Tronscan Desktop -- TX send confirm via Nan S keep failing

### ISSUE THREAD

**Issue by lbjenious** [tronscan/tronscan-frontend#879]
Ledger Nano S LCD screen prompt display option to accept transaction... However, when attempting to the accept transaction, Tronscan reports "Something Went Wrong".

Then in about 10 minutes plus or minus, the TRX sent magically show up.

Kindly advise.

Thanks, in advance.

Lionell Brian Jenious

**Comment by cccyyc** [comment]
hi, if you are using ledger, try use it on https://tronscan.github.io/tronscan-frontend/#/
It supports sending, voting, freezing and unfreezing for now.
