### ISSUE TITLE
[Bounty] Tronscan V2 - Apple Iphone X & Iphone8 - Website not Usable

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#88]
Bug Report
-----------
 website via an iPhone is not usable.

Problems
- after registration the website will no longer be displayed
- incorrect table display
- faulty search function
- incorrect scaling of images

![image](https://user-images.githubusercontent.com/39301026/40834126-4748185a-6590-11e8-97ef-165aeec8ab97.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
01. June 2018 10:00 am (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

Bounty Program
--
https://twitter.com/justinsuntron/status/1002072890349531137

**Comment by Rovak** [comment]
Can you send the javascript error that you get after registration?

**Comment by PMD3VSolution** [comment]
no problem, give me some time and I will create a development set
https://developer.apple.com/safari/tools/

**Comment by Rovak** [comment]
This should be fixed now. @PMD3VSolution could you confirm?

**Comment by PMD3VSolution** [comment]
@rovak, yes it is fixed. I have test it on iphone x, iphone8 and ipad pro

**Comment by Rovak** [comment]
Thanks for testing :+1:, closing this issue

**Comment by PMD3VSolution** [comment]
@rovak, You got any slack?  It is good to create a group for joint communication.

**Comment by Rovak** [comment]
Add me to telegram -> @Rovakk
