### ISSUE TITLE
Can't vote for SR 

### ISSUE THREAD

**Issue by ramiscar** [tronscan/tronscan-frontend#880]
When i click the  Vote for Super Representatives is does not send me to the voting page.
It sends me to another page. (see attached screenshot) 
![screenshot](https://user-images.githubusercontent.com/45548597/49350566-66117380-f6ea-11e8-85f5-cdfe0e6590fc.JPG)

**Comment by cccyyc** [comment]
hi, refresh the page and try it again. It should be working.
https://tronscan.org/#/sr/votes
