### ISSUE TITLE
No Open wallet to view

### ISSUE THREAD

**Issue by regnert** [tronscan/tronscan-frontend#881]
Transfered tron to the ledger wallet, nothing has shown up. Been hours.

**Comment by regnert** [comment]
when i add the address is says record not found, but when i search the address online it shows up with a deposit

**Comment by regnert** [comment]
can use web client and its there as well, but of course cannot touch it because i'm not logged in with the ledger

**Comment by thebigkahuna62** [comment]
mine says: no open wallet to view...also last few days ledger keeps conflicting with Windows, says unrecognizable device and disconnects

**Comment by pukkert** [comment]
Same problem here! Any news on what's going on and help is much appreciated.

Message: No open wallet to view.

Tronscan on Mac.

**Comment by Jdog88** [comment]
the wallet opened after 3 tries, I plugged in the ledger and let it sit for few minutes. try that see if it works..

**Comment by thebigkahuna62** [comment]
nothing works...blockheight shows 0, transactions lasts day 0, etcetera also

**Comment by jakarta404** [comment]
Same issue as TBK62 - Brower support on or off doesn't matter - Ledger is not working "No Open Wallet to View"

**Comment by geoplane** [comment]
Me as well! It's been well over 10 hours... same message (No Open Wallet To View) WOW!!!

**Comment by geoplane** [comment]
> 
> 
> the wallet opened after 3 tries, I plugged in the ledger and let it sit for few minutes. try that see if it works..

Not working... where is the developer of this wallet?

**Comment by geoplane** [comment]
I'm hearing they're going to initiate ledger support on https://tronscan.org/#/ estimated ETA is unknown?

**Comment by thebigkahuna62** [comment]
still no news ?? been almost 24 hrs..still no open wallet to view.

**Comment by thebigkahuna62** [comment]
developer is sr cryptoguyinza

**Comment by cccyyc** [comment]
hi, if you are using ledger, try use it on https://tronscan.github.io/tronscan-frontend/#/
It supports sending, voting, freezing and unfreezing for now.

**Comment by CryptoPlayer99** [comment]
Same with my wallet. when i open Tronscan it shows 0 for everything and i cannot log in. Is someone working on this.

**Comment by thebigkahuna62** [comment]
worked once this morning 1st time in 3 days, does not work now. Tronscan
does not have a ledger option on the link you supplied

**Comment by thebigkahuna62** [comment]
sorry the one jasonwain supplied

**Comment by thebigkahuna62** [comment]
still not working ??

**Comment by thebigkahuna62** [comment]
still not working ?

**Comment by jasonswain** [comment]
@thebigkahuna62 hi, i didnt supply a link, that was shared by  @cccyyc

I tried it and it did work in as much as it allowed me to view my wallet at least (which wasa relief), but when I tried an action (freezing some tron) it seemed to lock up my ledger and display a duff character on the screen, so i decided to stop and wait for the full release in the hope that it wouldnt be bugged, or better still that someone would fix the tronscan app

**Comment by thebigkahuna62** [comment]
If someone has luck with the wallet please post it...even though we are all
in a big hole ...will be great when it jumps big :)

**Comment by thebigkahuna62** [comment]
if i open two wallet tabs one of them gets all the info so it will open ie:
all the nodes, transactions etc at the bottom of the page. The close the
other tab without the updated daily functions

**Comment by thebigkahuna62** [comment]
doesent work perfectly but it works

**Comment by TopCapCrypto** [comment]
Hi, I'm having same problem. Ledger plugged in. Opened Tron on my ledger. Address verified on tronscan, then No Open Wallet To View.

Gonna miss my BTT airdrop
