### ISSUE TITLE
Issues With Accessing Tron Account On Ledger

### ISSUE THREAD

**Issue by QuezyJ** [tronscan/tronscan-frontend#883]
Is anybody else having issues with accessing Tron Wallet on Ledger Nano S? I've done all the steps correctly and it keeps saying NO WALLET TO VIEW or something of that nature. I've deleted and redownloaded everything. I've signed in and signed out. Every single thing that I know, and I keep getting nothing. Is there some kind of update that is being worked on right now that is keeping users from accessing their wallets? I've noticed that there has been other posts about this as well.

**Comment by pukkert** [comment]
Same here! Help is much appreciated!

**Comment by TheOneFirstOne** [comment]
I am having the same problem. I open TronScan, then clicking on the Ledger the system shows my account # but never opens my wallet.

**Comment by Dirkbelgie** [comment]
i also can not see my wallet(account) when i connect with ledger  When i copied adres to browser and with transcan browser  i see my account But NOT with Ledger  Is this problem ledger or tron???

**Comment by 2250Tron** [comment]
I looked on reddit and apparently rovak is working on a fix, what ever Rovak is?

**Comment by Dirkbelgie** [comment]
got this mail from tron   must work again now with this link
Hi，
tronscan web version are supporting ledger now. You can use https://tronscan.github.io/tronscan-frontend for some basic functions like sending, voting, freeze and unfreeze.
