### ISSUE TITLE
Tronscan token disappearance continues.

### ISSUE THREAD

**Issue by LahootiHyderi** [tronscan/tronscan-frontend#885]
Today again I found my wallet empty from Tarq Tokens, USA Coins, Retro and few more are missing from my wallet. Then why we voted for. What we get? What the hanky panky is being observed by Tronscan. 

Very sadly saying that I use to Love Tron and was crazy about it. but now my faith is getting broken day by day. Here at GitHub, there is also no remedy rather we just only submit our voice which is always unheard. 

If I dont get satisfied answer or remedy, I will go for Social Media which is open house where we can share what is happening and tell the whole world. I am so sad to shout against my Favorite coin.

**Comment by Savvepro** [comment]
That's makes me too and not sure why they delisted a token without any announcememt

**Comment by LahootiHyderi** [comment]
Guys start the strong campaign against them but if we keep on asking and
wondering hither and thither then they will keep on doing this to us.

**Comment by LahootiHyderi** [comment]
well friends finally I found all my token disappeared from Tronscan. You can find all of your tokens at www.trxplorer.io . but still 1 flaw is there that why they moved coins without intimating its community.

**Comment by Fwelco** [comment]
my tokens are also not visible in tronscan, if i log on to tronwatch, i can see all tokens and i can make transactions with the tokens i created, they just dont uppear in tronscan anymore. i hope this issue will be fixed soon. i have  worried people contacting me because of their tokens disappearing, and new clients that cant get hold of the token. its okay if tokens i created are not added to the tronscan dex, but they should be visible in the wallets of people that already invested.

**Comment by LahootiHyderi** [comment]
Well now problem is resolved. All tokens can be found at www.trxplorer.io
so go n sign in ur acount there

**Comment by Savvepro** [comment]
TronScan started to act like a centralized platform and guess they want to be paid to list the delisted token. They are following ETH path. Only those small token that get listed either they paid or created by them alone.

**Comment by LahootiHyderi** [comment]
Here I have my own view. Big difference between Eth and Trx. Tron will hit
the heights. Just wait n watch. I only request team of Tron to keep
community completely aware of any change that happens like transfering
coins from wallet to trxplorer

**Comment by hammish1973** [comment]
i lost all mine to had like 28 diffrent tokens with over 3000 in one of them all gone what a scam

**Comment by LahootiHyderi** [comment]
Nothing is gone. All ur coins are at www.trxplorer.io go there signin and
find ur tokens

**Comment by cccyyc** [comment]
Tronscan are reviewing the scam tokens. So we kindly recommend that you contact the token issuer to see if the tokens are in the black list of tronscan.

**Comment by AKEK114** [comment]
I have issue of missing TRX (Approx 25k) from my Windows Tron Wallet. This I came to know once I tried to check in few weeks time yesterday. My wallet receive address is TDSRex4NF5egmpZdCUhMXjBvt77BGpAvbV

Can anyone help why TRX are not shown or how to recover? I tried few times with TRX customer service and feedback but ALAS they are really not in mood to help apparently .. at least as of now.
