### ISSUE TITLE
Missing Token

### ISSUE THREAD

**Issue by mattygm** [tronscan/tronscan-frontend#886]
Hi there,

I seem to have lost a number of token i had accumulated in my TronScan account especially over 1600 Tarquin which are not there anymore, please can you advise?

Thanks,
Matt.

**Comment by hammish1973** [comment]
i had also over 3000 of the same token all goon

**Comment by mattygm** [comment]
Not good at all that like, needs looking into asap.

**Comment by hammish1973** [comment]
well if i dont get back every thing i have lost i will be removing all my trx out of my troscan wallet and will not be using this wallet again  and i will be letting all my friends on face book know about my trouble with tron scan wallet
________________________________

**Comment by mattygm** [comment]
Definitely, same here.

**Comment by hammish1973** [comment]
i think there are a lot of people that got sucket in here

**Comment by mattygm** [comment]
Looks like it on the Facebook TRON (TRX) page a load of panic - looks like they are aware of it and looking into the issue.

**Comment by hammish1973** [comment]
Lets hope they fix this or this may hurt them big time



Sent on the go with Vodafone


-------- Original message --------

**Comment by cccyyc** [comment]
hi, it's not a bug. Tronscan has hidden some tokens which are probably scam tokens.
