### ISSUE TITLE
Issues using Ledger Nano S

### ISSUE THREAD

**Issue by PabloTheViking** [tronscan/tronscan-frontend#887]
Hello,
I am using desktop version of Tronscan with Ledger Nano S. It has been working fine until recently. Suddenly when I try to sign off transactions with the Nano S I keep getting error messages, it happens basically with anything I want to do that requires confirmation from the Nano S device. I am able to log on to my account with the Nano S, but not able to do anything. Please advise!!

**Comment by cccyyc** [comment]
hi, if you are using ledger, try use it on https://tronscan.github.io/tronscan-frontend/#/
It supports sending, voting, freezing and unfreezing for now.

**Comment by PabloTheViking** [comment]
Ok. Thanks!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
