### ISSUE TITLE
bug in my tronscan wallet

### ISSUE THREAD

**Issue by hammish1973** [tronscan/tronscan-frontend#889]
hi there what i have seen in my tron scan wallet is after i freeze and vote i get some tokes back for voting now i had like 15 odd different tokens from voting and one of them i had over 3000 tokens but i see in my tron scan wallet all my tokens have been taken so i am now looking to close up my tron scan wallet as i no longer trust it i have given my key to no one but yet i have lost all my tokens with in my wallet

**Comment by cccyyc** [comment]
hi, your token are not missed. Just because tronscan has hidden some scam tokens.

**Comment by hammish1973** [comment]
So the tokens i have been getting are scam tokens


Sent on the go with Vodafone


-------- Original message --------

**Comment by hammish1973** [comment]
so are u saying all the token i got in my tron scan wallet for freezeing and voting are scam tokens
________________________________

**Comment by cccyyc** [comment]
Tronscan are reviewing the tokens. if the tokens provide enough information, they will be re-listed in tronscan.

**Comment by hammish1973** [comment]
is that relisted to my tron scan wallet

________________________________

**Comment by cccyyc** [comment]
Which token? I'll help u check it.

**Comment by hammish1973** [comment]
Tarquin<https://tronscan.org/#/token/Tarquin/TV6qcwSp38uESiDczxxb7zbJX1h2LfDs78> TronLottery<https://tronscan.org/#/token/TronLottery/TGQwBNht8h3zev4gBtDMoQjWE2WJm1Zr9B> ofoBike<https://tronscan.org/#/token/ofoBike/THG48yHsR6inxrCJk2hhxZPsFLq1ehP88V> BitTorrent<https://www.trxplorer.io/token/BitTorrent> Bithumb<https://www.trxplorer.io/token/Bithumb> Durex<https://www.trxplorer.io/token/Durex> HuobiToken<https://www.trxplorer.io/token/HuobiToken> IPFS<https://www.trxplorer.io/token/IPFS> James<https://www.trxplorer.io/token/James> MacCoin<https://www.trxplorer.io/token/MacCoin> Messenger<https://www.trxplorer.io/token/Messenger> NBACoin<https://www.trxplorer.io/token/NBACoin> Pornhub<https://www.trxplorer.io/token/Pornhub> RingCoin<https://www.trxplorer.io/token/RingCoin> TRXTestCoin<https://www.trxplorer.io/token/TRXTestCoin> Tarquin<https://www.trxplorer.io/token/Tarquin>
Tarquin - Tarq token tracker, price and informations - trxplorer.io<https://www.trxplorer.io/token/Tarquin>
Get all informations about Tarquin token on Tron blockchain
www.trxplorer.io

binance<https://www.trxplorer.io/token/binance> dice<https://www.trxplorer.io/token/dice> ofoBike<https://www.trxplorer.io/token/ofoBike>   this is all the coins i get from freezing and voting
ofoBike - ofo token tracker, price and informations - trxplorer.io<https://www.trxplorer.io/token/ofoBike>
Get all informations about ofoBike token on Tron blockchain
www.trxplorer.io


binance - BNC token tracker, price and informations - trxplorer.io<https://www.trxplorer.io/token/binance>
Get all informations about binance token on Tron blockchain
www.trxplorer.io


RingCoin - RC token tracker, price and informations - trxplorer.io<https://www.trxplorer.io/token/RingCoin>
Get all informations about RingCoin token on Tron blockchain
www.trxplorer.io


Pornhub - PHB token tracker, price and informations - trxplorer.io<https://www.trxplorer.io/token/Pornhub>
Get all informations about Pornhub token on Tron blockchain
www.trxplorer.io


NBACoin - NBA token tracker, price and informations - trxplorer.io<https://www.trxplorer.io/token/NBACoin>
Get all informations about NBACoin token on Tron blockchain
www.trxplorer.io


MacCoin - Mac token tracker, price and informations - trxplorer.io<https://www.trxplorer.io/token/MacCoin>
Get all informations about MacCoin token on Tron blockchain
www.trxplorer.io


James - king token tracker, price and informations - trxplorer.io<https://www.trxplorer.io/token/James>
Get all informations about James token on Tron blockchain
www.trxplorer.io


IPFS - IPFS token tracker, price and informations - trxplorer.io<https://www.trxplorer.io/token/IPFS>
Get all informations about IPFS token on Tron blockchain
www.trxplorer.io


HuobiToken - HT token tracker, price and informations - trxplorer.io<https://www.trxplorer.io/token/HuobiToken>
Get all informations about HuobiToken token on Tron blockchain
www.trxplorer.io


Durex - drx token tracker, price and informations - trxplorer.io<https://www.trxplorer.io/token/Durex>
Get all informations about Durex token on Tron blockchain
www.trxplorer.io


Bithumb - BTM token tracker, price and informations - trxplorer.io<https://www.trxplorer.io/token/Bithumb>
Get all informations about Bithumb token on Tron blockchain
www.trxplorer.io


[https://coin.top/production/js/2018-08-22-09-02-22_share-logo.png]<https://tronscan.org/#/token/ofoBike/THG48yHsR6inxrCJk2hhxZPsFLq1ehP88V>

TRON BlockChain Explorer<https://tronscan.org/#/token/ofoBike/THG48yHsR6inxrCJk2hhxZPsFLq1ehP88V>
Tronscan allows you to explore and search the TRON blockchain for transactions,accounts,tokens,nodes,votes and market information.
tronscan.org


[https://coin.top/production/js/2018-08-22-09-02-22_share-logo.png]<https://tronscan.org/#/token/TronLottery/TGQwBNht8h3zev4gBtDMoQjWE2WJm1Zr9B>

TRON BlockChain Explorer<https://tronscan.org/#/token/TronLottery/TGQwBNht8h3zev4gBtDMoQjWE2WJm1Zr9B>
Tronscan allows you to explore and search the TRON blockchain for transactions,accounts,tokens,nodes,votes and market information.
tronscan.org


[https://coin.top/production/js/2018-08-22-09-02-22_share-logo.png]<https://tronscan.org/#/token/Tarquin/TV6qcwSp38uESiDczxxb7zbJX1h2LfDs78>

TRON BlockChain Explorer<https://tronscan.org/#/token/Tarquin/TV6qcwSp38uESiDczxxb7zbJX1h2LfDs78>
Tronscan allows you to explore and search the TRON blockchain for transactions,accounts,tokens,nodes,votes and market information.
tronscan.org


________________________________

**Comment by hammish1973** [comment]
Tarquin<https://tronscan.org/#/token/Tarquin/TV6qcwSp38uESiDczxxb7zbJX1h2LfDs78> when will this be apart of the DEX TRADING plat form with in the tron scan wallet
________________________________
