### ISSUE TITLE
Hidden coins on Tronscan.org

### ISSUE THREAD

**Issue by Mikeyf74** [tronscan/tronscan-frontend#890]
Hi, a lot of my coins have disappeared on Tronscan.org - They appear on the blockchain but are inaccessible from my wallet - See address  TH78GEUdvyCRyfr9HLfyjG7vy1j8uy5kVg

If you check the same address using: - https://www.trxplorer.io/address/TH78GEUdvyCRyfr9HLfyjG7vy1j8uy5kVg#/tokens

You will see they exist, Tarquin for example is no longer showing on Tronscan

How are these coins being hidden or removed from Tronscan.org, this is very alarming

**Comment by cccyyc** [comment]
Tronscan are reviewing the scam tokens. So we kindly recommend that you contact the token issuer to see if the tokens are in the black list of tronscan.
