### ISSUE TITLE
The token I created, FlyingFux (FUX) is completely missing...

### ISSUE THREAD

**Issue by kapteur** [tronscan/tronscan-frontend#891]
Yesterday, while attempting to send our airdrops to the FlyingFux (FUX) community, I noticed that the FlyingFux token was not showing up as an option to send, even though there was 68b FlyingFux in the wallet, which I could clearly still see there when I accessed the wallet through another TRX Wallet.

I then logged into the site this morning to see if the issue was fixed and much to my dismay it was worse, now not only was FlyingFux not showing up in my wallet balances, but the creation page or anything associated wasn't showing up either and was being redirected to the home page, as if someone removed all traces of the token from your site.

[](https://tronscan.org/#/token/FlyingFux/)

[](https://www.tronscan.org/#/token/FlyingFux/TTEnSGJcexm7jxU9vFRuqr7BMHVmjnovrk)

Can you please look into this and please explain what is occurring, my team is concerned there may be some tampering on your end by someone who is related to Trxinfo.org, specifically someone by the name Randy Kar, since they were caught redhanded stealing large amounts of tokens from our wallets and then have been doing malicious things towards us ever since when we said we'd expose their thefts to the public.

**What if trxinfo DEX is a scam?**
https://medium.com/@milevastankovic/what-if-trxinfo-dex-exchange-is-a-scam-8c13dafc94f1

**Completely missing!:**
https://tronscan.org/#/token/FlyingFux/
and
https://www.tronscan.org/#/token/FlyingFux/TTEnSGJcexm7jxU9vFRuqr7BMHVmjnovrk

No longer feeling secure through Tronscan.org, I used another Wallet to create a new wallet address and transferred as many of my tokens there as I could until this issue has been resolved.

Please look into this immediately, if random people with malicious intentions are able to manipulate the network at will, people will loose faith in network and will jump ship to something that is more secure.

For the sake of the entire TRON/TRX network and everyone supporting it, please look into this immediately.

Thank you and best regards,

Chris

**Comment by kapteur** [comment]
https://medium.com/@milevastankovic/what-if-trxinfo-dex-exchange-is-a-scam-8c13dafc94f1

**Comment by kapteur** [comment]
**Completely missing!:**

https://tronscan.org/#/token/FlyingFux/

and

https://www.tronscan.org/#/token/FlyingFux/TTEnSGJcexm7jxU9vFRuqr7BMHVmjnovrk

**Comment by cccyyc** [comment]
Hi, if your token info are insufficient，it may probably hidden by tronscan. Newly issued tokens also need a censor by tronscan before it is listed in the page. You can contact token@trx.market to learn more about the process.
