### ISSUE TITLE
[FRQ] Tronscan V2 - Create Token - required fields should be marked

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#9]
Feature Request
------------------
required fields should be marked in the form
![image](https://user-images.githubusercontent.com/39301026/40225396-33f62a92-5a89-11e8-9784-6feb72444025.png)

possible solution:
-------------------
![image](https://user-images.githubusercontent.com/39301026/40225633-e64f9cb4-5a89-11e8-8242-56663630177b.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

**Comment by Rovak** [comment]
Fixed
