### ISSUE TITLE
Mising tokens in Tronscan account,

### ISSUE THREAD

**Issue by diamonds460800** [tronscan/tronscan-frontend#902]
Hello I tried to send some token I have via my telegraph account via tronscan account to another wallet.  In my tronscan where I have been buying tokens via telegraph exhanges  .   When I log into my Tronscan my tokens I have are not showing.   They are missing.  But in the balance in the telegraph tronscan balance they are there.    When I check TRXplorer.io  they are also there..   Is there a bug in the tronscan account  I cant seem to see many of my tokens to send .     I have them ,  there is a record of me buying and holding them. they are just not there to send.    The balace via telegraph has them   but not when I actually log into tronscan . they are missing.. can someone help.  thank you    my public address is  TDFhb1NUpZuJ2UnGf7QiVhMrxvfJXNSeHG    thank you  jim

**Comment by diamonds460800** [comment]
BTW one of the many that are missing is  TRONBITCOIN  i know its not a scam coin.  it is missing out of my Tronscan account.  but shows in my balance via the telegraph/seedit  tronsan app. account

**Comment by mpmprudencio** [comment]
Also can't find the token that I created and some ones that I participated also are not showing in my wallet. If not stolen, why hide the tokens? Where is all the decentralized and freedom talking? All this comes somehow against blockchain principles, can't expect Tron to go up manipulated this way... :(

**Comment by jp222222** [comment]
I'm dealing with the same problem, missing 100,000,000 RET fron tronscan wallet I never moved it.
