### ISSUE TITLE
Tronscan not showing address

### ISSUE THREAD

**Issue by GarethTRelph** [tronscan/tronscan-frontend#907]
I have tried everything possible my end with getting an address so I can move my Tron TRX to my Ledger Nano S.
I have uninstalled and reinstalled software again and again.
I have the latest firmware.
Everything is as it should be but no address appears when I open the wallet.
I am told I am connected but still no address?

Someone needs to fix this as I am not the only person having issues.
Regards,

Gareth Relph

**Comment by Marcvanb** [comment]
same here. It would be great to get an answer to this topic
