### ISSUE TITLE
[Bounty][Security] Tronscan V2 - TLS certificate - too many unsafe SAN entries - fishing attack

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#91]
Security Report
----------
the certificate used by tronscan.org is a multi-server certificate with wildcard information from other domains. many websites can hide behind a wildcard certificate. in combination with a DNS redirection, an attacker can redirect the user to another server that uses the same certificate. the private key is the same! the ordinary user can no longer distinguish whether the website is real or recreated.

the current tronscan certificate has the following SAN entries:
DNS-Name=sni64554.cloudflaressl.com
DNS-Name=*.4ji62books.cf
DNS-Name=*.67x8abooks.gq
DNS-Name=*.ajrouses.gq
DNS-Name=*.as-altamoda.com.ar
DNS-Name=*.bitdog.dog
DNS-Name=*.booktripeasy.com
DNS-Name=*.boostertube.com
DNS-Name=*.boyscasting.org
DNS-Name=*.coin.top
DNS-Name=*.cyclopsci.com
DNS-Name=*.flokia.review
DNS-Name=*.guestblogging.com
DNS-Name=*.gunnisonconstructionandseptic.com
DNS-Name=*.hillfarmfinest.com
DNS-Name=*.hugeast.com
DNS-Name=*.individualeconomics.com
DNS-Name=*.lskz.org
DNS-Name=*.mannanewsonline.com
DNS-Name=*.marroclooks.tk
DNS-Name=*.mayomelz.com
DNS-Name=*.n6fohbooks.ga
DNS-Name=*.onmlm.ru
DNS-Name=*.pollyvendetti20ctqcz.ml
DNS-Name=*.roeckitts.gq
DNS-Name=*.sell-pilbha.ml
DNS-Name=*.sell-szduqh.ga
DNS-Name=*.seriousbloggersonly.com
DNS-Name=*.spbfaberlic.ru
DNS-Name=*.stateoftrondapps.com
DNS-Name=*.sunciztyltds.ga
DNS-Name=*.telemaccos.cf
DNS-Name=*.thisendout.com
DNS-Name=*.tron.network
DNS-Name=*.trondapp.org
DNS-Name=*.tronscan.io
DNS-Name=*.tronscan.org
DNS-Name=*.zabumba.net
DNS-Name=4ji62books.cf
DNS-Name=67x8abooks.gq
DNS-Name=ajrouses.gq
DNS-Name=as-altamoda.com.ar
DNS-Name=bitdog.dog
DNS-Name=booktripeasy.com
DNS-Name=boostertube.com
DNS-Name=boyscasting.org
DNS-Name=coin.top
DNS-Name=cyclopsci.com
DNS-Name=flokia.review
DNS-Name=guestblogging.com
DNS-Name=gunnisonconstructionandseptic.com
DNS-Name=hillfarmfinest.com
DNS-Name=hugeast.com
DNS-Name=individualeconomics.com
DNS-Name=lskz.org
DNS-Name=mannanewsonline.com
DNS-Name=marroclooks.tk
DNS-Name=mayomelz.com
DNS-Name=n6fohbooks.ga
DNS-Name=onmlm.ru
DNS-Name=pollyvendetti20ctqcz.ml
DNS-Name=roeckitts.gq
DNS-Name=sell-pilbha.ml
DNS-Name=sell-szduqh.ga
DNS-Name=seriousbloggersonly.com
DNS-Name=spbfaberlic.ru
DNS-Name=stateoftrondapps.com
DNS-Name=sunciztyltds.ga
DNS-Name=telemaccos.cf
DNS-Name=thisendout.com
DNS-Name=tron.network
DNS-Name=trondapp.org
DNS-Name=tronscan.io
DNS-Name=tronscan.org
DNS-Name=zabumba.net

solution: 
------
use a secure single server certificate or a multi server certificate without foreign domains

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
01. June 2018 03:00 pm (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

Bounty Program
--
https://twitter.com/justinsuntron/status/1002072890349531137

**Comment by Rovak** [comment]
Duplicate of #17
