### ISSUE TITLE
Voting by Ledger Nano S is not possible

### ISSUE THREAD

**Issue by ilDraken** [tronscan/tronscan-frontend#917]
I converted my TRX to Tron Power, but when I try to vote through the Ledger Nano S, Tronscan always returns error.
How can I solve?

I tried on Windows OS and it works. Not possible on Mac OS.

**Comment by fomman** [comment]
ok, let me help you buddy ))

**Comment by dandoestech** [comment]
I had this issue as well. First make sure that the ledger nano has not locked  you out by entering your passcode into the nano. 

Also make sure  you are running the Tron app on the ledger-

After you confirm the number of trx you want to freeze (make sure this is a whole number), you will get a request to confirm the transaction on the nano. Click the right button to approve and you will see a success trx frozen in the prompt on tron scanner desktop. 

this still failed for me-but after a pc restart and unplugging the nana and back in and launching both the ledger live and tronscanner desktop apps it worked

**Comment by ilDraken** [comment]
I've tried all your solutions, but Tronscan works really bad. I am very tempted to sell all the TRX units and exit the project.

Thank you.
