### ISSUE TITLE
Tronscan win-desktop

### ISSUE THREAD

**Issue by JC321Card** [tronscan/tronscan-frontend#922]
Hello,
My Tronscan win-desktop with my Ledger Nano S had been working fine from the time I installed it up until three or four days ago. Now I have not been able to sign in to my Tronscan account for the past three or four days. When I try to sign in with my Leger, a Tronscan pop up message comes up saying "No open wallet to view". I have not been able to connect with my Tronscan account to manage my account.

**Comment by Rovak** [comment]
Please use https://tronscan.github.io/tronscan-frontend for the new tronscan with ledger support

**Comment by JC321Card** [comment]
Thank you Rovak. I appreciate your help.
