### ISSUE TITLE
DEX

### ISSUE THREAD

**Issue by Fabjoh** [tronscan/tronscan-frontend#926]
I am on the https://tronscan.github.io logged in with Ledger but when I try to trade on DEX nothing happen? Do I miss a point ?
Thanks

**Comment by Fabjoh** [comment]
And by the way the Ledger is configured for web access. I have tried as well with Opera and Safari, none of them are working.
Any Idea why is does not work ?

**Comment by mistahmedia** [comment]
I have same issue ... exactly the same as you describe ... I was trying to trade TERC and nothing happened ... even when dropping price way, way down
