### ISSUE TITLE
Error message when trying to Vote...

### ISSUE THREAD

**Issue by TonyMcC** [tronscan/tronscan-frontend#929]
Comes up with Error screen saying "something went wrong..."

**Comment by htlee80** [comment]
I have the same error when I tried to vote for a Tron super representative 

<img width="623" alt="error voting screen shot 2018-12-26 at 9 03 56 pm" src="https://user-images.githubusercontent.com/46168363/50463558-2ab53e00-0952-11e9-875b-6143f6a6d407.png">
