### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by perry123xyz** [tronscan/tronscan-frontend#93]
I am trying to create a coin or token but whenever I land on the: https://tronscan.org/#/tokens/create page it says I will need to log in to make use of this functionality so I am unable to log in. I have created a github.com account and a wallet should that not allow me to be logged in?

**Comment by PMD3VSolution** [comment]
I had the same problem, please use firefox or chrome and clear the protocoll.

Please press F12 and select the browser console. Please send me the browser console log,

Regards, PM

**Comment by Rovak** [comment]
You need to open a wallet to be able to create tokens
