### ISSUE TITLE
tronscan issues.  

### ISSUE THREAD

**Issue by Lstork121** [tronscan/tronscan-frontend#930]
having problems logging in with ledger once on tronscan.   doesn't even show votes.  Could use help thanks.

**Comment by cccyyc** [comment]
Use this web version and retry it!
https://tronscan.github.io/tronscan-frontend/#/

**Comment by Lstork121** [comment]
Thanks cccyyc for your help. I can actually see my coins on it but now i cant vote on it.  I dont see a place to vote.  Any suggestions on that part? Thanks

**Comment by Lstork121** [comment]
I found where to vote at. Thanks for your help on other issues.

**Comment by cccyyc** [comment]
You are welcome.
