### ISSUE TITLE
Ledger Nano not working 

### ISSUE THREAD

**Issue by Technard** [tronscan/tronscan-frontend#931]
I cannot open Ledger nano Tron wallet with Tronscan... It worked the last 2 weeks and now nothing. Please help! Thank you

**Comment by cccyyc** [comment]
Use this web version and retry it!
https://tronscan.github.io/tronscan-frontend/#/

**Comment by idforcrypto** [comment]
hi,
When will the support for TRC20 token be enabled for the ledger wallet on tronscan web.

Currently the trc20 dont show and we cannot transfer or freeze any trc20

**Comment by cccyyc** [comment]
> hi,
> When will the support for TRC20 token be enabled for the ledger wallet on tronscan web.
> 
> Currently the trc20 dont show and we cannot transfer or freeze any trc20

We wil support that soonl

**Comment by mikeyg4** [comment]
Unable to access Ledger Tronscan, just says no open wallet to view...any answers?
