### ISSUE TITLE
Freezing and Voting

### ISSUE THREAD

**Issue by Terrygil** [tronscan/tronscan-frontend#932]
Using a Nano Ledger S I am getting "ERROR" when I try to freeze tron and I get the same message when I vote. After several (probably 8-15) attempts it will accept my request. Is this a bug in the app or is it a bug in the Ledger? Are there any suggestions to correct problem noted above?

**Comment by cccyyc** [comment]
Use this web version and retry it!
https://tronscan.github.io/tronscan-frontend/#/

**Comment by RW80** [comment]
Same here,I keep getting errors, when trying to freeze.

**Comment by UnBuenCamino** [comment]
Did you make any improvements, hope so.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Rovak** [comment]
I closed this issue to cleanup duplicate reports, the issue is still being looked into

**Comment by UnBuenCamino** [comment]
Freezing and voting is really frustrating, I'll give you more feedback if you want, what issue# should I post against.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Rovak** [comment]
use https://tronscan.org instead of the desktop client

**Comment by Terrygil** [comment]
I couldn't use Firefox browser, I tried it on Brave browser and it works
like it should.

**Comment by UnBuenCamino** [comment]
Today, March 26, tried again to freeze and vote my TRX, using, as you suggested, Tronscan.org and Ledger Nano S.  It just doesn't work.  Very frustrating.  Same problems as always as I documented on previous posts.  Any suggestions.  It really diminishes my confidence in Tron.

Harlan

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
