### ISSUE TITLE
Unable to send tokens, unable to vote!

### ISSUE THREAD

**Issue by cryptozwerg** [tronscan/tronscan-frontend#933]
What the fuck is going on?! Why can not vote, nor send my TRX to another address (because I want to vote God damn it!)?! WTF is wrong with you?! I will start putting negative reviews EVERYWHERE, this is simply unacceptable.

**Comment by cccyyc** [comment]
Use this web version and retry it!
https://tronscan.github.io/tronscan-frontend/#/
