### ISSUE TITLE
I can´t vote, freeze or unfreezeTRX on Tronscan

### ISSUE THREAD

**Issue by wingot** [tronscan/tronscan-frontend#934]
Since weeks ago I have no way to vote, freeze or unfreeze TRX on Tronscan. The TRX frozen reamains frozen but I can´t vote with them. But I can´t have access to my TRX, because they are frozen.
I see several people with the same issue but nobody answers. 
This issue has been there for a while, so it doesn´t seem to be something "temporary". At this point I would like to just unfreeze my TRX and forget about voting anymore, since it seems to involve some risk.

Anyone knows any support for Tronscan where we can get help with this issue?

**Comment by chuckyloco** [comment]
I 'am like you still waiting for a answer…. not going to put my trx in the freeze anymore got the rest in the wallet out of there don't trust it anymore. Waiting for like more than 3 months and still nobody that helping

**Comment by wingot** [comment]
Ok. I solved the issue. Instead of opening the desktop app, I went to this page: https://tronscan.github.io/tronscan-frontend/#/
It is the same that the desktop app. I saw my TRX. I was able to frozen them again and vote.
Most likely it is an error of the desktop app what was causing the
 issue

**Comment by wingot** [comment]
And, by the way, when I used Firefox I couldn´t open the wallet. Using chrome soled that too
