### ISSUE TITLE
FREEZE for energy showing error when ledger wallet used

### ISSUE THREAD

**Issue by idforcrypto** [tronscan/tronscan-frontend#937]
hi,

The freeze for Enerygy token is showing error window and not frrezing trx for energy.

https://tronscan.github.io/tronscan-frontend/ 

![image](https://user-images.githubusercontent.com/41203090/50036292-80423000-ffcd-11e8-97cb-7d4451a473d2.png)

**Comment by GarethTRelph** [comment]
I am having the same issue. I cannot freeze TRX for Energy but I can for Tronpower.
