### ISSUE TITLE
40 digits instead of 34 digits required for BTC withdrawal-100USD BTC stuck in the BTC part of my tron.network wallet

### ISSUE THREAD

**Issue by bennethcc** [tronscan/tronscan-frontend#94]
I've been on this for days now, please HELP ME..! Immediately I registered on tron.network(personalcenter) I transfered 100USD in BTC to my wallet in an attempt to purchase trx. Now I've learned how to get trx from Binance but my 100bucks is still stuck in the BTC part of my wallet. I have over 100TRX on the TRX part of the wallet but if I want to withdraw the BTC I cant submit because the address requires 40 digits for me to be able to click submit and btc address is usually 34 digits. Ive been able to transfer the ETH and TRX which is up to 40 but not BTC. What do I do?

**Comment by conglinduye** [comment]
Thank you for your support of tron。The problem has been solved. Please go to tron.network for normal withdrawal.

**Comment by conglinduye** [comment]
Thank you for your support of tron。The problem has been solved. Please go to tron.network for normal withdrawal.
