### ISSUE TITLE
BUG WALLET TRON UNLIMITED

### ISSUE THREAD

**Issue by markfrez** [tronscan/tronscan-frontend#95]
BUG WALLET TRON UNLIMITED. WITH DYNAMIC IP ADDRESSES. Limit the wallet by email as well.

**Comment by PMD3VSolution** [comment]
It is normal to create multiple wallets for one person.  This makes it possible to distribute values.  Tron trx claims to give everyone access to the tron network, regardless of origin, age or address.  This way you can also separate certain businesses, an account for business with friends, an account for personal multimedia, an account for your son.  This is quite normal and is also the case with btc or ethscan!
