### ISSUE TITLE
error on freezing or voting

### ISSUE THREAD

**Issue by UnBuenCamino** [tronscan/tronscan-frontend#952]

**Comment by myfocus** [comment]
Can you elaborate on it?

**Comment by UnBuenCamino** [comment]
Elaboration:
Open Tronscan, first problem is there is no about or check for updates pick, so I don't know what version I am using or if there is a newer version.  Click  upper corner open wallet, click green open wallet menu pick, Tronscan wallet window appears, click ledger, it turns red and says go to Tron app on Ledger.  Connect Ledger, enter pin, select Tron app, get sonic "ding a ling" sound feedback, Tronscan just displays 3 blinking size changing dots with no further error msg or instruction.  You need a timeout here with error or instruction messages.  Click open wallet again, there is no signout pick yet, just same old green open wallet pick.  Close Tronscan window, relaunch Tronscan app, open wallet, and poof, now handshake has been negotiated and Tronscan displays public key and green ledger connected message. Now, for the 3rd time in the 3rd place, this time on Tronscan wallet screen, I again click open wallet (with ledger connected green message), and wallet opens and my account values are displayed.

Today, at this time, I have a TRX balance of 18.339861, all received in the last few hours from an SR distrubution.  All of the rest of my TRX is properly displayed as Tron Power.  

I failed to get where I wanted on the first try and had to relaunch Tronscan to achieve success, if I am supposed to launch Tronscan first then log into Ledger, you need to make this clearer, if I do it in the wrong sequence and sequence is important, those 3 dots need to time out and I need a message explaining the proper sequence.  As it is, I just guess and try and retry until I achieve success.

Next, I scroll down to the freeze unfreeze section.  I click freeze and the Freeze Balance window comes up, but, as always, I can't remember exactly how much TRX I have.  You need a click here that says "Freeze Max", or if you want a more sophisticated approach, the click can say Freeze 25%, 50%, 75% or 100% and when I click my choice, the proper amount of TRX is filled into the TRX amount field.

So I scroll back up to the top to look again at my TRX amount, 18.339861, now, I don't know if I can freeze a fraction of a TRX or just integer 18.  Giving me the fill choices above obviates all of this.  I will try entering 18 in the TRX amount field. I do and click I confirm and then click Freeze Balance.  Nothing happens, no blinking dots, no error or status message, no nothing. I look at my Ledger and it is in some kind of screen save mode and unresponsive.

I unplug the Ledger, plug it in, re enter my pin, re select Tron app, and presto chango, I finally get the ! Unknown Error, an unknown error occurred.  I click ok.  I get another error page, ! Error, something went wrong while trying to freeze TRX.  I click ok and scroll back up to the top of TronScan and still see my 18.339861 TRX balance.  Two error messages and zero useful information.

I try freeze again with 18 TRX, this time I get a Hash Trans prompt on Ledger and confirm it, and shazam, a grammatically incorrect Tokens Frozen, successfully frozen 18 TRX appears. Successfully froze 18 or 18 were successfully frozen doesn't hurt my ears.

 I click ok and scroll up and select votes.  I might add, sometimes I have to trial and error 6 or 8 times just to get this far.

So, after clicking votes I click the red click ere to start voting.  I have 18.552 votes to distribute, again, I don't know if I can vote fractions of a TRX, the SRs I have voted for all show integer votes,  I now click the + bar for the SR I want.   One click transfers 18 votes to my SR leaving .552 remaining.  In previous attempts, I would often click again to try to vote the fraction.  Now I have a green Submit votes, which I click and I get the fast moving black bar display, again, with no written information on how to proceed.  At least give me a confirm your Hash Tx on your Ledger here or something.  I confirm it on the Ledger and get X Error, something went wrong while submitting your votes, Please try again later.  I click ok.  Maddeningly Tronscan displays a green Thanks for submitting your vote! 

I don't know how to refresh the screen here, so I scroll up and click wallet, account, the select votes, then click the red click here to start voting pick again. My good old 18.552 TRX are still listed as Votes Remaining.

I vote again, this time clicking twice, once for the 18, again for the .552, I get another poor grammar error of you spend to much votes, too, not to, you spent, not you spend.  A better message would be you can't vote fractions of a TRX, only whole integers or something like that.  I submit votes and get the same error, click ok, and get the same Thanks for submitting your votes green success message, except, I was not successful.

**Comment by UnBuenCamino** [comment]
I sign out, close Tronscan, re-launch, and holy Tron Power, Batman!!, my TRX balance is 0.339861 votes.  I click votes, and get Loading Super Representatives with the blinking Tron icon forever. I scroll back up and click wallet, account, then votes again, and this time the vote screen launches, and, you can't make this stuff up, I show 18.552 votes available.

I am now frustrated and will try again later.

Hope this helps.

**Comment by UnBuenCamino** [comment]
Another day, more elaboration.
This time, I connect my Nano S and open the Tron app on the Nano.
Now I launch Tronscan on my Win10Pro desktop.
Open wallet, open wallet, select Ledger, and it quickly connects.

It appears that sequence is important.  Connect Ledger, open Tronscan seems to work better than open Tronscan, connect Ledger.

From the Ledger Connected open wallet click, it took 5 or 10 seconds to open my wallet, during that time, Tronscan displayed an empty wallet, better o display an opening wallet..... message.

Ok, I have some SR Tron available, so I will freeze it and vote it.

Click freeze, enter TRX to the nearest rounded down integer, click I confirm..., click Freeze Balance.

Once again, upon clicking Freeze Balance, the button ghosts, but, other than that, I get zero on screen feedback.

I go to my Ledger screen and accept the transaction hash.  You really should display the transaction has on my Win10 screen, or at least give me a pick to display it, so, I can verfy the hash on my Ledger.

And, as before, after verifying hash on Ledger, I get an ! Error on Tronscan, something went wrong while trying to freeze TRX.  At this point, I have no confidence in this error message.  I don't know what it means or whether my TRX was really frozen or not. I click ok to acknowledge the message and scroll to the top of the screen where I see all of my TRX still unfrozen.  That is, my TRX balance never changed.

Just for grins, I click votes and click click here to start voting, and see a balance of 18.552 votes.  I thought I received indication in the last comment post that these votes were voted.  Now, they have reappeared as not voted.

I assign all votes to my favorite SR, click submit, and get a nice info screen telling me to confirm my votes on my Ledger, which, I do, and then get the X Error, something went wrong.....

I click ok, and get the green thanks for voting.  I think, I hope the guys that programmed the freezing and voting interface had nothing to do with the Tron blockchain.

I open my walled and see that my TRX for the day has not been frozen.
I scroll down to votes, click the tab, and it reports that my 18 votes from the previous attempt have now been voted.  So, I have some indicators of a successful vote and other indicators of an unsuccessful vote.  Which indicator are false?

I go back to wallet and try another freeze, this time, I get the expected Confirm transaction Freeze Coins window.

The tx hash on the screen does not match the one on the Tron.

I click ok to the error message.  Wallet shows my TRX is not frozen.

I try another freeze and am prevented from entering the value of my TRX.

Conclusion.  Your freeze and vote code is VERY buggy.  It appears like the bugs are non fatal and do not ultimately result in loss of my TRX.  But, the system is so buggy, it is almost completely unusable.  I have zero confidence in using my Tron for ANYTHING.  I don't even have confidence to unfreeze it and send it up to an exchange to trade it for something else.

You really need to have better quality control over the freezing and voting code.  It is really tarnishing users perception of Tron.  It's like you have no beta testing at all, or worse, the quality control you do have is simply not capable of generating clean relatively free of bug code. It really erodes my confidence in anything Tron.

Hope this helps you fix some of this.

**Comment by UnBuenCamino** [comment]
After I wrote this and submitted it, I went back to my wallet, and now I see a < 1 balance.  Clearly, some of your problems are related to what your screen displays in the interim period when you are validating transactions.  I don't expect instant transactions, I do expect instant and continually updating status error messages that let me know what is going on.  Other crypto interfaces I use are very good at this.

Now, by TRX for the day is frozen and available for voting.   I vote it and submit it and get a scrolling horizontal line where the error or success message should be. I confirm the tx on Ledger (I have no way of knowing if it was the correct hash, and the mismatch in hash previously has taken my confidence down to zero for doing anything significant with Tron.

Who knows, maybe tomorrow I will be able to vote the TRX I froze today.  Bottom line, your code for freezing and voting Tron is unacceptably buggy.

**Comment by UnBuenCamino** [comment]
Hi you guys,
Trying again to freeze and vote, and cannot do it.  I tried using Tronscan and a Tron Explorer Github screen.

Here is what would be really helpful.  Give me a Help, About pick that tells me the build of the app I am using.  In this screen give me a Check for Updates.  

It is kind of pointless for me to try to do something I cannot do over and over again unless something has changed.

As a general comment your error handling is very poor and uninformative.  It is possible that some of my problems arise from trying over and over again, the only technique that I have to eventually become successful.  When I submit something, do I need to wait for some kind of conformation?  Your error messages don't appear to be true error messages, maybe you need to refresh my wallet upon submit.  It is very frustrating to get an error message that says one thing, like TRX successfully frozen, but, have a wallet screen that shows that it is not frozen.  Same with voting, don't give me a thanks for voting and show me a screen that shows I did not vote.

Also, in general, you guys need a lot more quality control.  Maybe give some TRX rewards for reporting bugs in freezing and voting via some kind of submit form that at least gives you a chance to reproduce the error that has been submitted. I think this might be a good idea. Submit a bug, upon fix, drop a few TRX, probably doesn't even have to be much, depending on the bug.

I would really like to see Tron Scan evolve to be much more robust.  As is, I don't have much confidence in trying other features.

**Comment by Rovak** [comment]
I closed this issue to cleanup duplicate reports, the issue is still being looked into

**Comment by UnBuenCamino** [comment]
I'll give you more feedback if you want, what issue# should I post against.

Sent from ProtonMail mobile

-------- Original Message --------
