### ISSUE TITLE
Trouble opening wallet with Tronscan desktop with Ledger

### ISSUE THREAD

**Issue by htlee80** [tronscan/tronscan-frontend#962]
- I am unable to open up my wallet with Tronscan desktop with my Ledger Nano S.  All I get it "Open Tron app on your Ledger".  I have my Tron app open on the Ledger but still not connecting.  
<img width="1272" alt="tronscan ledger issue - screen shot 2018-12-26 at 1 17 05 pm" src="https://user-images.githubusercontent.com/46168363/50455100-827f8500-0911-11e9-9d6e-a7655ccb9aca.png">

**Comment by fomman** [comment]
its been a while, like a few weeks already.....u need to use this link https://tronscan.github.io/tronscan-frontend/#/account

**Comment by alexandra011** [comment]
You need to close and open again the app, took me a while to figure that out.

**Comment by TroyLindsey** [comment]
I have tried this multiple times as well and have not been successful it is very frustrating this should be the simplest part of the process.

**Comment by Rovak** [comment]
use https://tronscan.org instead of the desktop client

**Comment by TroyLindsey** [comment]
That’s one issue the other is wouldn’t open on safari so I had to an alternate browser 

 www.troylindsey.com

**Comment by habibawan1** [comment]
well i am not able to login to tron scan desktop app through nano ledger s please guide.
