### ISSUE TITLE
FROZEN TRX MISSING

### ISSUE THREAD

**Issue by Network66** [tronscan/tronscan-frontend#963]
I have trx that i froze two weeks ago and now nothing is showing?? i have 0 balance tron power??  how can i get my coins back please???   There is no option to unfreeze my coins.  They show as froze on the confirmation page but no balance or unfreeze option on the account page??

**Comment by fomman** [comment]
its been a while, like a few weeks already.....u need to use this link https://tronscan.github.io/tronscan-frontend/#/account

**Comment by Network66** [comment]
Thanks.  All good now :)
