### ISSUE TITLE
i can not to trade Reyna token

### ISSUE THREAD

**Issue by sonic1111** [tronscan/tronscan-frontend#964]
Hi, i see my Reyna tokens in my wallet 
TTMEvthacYz8sTNSYoWrWwYAR29Aseshok
but i can not to see it here so i can not to trade them
https://tronscan.org/#/exchange20?token=REY/TRX&id=34

**Comment by sonic1111** [comment]
I can not to trade REYNA token here https://tronscan.org/#/exchange20?token=REY/TRX&id=34  Because the system not shows it!!!!! But tokens are om my wallet!

**Comment by duncanvanloon** [comment]
It should be here : https://tronscan.org/#/exchange20?token=REY/TRX&id=34
