### ISSUE TITLE
[Bounty] Tronscan V2 - Voting Cancel Bug

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#97]
Bug Report
------------
i take part in the vote of the SR and select the desired number of tronpower.
![image](https://user-images.githubusercontent.com/39301026/40871840-d9de007c-6643-11e8-82a4-3404eedb09b9.png)

100 TP for CryptoChain and 10 TP for CryptoGuyInZA 
![image](https://user-images.githubusercontent.com/39301026/40871859-3f9eaaf6-6644-11e8-8b07-140236f590f2.png)
I confirm the voting with the submit button 

![image](https://user-images.githubusercontent.com/39301026/40871869-64adcb42-6644-11e8-8aa1-23601812ace1.png)

later i remembered that i want to change my vote and start the voting again.
my old values are stored, thats fine!
![image](https://user-images.githubusercontent.com/39301026/40871882-a71cf322-6644-11e8-9a49-60a61e1c6b34.png)

now to the problem/bug if I now remove or change a voting value and click on the cancel button the changes are saved
![image](https://user-images.githubusercontent.com/39301026/40871900-fddf81d4-6644-11e8-9996-0d5db73ebfd7.png)

![image](https://user-images.githubusercontent.com/39301026/40871907-0784ec24-6645-11e8-885f-c7dd20f03791.png)

![image](https://user-images.githubusercontent.com/39301026/40871914-0fc76b0a-6645-11e8-8767-d03d91d7f65d.png)

Check:
![image](https://user-images.githubusercontent.com/39301026/40871922-2aac6830-6645-11e8-865a-003da52aa1da.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
02. June 2018 5:00 am (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

Bounty Program
--
https://twitter.com/justinsuntron/status/1002072890349531137

**Comment by PMD3VSolution** [comment]
the problem can be reproduced even if I make changes
![image](https://user-images.githubusercontent.com/39301026/40871948-8751b770-6645-11e8-8491-d31a08164ee2.png)

**Comment by PMD3VSolution** [comment]
I have analyzed the problem a more, the cancel button also saves the voting
![image](https://user-images.githubusercontent.com/39301026/40871964-f92d5840-6645-11e8-8623-044722d4c69b.png)

**Comment by joe-meyer** [comment]
This doesn't actually seem to submit the votes, it's just remembering the state of the votes prior to cancelling. If you refresh and go back into the wallet all the votes are still there (or at least they appear to be for me).
