### ISSUE TITLE
/api/asset/transfer - tokenName seems to be case sensitive

### ISSUE THREAD

**Issue by jkincali** [tronscan/tronscan-frontend#970]
The API for getting asset transfers, /api/asset/transfer, seems to be giving different results for tokenName, depending on whether or not the parameter given is in capital letters (seems to be case sensitive).  Calling with TRX and trx gives different results.  GAME and game give different results.

**Comment by Gennttii** [comment]
I want to get USDT transactions only but this link doesn't give me anything, how to write the token name for USDT, tried with capital and lowercase letters, gives nothing..:

http://apilist.tronscan.org/api/transfer?sort=-timestamp&token=usdt&address=TEmcaT3xRarqhju1XrbskcV3w3UKz2iBqi
