### ISSUE TITLE
TronScan Wallet Issues

### ISSUE THREAD

**Issue by ry23** [tronscan/tronscan-frontend#972]
Hello, 

I Purchased Ante from the trx.market and it deposited into my Tronscan wallet. I have been trying to send my Ante to my Tron Link wallet and it will not transfer them. I have also been trying to sell the ante on trx.market thats in my tronscan wallet and it will not let me make transactions on the market. 

Any help would be greatly appreciated.

Thanks
Ryan

**Comment by regnert** [comment]
I can't send any trc10 tokens either, been a few days.

**Comment by jpharney** [comment]
I put in a sell order of 100 ANTE at price 40. It does not show in my order log(all other orders are showing). BUT IT SUBTRACTED FROM MY ANTE BALANCE!!!
