### ISSUE TITLE
Error when freezing. Not enough TRX not true

### ISSUE THREAD

**Issue by alfonrp** [tronscan/tronscan-frontend#978]
Hi,

Trying to freeze. I have more than 1 TRX but I receive message: "Not enough TRX".

Regards,
Arp.

**Comment by sspyue** [comment]
Same issue.

**Comment by sspyue** [comment]
Problem solved.  Use this link:  https://tronscan.github.io/tronscan-frontend/#/.  I also encountered error message when trying to use all my votes.  Needed to round down to whole number and the vote went through.

**Comment by msc82** [comment]
https://tronscan.github.io/tronscan-frontend/#/.     where did you bring that ?    i hope devs will answer if we can use it

**Comment by sspyue** [comment]
I got that link from reading similar tickets and how others solved it.

**Comment by piet241** [comment]
Hello,
I have the same issue I´m trying to freeze but I receive message: "Not enough TRX".
I hve more than 1000TRX avialable on my wallet!
What I have to do after I clicked on the link above?
