### ISSUE TITLE
[Bounty] Tronscan V2 - TRANSACTION VIEWER - without function

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#98]
Bug Report
------------
the use of TRANSACTION VIEWER did not allow me to search for an appropriate transaction
![image](https://user-images.githubusercontent.com/39301026/40871992-92f61e4e-6646-11e8-80a0-a9da7a89e284.png)
i use the hash of an transaction

![image](https://user-images.githubusercontent.com/39301026/40872007-bd65f50a-6646-11e8-9634-8a5ac159cde1.png)

![image](https://user-images.githubusercontent.com/39301026/40872016-f215ed14-6646-11e8-88bc-95d29b63b0fa.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
02. June 2018 5:00 am (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

Bounty Program
--
https://twitter.com/justinsuntron/status/1002072890349531137

**Comment by Rovak** [comment]
The transaction viewer requires a HEX string which is a serialized transaction, i shall make the documentation more clear
