### ISSUE TITLE
SEED issue

### ISSUE THREAD

**Issue by towliie** [tronscan/tronscan-frontend#984]
Hey, using tronscan + ledger. Few days ago i've sold all my seeds with no problems. Since then i can see the transactions of the daily rewards on tronscan but in my wallet SEED doesn't show up at all even with 0 balance. Any ideas?

**Comment by TronRevolution** [comment]
I am also seeing the same thing, my tronscan seed balance showing 97 seed token.  Been getting seed tokens from voting but my balance never changes, still showing 97 seed tokens.   Please help ?
