### ISSUE TITLE
votes not working

### ISSUE THREAD

**Issue by Spanysh37** [tronscan/tronscan-frontend#985]

**Comment by akcryptoguy** [comment]
I'm seeing the same thing; I am unable to change votes the same as a month ago.

**Comment by Spanysh37** [comment]
Hello, the solution that I found is that the desktop app isn't working
properly. You can go to this link I found in the forum and vote you can
bookmark the page I've been using it instead of the desktop version.
https://tronscan.github.io/tronscan-frontend/#/account
