### ISSUE TITLE
cannot send tokens using Ledger with web version of tronscan

### ISSUE THREAD

**Issue by jakubsn** [tronscan/tronscan-frontend#986]
using macOS/chrome -  when trying to send funds the doalog pops up for confirmation but no confirmation shows on ledger

when confirming dialog red warning comes up - something went wrong with the transaction

**Comment by jakubsn** [comment]
using :   https://tronscan.github.io/tronscan-frontend/#/account

**Comment by regnert** [comment]
Same problem with any Tron wallet I use

**Comment by peteroosterbroek** [comment]
I have the same problem. I can't send to any wallet and not to Binance eather!!!

**Comment by alexandra011** [comment]
me too. But you just have to keep trying for a few times and it will work!

**Comment by AlexBarbulescu** [comment]
What's the difference between https://tronscan.github.io/tronscan-frontend/#/account and https://tronscan.org/#/ beside able to login with ledger? is tronscan.github.io secure? without worrying about loosing funds on device?

**Comment by Klng79** [comment]
same problem. try many time still not work.

**Comment by Klng79** [comment]
Any progress ? please kindly update.

**Comment by regnert** [comment]
still waiting. Keep getting notifications of tokens received but balance doesn't reflect increase. When I try to send tokens it just fails ... over and over and over

**Comment by jakubsn** [comment]
today i was able to send TRX but the tokens (SEED) i still cannot send
