### ISSUE TITLE
[Bounty] TRON.NETWORK - Login - E-Mail Address is case sensitive

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#99]
Bug Report
----------
at the login it plays a role how the email address was entered during registration. 
the problem can be fixed with an toUpperCase() method 

 if toUpperCase(DB hash) == toUpperCase(entered-mail-address) then -> credentials valid
![image](https://user-images.githubusercontent.com/39301026/40872146-dd3ce0b6-6649-11e8-9566-bb2b6fd71f5b.png)

![image](https://user-images.githubusercontent.com/39301026/40872147-f00eade6-6649-11e8-9297-f3a0afc6bc54.png)

![image](https://user-images.githubusercontent.com/39301026/40872150-fc746f30-6649-11e8-92b9-cf375774d5f0.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
02. June 2018 5:00 am (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

Bounty Program
--
https://twitter.com/justinsuntron/status/1002072890349531137

**Comment by Rovak** [comment]
I'm not sure where the right place is to report `tron.network` issues, but this repository isn't meant to track those bugs
