### ISSUE TITLE
Trade done on TRXMARKET

### ISSUE THREAD

**Issue by Traderjits** [tronscan/tronscan-frontend#992]
someone PLEASE HELP, I just traded 780K PLAY TRC-20 for 5K fish of TRX and its nowhere to be found in my wallet. Its like it never happened can someone help

**Comment by Traderjits** [comment]
It will post to your account. Give it time. Periodically check ur tronscan balance amd wallet. The system is really slow due to maintnece plus if the trading volume was poor it might time time for it to reflect. My problem showed up in my account hrs later

On Jan 10, 2019, at 1:25 PM, cniemann85 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi the dame happened to me!
Traded TRX for ANTE
TRXMARKET says ALL DEALT, TRX is gone but ANTE hasn't been credited
-> TVoDEqQqHHW3TYmGGDFvo4siGRjPBMMtiA
-> see screenshot from TRX Market:

[antenotdealt]<https://user-images.githubusercontent.com/46574128/50988581-6254e600-150d-11e9-93b8-d38a4ef745bb.JPG>

**Comment by cniemann85** [comment]
OK, thx!
