### ISSUE TITLE
Tokens not showing on my balance

### ISSUE THREAD

**Issue by alexandra011** [tronscan/tronscan-frontend#993]
Hi, i use tronscan with ledger. I am getting the rewards hash, but tokens are not showing on my balance, i did transfer some tokens from other wallet to my tronscan, and it doesn't show either. I also created a token called Zapdos and doesn't show either Help? Thanks

**Comment by gdoneit** [comment]
Same issue here, looking at tronscan.org the tokens are showin correctly, but i cannot log in there with my ledger. once logging in to tronscan.github/ tronscan-frontend, same issue as above, tokens are not there.
