### ISSUE TITLE
Getting "Something Went Wrong Again" for Token Transaction Send & Tron Token for FREEZE Transaction attempt

### ISSUE THREAD

**Issue by lbjenious** [tronscan/tronscan-frontend#998]
**FAILURE DESCRIPTION:**
Getting "Something Went Wrong Again" for Token Transaction Send & Tron Token for FREEZE Transaction attempt.

**ATTACHED VIDEO include  PROCESS with Error Message:**
I have attached a screen capture of the actual process [ Freeze process; although the same error failure will occur when I attempt to send any TRON or dAPP token to another wallet.

---------------------------------------
**Ledger Nano S HW / SW Details:**
- Tron Wallet SW Version:0.0.2
- Browser Settings: YES
- Firmware / Secure Element:1.4.2
- MCU:1.5

-----------------
**CHROME BROWSER:** 
- https://tronscan.github.io/tronscan-frontend/#/account
- Google Chrome is up to date
- Version 71.0.3578.98 (Official Build) (64-bit)

**Additional Information:**
The process/step sequence continues round-robin until the loop exits with the error message. The last time I tried to send TRX to Tron Mobile Wallet --- it took an hour of trying and retrying -- pressing Ledger Nano S confirmations for send, amount, hash sequence shown in the video; eventually, I was able to move TRX to another Wallet.

However, I have NO idea, as to what made the transactions succeed nor WHY this is happening to begin with. 

FYI: For now and until I can regain stability again, I have decided not to transfer any additional tokens to TRON BlockChain Explorer.

Important: This problem does NOT occur for other NON TRON wallets installed on Ledger Nano S.  That said, the wallet appears to be functioning properly in general but is experiencing some compatibility problem OR hitting a BUG (perhaps unknown and dcoumented)

KINDLY ADVISE WORKAROUND!!

[SomeThingWentWrong-LedgerNanoSTRON.zip](https://github.com/tronscan/tronscan-frontend/files/2746110/SomeThingWentWrong-LedgerNanoSTRON.zip)

[SomethingWentWrong-2.mov.zip](https://github.com/tronscan/tronscan-frontend/files/2746113/SomethingWentWrong-2.mov.zip)
[SomethingWentWrong-1.mov.zip](https://github.com/tronscan/tronscan-frontend/files/2746115/SomethingWentWrong-1.mov.zip)

 BUGs will occur....it's part of the vetting process and improving upon code releases...

That said. Please Advise any fix and/or workaround.

Thanks, in advance -- SR / TRON SUPPORT
Lionell B Jenious / Community supporter and BIG on TRON  **"GO TRON GO"**

**Comment by regnert** [comment]
same problem

**Comment by lbjenious** [comment]
This good to know (i.e. regnet ), a reproducible pattern. This kind of feedback and effort by the community only helps TRON Team / Developers to help identify and validate the problem;  hopefully, soon there will be a fix!

Let's see if others will share and provide their input; it's truly a team effort needed!

**Comment by regnert** [comment]
I was able to unfreeze a few hours ago. Thanks for your help.
