### ISSUE TITLE
TRXMARKET - ALL DEALT but TRX and or ANTE gone!

### ISSUE THREAD

**Issue by cniemann85** [tronscan/tronscan-frontend#999]
Traded TRX for ANTE
TRXMARKET says ALL DEALT, TRX is gone but ANTE hasn't been credited

-> TVoDEqQqHHW3TYmGGDFvo4siGRjPBMMtiA
-> see screenshot from TRX Market:
![antenotdealt](https://user-images.githubusercontent.com/46574128/50988827-0b034580-150e-11e9-9794-1077160a5ab7.JPG)

PLEASE HELP

**Comment by cniemann85** [comment]
ANTE is there but can't freeze them or bet any TRX on Tronbet.
this issue seems interconnected

**Comment by 5u8v3r7** [comment]
I am having the same issue, 130000 trx vanished, very concerning
